### DISCUSSION TITLE
AdGuard Home showing all clients as the same

### DISCUSSION THREAD

**Discussion by thedinz** [AdguardTeam/AdGuardHome#2736] [Q&A]
Hello

I installed adguard home on docker on my network, it's working as I can see by what it's blocking. The only issue I see is there is only 1 client being identified and that's the machine running docker, adguard is acting as if every query is coming from that machine.

What did I do wrong and how do I fix this? I even went into settings a manually added a few clients but still only shows the docker-machine as the client making all requests rather than the actual devices that are..

**Comment by alexpovel** [comment]
Just a guess, but you are probably running it with the `--port` option to `docker run`? This will run it through `docker-proxy`. I am also using the built-in DHCP server, for which running the container that way is not possible in the first place.

Therefore, I run it with the `network_mode: host` option set (docker-compose). For example:

```yaml
version: "3.2"

volumes:
  work:

services:
  main:
    # For configs, see https://hub.docker.com/r/adguard/adguardhome
    image: adguard/adguardhome
    container_name: adguard
    network_mode: host  # Required for DHCP server
    volumes:
      - work:/opt/adguardhome/work
      - ./conf:/opt/adguardhome/conf
    restart: unless-stopped
```

This will show up as:

```bash
$netstat -tulpn
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp6       0      0 :::80                   :::*                    LISTEN      11192/AdGuardHome
tcp6       0      0 :::53                   :::*                    LISTEN      11192/AdGuardHome
...
udp        0      0 0.0.0.0:67              0.0.0.0:*                           11192/AdGuardHome
udp        0      0 0.0.0.0:68              0.0.0.0:*                           594/dhcpcd
...
udp6       0      0 :::53                   :::*                                11192/AdGuardHome
```

Now, AGH runs less isolated, but no longer behind the docker proxy. It would say `docker-proxy` for you (presumably) where it now says `AdGuardHome`. This allows your AGH instance to also see all real source IPs. It won't map them to hostnames properly. For that, you would also need to use it as your DHCP server (unless you make the effort to map everything manually -- not a great idea).

Note that I've never run your setup (`docker run` with `--port`), so my guess might be off.
