### DISCUSSION TITLE
New flag --no-etc-hosts : explainations and how to use it with a docker installation ?

### DISCUSSION THREAD

**Discussion by MilesTEG1** [AdguardTeam/AdGuardHome#3025] [Q&A]
Hello,
With the new build v0.106.0 there is a "new flag `--no-etc-hosts` to disable client domain name lookups in the operating system's /etc/hosts files ([#1947](https://github.com/AdguardTeam/AdGuardHome/issues/1947))."
But when I read the #1947 issue, I don't understand what does this flag...
is it with the host filter file I set in "blocking filter list" ?

And, when I'll correctly understand the purpose of this new flag, how to use it with a docker installation (with docker-compose file) ?

Thanks for your help 😃

**Comment by EugeneOne1** [comment]
@MilesTEG1, hello!  The `--no-etc-hosts` flag simply makes _AdGuard Home_ exclude the hosts listed in `/etc/hosts` file from the runtime clients list.  It means that these hosts will be resolved in a usual way (e.g. via upstream servers or local resolvers).

To run _AdGuard Home_ in a container with this new flag run:

```sh
docker run --name adguardhome \
    -v /my/own/workdir:/opt/adguardhome/work \
    -v /my/own/confdir:/opt/adguardhome/conf \
    -p 53:53/tcp -p 53:53/udp \
    -p 80:80/tcp -p 3000:3000/tcp \
    -p 67:67/udp -p 68:68/tcp -p 68:68/udp \
    -p 443:443/tcp \
    -p 853:853/tcp \
    -d adguard/adguardhome \
    --no-etc-hosts
```

You may notice, that this command is taken directly from our [wiki](https://github.com/AdguardTeam/AdGuardHome/wiki/Docker#3-create-and-run-the-container) with a little addition of `--no-etc-hosts`.  Of course, you should use your own settings.  This probably must be documented more accurately.

In case of using **Dockerfile**, to use this flag, you should just append it to `CMD` section:
```Dockerfile
CMD [ \
	"--no-check-update", \
	"--no-etc-hosts", \
	"-c", "/opt/adguardhome/conf/AdGuardHome.yaml", \
	"-h", "0.0.0.0", \
	"-w", "/opt/adguardhome/work"
]
```

**Reply by MilesTEG1** [reply]
Thank you for the answer.
But I'm using a `docker-compose.yml` file to create the container. (I use Docker on a Synology DS920+)
```yaml
---
  version: "2.4"
  services:
    adguardhome_macvlan:
      image: adguard/adguardhome:latest         # https://github.com/AdguardTeam/AdGuardHome
      container_name: adguardhome_macvlan
      hostname: AdGuard-Home--DS920+
      environment:
        - PUID=1000  # Utiliser la commande (en SSH) : id NOM_UTILISATEUR
        - PGID=100   # Utiliser la commande (en SSH) : id NOM_UTILISATEUR
        - TZ=Europe/Paris
        - LANG=fr_FR.UTF8
        - LANGUAGE=fr_FR.UTF8
  
      # ###############
      # Le label ci-dessous permet à Watchtower de faire les mises à jour automatiquement
      # Cela peut-être supprimé si Watchtower n'est pas utilisé.
      labels:
        - "com.centurylinklabs.watchtower.enable=true"
      # ###############
  
      volumes:
        - "/volume1/docker/adguardhome_macvlan/work:/opt/adguardhome/work"
        - "/volume1/docker/adguardhome_macvlan/conf:/opt/adguardhome/conf" 
  
      networks:
        macvlan-network:
          ipv4_address: 192.168.xxx.yyy     # Mettre ici l'IP macvlan dans la plage définie dans les scripts
  
      restart: unless-stopped
  
      healthcheck:
        test: "/bin/netstat -pant | /bin/grep 53"
        interval: 45s
        timeout: 30s
        retries: 3
  
  networks:
    macvlan-network:        # Ce réseau devra bien entendu être créé avant avec le script annexe ou avec Portainer.
      external: true
```

Is it possible to use the `--no-etc-hosts` with a docker-compose.yml file ?


For the question about what the tag does : 
> AdGuard Home exclude the hosts listed in /etc/hosts file from the runtime clients list.
You're talking about the  /etc/hosts file inside the container ?
I'm afraid that the blocking list filters are what are excluded :
![image](https://user-images.githubusercontent.com/29298312/116553430-6681b900-a8fa-11eb-98b4-1e82ec335895.png)

Thank you again for your help :relaxed:

**Reply by EugeneOne1** [reply]
The file in question is `/etc/hosts` which is located inside the container.  The filter lists shouldn't be impacted.

Since docker-compose files only provide the ability to rewrite the whole `CMD` section of `Dockerfile`, I suppose You should copy the commands from the original `Dockerfile` with appropriate additions and insert it into your docker-compose file's `command` section, like this:

```yaml
adguardhome_macvlan:
    # Your settings.
    command:
        - '--no-check-update'
        - '--no-etc-hosts'
        - '-c'
        - '/opt/adguardhome/conf/AdGuardHome.yaml'
        - '-h'
        - '0.0.0.0'
        - '-w'
        - '/opt/adguardhome/work'
    # Your other settings.
```
