### DISCUSSION TITLE
Custom "Domain name not resolved" web page

### DISCUSSION THREAD

**Discussion by DavidOsipov** [AdguardTeam/AdGuardHome#3073] [Ideas]
Hello, guys!
Do you think it is a good idea to show a custom web page like "This domain is blocked because ... You're secured by Adguard Home" instead of boring "Domain name not resolved"? I think it's convenient to know that Adguard home has blocked a domain and why + moreover additional brand awareness. And I think this feature is quite easy to implement.

**Comment by ainar-g** [comment]
Hello.  From what I can tell, [this] is the current way to do it.

[this]: https://github.com/AdguardTeam/AdGuardHome/issues/454#issuecomment-548269055

**Reply by MilesTEG1** [reply]
```yaml
  parental_block_host: family-block.dns.adguard.com
  safebrowsing_block_host: standard-block.dns.adguard.com
...
  safesearch_enabled: true
  safebrowsing_enabled: true
``` 
Setting this two variables works only for threats and parenting control.
What @DavidOsipov wants, and what I want too, is what proposed @Bluscream here for all the filters rules : 
> _Originally posted by @Bluscream in https://github.com/AdguardTeam/AdGuardHome/issues/454#issuecomment-499688874_
> Here's a mockup for the block page:
> 
> ![](https://user-images.githubusercontent.com/3318223/59064548-d02def80-88aa-11e9-903d-a7378bbb2fca.png)

Currently, all I get for a domain filtered by rules, is :
![image](https://user-images.githubusercontent.com/29298312/117189805-e4ecc800-adde-11eb-9063-ed66d3c02c08.png)
(or whatever the setting is set in AdGuard Home Blocking mode :
![image](https://user-images.githubusercontent.com/29298312/117190082-3f862400-addf-11eb-9490-83952bc99a6c.png)

So, How can we set a message like @Bluscream posted some years ago ? (in addition to safebrowsing block).

Thanks.
