### DISCUSSION TITLE
Webhook on client query

### DISCUSSION THREAD

**Discussion by alexdelprete** [AdguardTeam/AdGuardHome#3662] [Q&A] [answered]
Hello,

first of all, let me tell you I simply love AdGuardHome, impressive piece of sw, very reliable and simple to use (one exec and one config file) and with a nice GUI. Congrats to all devs, keep up the great job.

I want to achieve something that seems out-of-scope for a dns server, but maybe AdGuardHome can allow me to do it:

- I have an EZVIZ DB1 doorbell, it's a wireless device, and I'd like to intercept when someone rings pressing the button, to send an event to my Home Assistant. RIght now I'm using a hardware device to do this, but I'd prefer a software solution.
- Unfortunately the doorbell doesn't have an open interface, and even using its cloud API, the push button event is not managed
- Someone noticed that everytime the button is pressed, the doorbell does a specific DNS query:

![image](https://user-images.githubusercontent.com/7027842/134815363-5d28cd32-8abb-4d57-8bd5-d43ddd63512e.png)

- the **alarm** string is always there, only the second part can change based on geography
- I'm looking for a way for AGH to send a callback to HA via webhook everytime it is queried from that specific client for that specific query (containing the string **alarm**)

So questions are:

- does AGH support webhooks? I'd like to use those for my HA automations
- is this even possible with AGH?
- if it's possible, what's the proper way to do it?

Thanks for any help or advice,

Alessandro

**Comment by ameshkov** [comment, marked as answer]
AGH does not support webhooks, at least not at this moment. But I think this is indeed possible using the [API](https://github.com/AdguardTeam/AdGuardHome/tree/master/openapi). You'll need to poll the query log (rather often, every second maybe?) for new records and look for this domain there.

**Comment by alexdelprete** [comment]
Thanks for the answer. I wanted to avoid polling. I'll wait for webhooks to be available.

**Comment by FlorianObermayer** [comment]
FWIW:

Here is a home assistant configuration example I use to wake up my NAS on DNS query:

```yaml
# configuration.yaml
sensor:
  - platform: rest
    name: "Last DNS Query (nas.mydomain.com)"
    resource: "http://<ADGUARD_SERVER_IP>/control/querylog?search=nas.mydomain.com&limit=1"
    authentication: basic
    username: "<USERNAME>"
    password: "<PASSWORD>"
    scan_interval: 5
    value_template: "{{ value_json.oldest }}"
    unique_id: "<UUID>"
```

```jinja
# template binary sensor state template

{{ now() - states('sensor.last_dns_query_nas_mydomain_com') | as_datetime(default=0) < timedelta(seconds=11) }}
```
