### DISCUSSION TITLE
How to change the Adguard DNS listen ports from 127.0.0.1 to something else

### DISCUSSION THREAD

**Discussion by madd74** [AdguardTeam/AdGuardHome#4265] [Q&A]
I installed using docker, and the two default DNS to listen to are:

127.0.0.1
172.18.0.2

My router will not allow a loopback address of 127.0.0.1, however, my router is on 192.168.0.1 and any 192.168.0.X address will work.  Is there a way to change this to something in the 192.168.0.X, and if so, how would I go about doing that?

**Comment by ainar-g** [comment]
Hello.  If you're using Docker, those are the addresses *within* the container.  By default, the AdGuard Home Docker container binds to `127.0.0.1`, if I recall correctly.  To make it bind to a different address, you can either use the `--ip` flag when starting the container or add the addresses to the `-p` flags.  See [this][1] and [this][2] section in the Docker documentation.

We should probably add that to [our Wiki page about Docker][3].  Along with the explanation of the addresses that users will see in the UI.

[1]: https://docs.docker.com/engine/reference/run/#network-settings
[2]: https://docs.docker.com/engine/reference/run/#expose-incoming-ports
[3]: https://github.com/AdguardTeam/AdGuardHome/wiki/Docker

**Reply by madd74** [reply]
Actually, this is what is in the yml file:

```
version: '3.3'
services:
    run:
        container_name: adguardhome
        restart: unless-stopped
        volumes:
            - '/home/${USER}/server/configs/adguardhome/workdir:/opt/adguardhome/work'
            - '/home/${USER}/server/configs/adguardhome/confdir:/opt/adguardhome/conf'
        ports:
            - '53:53/tcp'
            - '53:53/udp'
            - '67:67/udp'
            - '68:68/udp'
            - '68:68/tcp'
            - '80:80/tcp'
            - '443:443/tcp'
            - '443:443/udp'
            - '3000:3000/tcp'
        image: adguard/adguardhome
```
It only has the ports in here.  This is actually the first time I am using docker so I am not exactly clear where I would use this to make it happen.  So if I wanted 192.168.0.10 to be the DNS instead of 127.0.0.1, would I incorporate that into the .yml file, or would that be put into the run command of `docker-compose up -d`?  Someone else replied that may or may not have my answer also...
