### DISCUSSION TITLE
First launch: blank screen after clicking "Get started"

### DISCUSSION THREAD

**Discussion by bertmelis** [AdguardTeam/AdGuardHome#4474] [Q&A] [answered]
I'm running AdGuard Home in a Podman container (pulled docker.io/adguard/adguardhome:edge). The service starts and the logs tell me to browse to http://serverip:3000/install.html

A nice introduction page is served but when I click "Get started", the screen goes blank. The javascript console shows an error though:

```
TypeError: Cannot read properties of undefined (reading 'includes')       install.1fad9539c334c1722a15.js:27
    at V (install.1fad9539c334c1722a15.js:1:52711)
    at d (install.1fad9539c334c1722a15.js:43:61549)
    at install.1fad9539c334c1722a15.js:43:61898
    at Array.map (<anonymous>)
    at _ (install.1fad9539c334c1722a15.js:43:61874)
    at Vi (install.1fad9539c334c1722a15.js:27:57930)
    at hs (install.1fad9539c334c1722a15.js:27:104169)
    at cl (install.1fad9539c334c1722a15.js:27:96717)
    at sl (install.1fad9539c334c1722a15.js:27:96642)
    at $s (install.1fad9539c334c1722a15.js:27:93672)
```

The :3001 beta page does load correctly.

Might it have something to do with the -h 0.0.0.0 option that is passed by default? Reason is that after finishing the setup-wizard, it redirects me to this IP which doesn't respond obviously.

EDIT
for reference:
```yml
version: "3"
services:
    adguardhome:
        container_name: adguardhome
        image: adguard/adguardhome:edge
        # specifying user doesn't work because "needs to be run as administrator"
        #user: 1000:1000
        #network_mode: host
        ports:
          - 53:53
          - 3000:3000/tcp
        volumes:
          - /home/podmanager/adguard/work:/opt/adguardhome/work:Z
          - /home/podmanager/adguard/conf:/opt/adguardhome/conf:Z
        restart: unless-stopped
```
