### DISCUSSION TITLE
AdGuard Home и реверс-прокси NGINX в одной подсети Docker

### DISCUSSION THREAD

**Discussion by ammnt** [AdguardTeam/AdGuardHome#4548] [Q&A] [answered]
Здравствуйте,

установил AdGuard Home и реверс-прокси NGINX при помощи Docker, но не через Compose, а просто в одной подсети. NGINX и AGH друга друга видят в сети Docker:

![image](https://user-images.githubusercontent.com/45385632/166686507-7d621ecf-aa25-463e-87d9-02d028f89417.png)

![image](https://user-images.githubusercontent.com/45385632/166688288-ac4a34bf-78e3-48e0-a787-42d6df617774.png)

Проблема в том, что реверс-проксирование не работает:

![image](https://user-images.githubusercontent.com/45385632/166686220-d817a90a-7e6d-49a9-a705-8d777cae0d80.png)

Ни HTTP ни HTTPS:
```
server {
    listen 443 default_server http2 ssl fastopen=256;
    server_name test.ammnt.app;
    ssl_protocols TLSv1.3;
    ssl_ecdh_curve X25519;
    ssl_ciphers TLS_CHACHA20_POLY1305_SHA256:TLS_AES_256_GCM_SHA384:ECDHE:!COMPLEMENTOFDEFAULT;
    ssl_certificate /etc/nginx/ssl/fullchain.pem;
    ssl_certificate_key /etc/nginx/ssl/privkey.pem;
    ssl_trusted_certificate /etc/nginx/ssl/fullchain.pem;

location / {
    proxy_pass http://172.16.0.5:80;
    proxy_redirect / /;
    proxy_cookie_path / /;
}
}
```

```
server {
    listen 443 default_server http2 ssl fastopen=256;
    server_name test.ammnt.app;
    ssl_protocols TLSv1.3;
    ssl_ecdh_curve X25519;
    ssl_ciphers TLS_CHACHA20_POLY1305_SHA256:TLS_AES_256_GCM_SHA384:ECDHE:!COMPLEMENTOFDEFAULT;
    ssl_certificate /etc/nginx/ssl/fullchain.pem;
    ssl_certificate_key /etc/nginx/ssl/privkey.pem;
    ssl_trusted_certificate /etc/nginx/ssl/fullchain.pem;

location / {
    proxy_pass https://172.16.0.5:8443;
    proxy_redirect / /;
    proxy_cookie_path / /;
}
}
```
```
Настройки самого AGH тоже подправил:

bind_host: 0.0.0.0
bind_port: 80
trusted_proxies:
  - 127.0.0.0/8
  - ::1/128
  - 172.16.0.0/24
  tls:
  enabled: true
  server_name: test.ammnt.app
  force_https: true
  port_https: 8443
  allow_unencrypted_doh: true
```

![image](https://user-images.githubusercontent.com/45385632/166687154-a238e8ac-b0ad-49ac-8744-4f3b72bf1e0e.png)

Не пойму где ошибся. Будет ли так работать в принципе? Буду благодарен за любую помощь и идеи🙏🏼

Спасибо.
