### DISCUSSION TITLE
Testing the AdguardHome docker image with 0 capabilities

### DISCUSSION THREAD

**Discussion by skelder** [AdguardTeam/AdGuardHome#4571] [Q&A]
Version: latest tag on docker hub
Install source: Docker hub
Device: Synology DS920+
CPU:AMD64
OS:Synology OS(Linux)

I was curious if I could possibly run the Adguard Home Docker version without giving it's container any capabilities.

I explicitly dropped all capabilities and got error
`standard_init_linux.go:230: exec user process caused: operation not permitted`
Adding only `NET_BIND_SERVICE` capability solved the issue

After that I decided to test further to see if setting all of the ports outside of 0-1024 range would allow me to run the container without `NET_BIND_SERVICE` capability.
Settings dns port to 3053 and browser ports to 3080 and 3443 resulted in same error.

Now I am confused since I thought `NET_BIND_SERVICE` is only needed if container required the ports below 1024.

Can someone explain why we need `NET_BIND_SERVICE` even though we are not dealing with ports below 1024?

**Comment by ainar-g** [comment]
Hello.  Have you also changed `port_dns_over_tls`, `port_dns_over_quic`, and other encrypted DNS ports?  Also, do you use AdGuard Home's DHCP?

**Reply by skelder** [reply]
I tried again with your suggestions and now the only "ports" with number below 1024 are 'beta_bind_port' and 'port_dnscrypt' both of which I did not find settings in the web ui. 

Next I manually edited the config file so that even 'beta_bind_port' and 'port_dnscrypt' are both way above 1024 along with other ports

Results were same

I think I did every port setting that I could find in the config file:
- 'bind_port'
- 'beta_bind_port'
- 'port'
- 'port_https'
- 'port_dns_over_tls'
- 'port_dns_over_quic'
- 'port_dnscrypt'

EDIT: I forgot to mention that I did not use DHCP in any of my test runs

**Reply by ainar-g** [reply]
@skelder, it's probably due to the `setcap` inside the container then.  You can remove it inside the container using a custom entrypoint that calls `setcap 'cap_net_bind_service=-eip' /opt/adguardhome/AdGuardHome` within the container before launching the binary.

**Reply by skelder** [reply]
I am currently trying to implement your suggestion without having to build a new Dockerfile myself.

I tried with following docker-compose.yml file:
```yml
version: '3.3'
services:
    run:
        container_name: adguardhome
        restart: unless-stopped
        volumes:
            - '/volume1/docker/adguard/work:/opt/adguardhome/work'
            - '/volume1/docker/adguard/conf:/opt/adguardhome/conf'
            - '/volume1/docker/adguard/entrypoint.sh:/entrypoint.sh'
        ports:
            - '3053:3053/tcp'
            - '3053:3053/udp'
            - '3080:3080/tcp'
            - '3443:3443/tcp'
            - '3443:3443/udp'
        cap_drop:
            - ALL
        network_mode: bridge
        entrypoint: /entrypoint.sh
        command: --no-check-update -c /opt/adguardhome/conf/AdGuardHome.yaml -h 0.0.0.0 -w /opt/adguardhome/work
        image: adguard/adguardhome
```

and entrypoint.sh:
```
#!/bin/bash
setcap 'cap_net_bind_service=-eip' /opt/adguardhome/AdGuardHome
/opt/adguardhome/AdGuardHome "$@"
```

with same AdguardHome.yaml file from previous attempts with changed ports and whatnot

It is giving me same errors.

I think I am missing some vital piece here, but I cannot figure it out.

**Reply by ainar-g** [reply]
@skelder, try explicitly dropping only `net_bind_service` instead of `ALL`.

**Reply by skelder** [reply]
I had to reset the system due to other issues and now it is giving me slightly different error

`standard_init_linux.go:230: exec user process caused: no such file or directory`

the problem is this error comes up no matter what type of `cap_drop` I use and seems to be caused by my `entrypoint.sh` script.

**Reply by ainar-g** [reply]
At this point, I'm not sure how to help you, sorry.  Here's the command that works for me:

```sh
docker run\
        -v "$HOME/tmp/":/opt/adguardhome/conf\
        -i\
        -t\
        --cap-drop net_bind_service\
        --entrypoint sh\
        adguard/adguardhome:edge\
        -c 'setcap "cap_net_bind_service=-eip" /opt/adguardhome/AdGuardHome && /opt/adguardhome/AdGuardHome --no-check-update -c /opt/adguardhome/conf/AdGuardHome.yaml -h 0.0.0.0 -w /opt/adguardhome/work'
```

**Reply by skelder** [reply]
Thank you for your effort nonetheless.

I think I will give it another try once I have another linux system and see if that does anything.

**Comment by Jip-Hop** [comment]
Building a derivative image which runs `setcap "cap_net_bind_service=-eip" /opt/adguardhome/AdGuardHome` allowed me to run AdGuardHome with all capabilities dropped.

```Dockerfile
FROM adguard/adguardhome:v0.107.43
RUN setcap "cap_net_bind_service=-eip" /opt/adguardhome/AdGuardHome
```

```yaml
version: "3"

services:
  adguardhome:
    image: jip/adguard
    build: .
    container_name: adguardhome
    restart: unless-stopped
    # Ensure to change to default dns port 53 to 5353 inside conf/AdGuardHome.yaml
    ports:
      - 192.168.1.10:53:5353/tcp
      - 192.168.1.10:53:5353/udp
    # Ensure files inside /mnt/adguardhome are owned by 2000:2000
    volumes:
      - /mnt/adguardhome/work:/opt/adguardhome/work
      - /mnt/adguardhome/conf:/opt/adguardhome/conf
    user: 2000:2000
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs: /tmp:noexec
    networks:
      - traefik_proxy
      - adguardhome
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adguard.entrypoints=websecure"
      - "traefik.http.routers.adguard.rule=Host(`adguard.example.com`)"
      - "traefik.http.routers.adguard.tls=true"
      - "traefik.http.routers.adguard.service=adguard"
      - "traefik.http.services.adguard.loadbalancer.server.port=3000"
      - "traefik.docker.network=traefik_proxy"

networks:
  adguardhome:
    external: false
  traefik_proxy:
    external: true

```
