### DISCUSSION TITLE
config.users to accept reading hashed password from a file

### DISCUSSION THREAD

**Discussion by jdheyburn** [AdguardTeam/AdGuardHome#4661] [Ideas]
To increase security, it may be beneficial to allow the user password to be defined via a password file (containing the hashed value) in the config file:

```yaml
users:
  - name: admin
    passwordFile: /path/to/file
```

This would replace the existing `users[].password` field.
