### DISCUSSION TITLE
AdGuard behind Traefik | How to use DNS-over-HTTPS?

### DISCUSSION THREAD

**Discussion by der-domi** [AdguardTeam/AdGuardHome#5453] [Q&A]
Hi! I'm figuring same issues as #4656 - just with using Traefik as proxy.

Current status: DNS and DNS-over-TLS are working well.
Issue to be solved: How do I configure Traefik (and AdGuard), so that DNS-over-HTTPS does also work?

My `AdGuardHome.yaml` looks
```yaml
bind_host: 0.0.0.0
bind_port: 80
users:
  - name: [...]
auth_attempts: 5
block_auth_min: 15
http_proxy: ""
language: ""
theme: auto
debug_pprof: false
web_session_ttl: 720
dns:
  bind_hosts:
    - 0.0.0.0
  port: 53
  [...]
tls:
  enabled: true
  server_name: dns.example.com
  force_https: false
  port_https: 443
  port_dns_over_tls: 853
  port_dns_over_quic: 853
  port_dnscrypt: 0
  dnscrypt_config_file: ""
  allow_unencrypted_doh: true
  certificate_chain: ""
  private_key: ""
  certificate_path: /opt/adguardhome/ssl/dns.example.com.crt
  private_key_path: /opt/adguardhome/ssl/dns.example.com.key
  strict_sni_check: false
[...]
```
My `docker-compose.yml` looks
```yaml
version: '3.7'
services:
  adguard:
    image: adguard/adguardhome
    container_name: adguard
    restart: unless-stopped
    ports:
      - "53:53/tcp" #DNS
      - "53:53/udp" #DNS
      - "853:853/tcp" #DNS over TLS
    volumes:
      - "${DATA_DIRECTORY}/adguard/work:/opt/adguardhome/work:rw"
      - "${DATA_DIRECTORY}/adguard/conf:/opt/adguardhome/conf:rw"
      - "${DATA_DIRECTORY}/adguard/ssl:/opt/adguardhome/ssl:ro"
    labels:
      - "traefik.enable=true"
      # DNS-over-HTTPS
      - "traefik.http.routers.adguard-doh.rule=Host(`dns.example.com`)"
      - "traefik.http.routers.adguard-doh.entrypoints=websecure"
      - "traefik.http.routers.adguard-doh.tls=true"
      - "traefik.http.routers.adguard-doh.tls.certResolver=letsencrypt"
      - "traefik.http.routers.adguard-doh.middlewares=hsts@file"
      - "traefik.http.routers.adguard-doh.service=adguard-doh-svc"
      - "traefik.http.services.adguard-doh-svc.loadbalancer.server.port=443"
    networks:
      - reverse-proxy
networks:
  reverse-proxy:
    external: true
```
I've tried several things. E.g. adding following
```yaml
      - traefik.http.middlewares.https_redirect.redirectscheme.permanent=true
```
But all I get is `Client sent an HTTP request to an HTTPS server.` or `Internal Server Error` with following label
```yaml
      - "traefik.http.services.adguard-doh-svc.loadbalancer.server.scheme=https"
```

**Comment by der-domi** [comment]
With `docker logs traefik` I get following entry with each access.
```
2023/02/06 21:22:44 reverseproxy.go:505: httputil: ReverseProxy read error during body copy: read tcp 172.19.0.2:35550->172.19.0.4:443: read: connection reset by peer
```
Currently I'm not sure what the root cause can be.

On a test server I've only started Traefik and AdGuard and removed everything releated to IPv6 what I have added recently to my environment.

When I started Traefik the fist time I got following error.
```
Error response from daemon: AppArmor enabled on system but the docker-default profile could not be loaded: running `apparmor_parser apparmor_parser --version` failed with output:
error: exec: "apparmor_parser": executable file not found in $PATH
```
So I've installed `apt-get install apparmor`. But it is inactive. `systemctl status apparmor`:
```
● apparmor.service - Load AppArmor profiles
     Loaded: loaded (/lib/systemd/system/apparmor.service; disabled; vendor preset: enabled)
     Active: inactive (dead)
       Docs: man:apparmor(7)
             https://gitlab.com/apparmor/apparmor/wikis/home/
```

**Reply by der-domi** [reply]
BTW: I've already tried to get rid from the HTTP to HTTPS mapping by using port 80 for HTTPS

`AdGuardHome.yaml`:
```
tls:
  enabled: true
  server_name: dns.example.com
  force_https: false
  port_https: 80
  port_dns_over_tls: 853
  port_dns_over_quic: 853
  port_dnscrypt: 0
  dnscrypt_config_file: ""
  allow_unencrypted_doh: true
  certificate_chain: ""
  private_key: ""
  certificate_path: /opt/adguardhome/ssl/dns.example.com.crt
  private_key_path: /opt/adguardhome/ssl/dns.exampl.com.key
  strict_sni_check: false
```

`docker-compose.yml`:
```
      - "traefik.http.services.adguard-doh-svc.loadbalancer.server.port=80"
```

This results also in `Client sent an HTTP request to an HTTPS server.` with `docker logs traefik`
```
2023/02/08 12:13:23 reverseproxy.go:505: httputil: ReverseProxy read error during body copy: read tcp 172.18.0.7:43788->172.18.0.6:80: read: connection reset by peer
```

Question is: How are you using DNS-over-HTTPS using Traefik as a reverse-proxy?
