### DISCUSSION TITLE
Query log spammed with blank NS records

### DISCUSSION THREAD

**Discussion by eiqnepm** [AdguardTeam/AdGuardHome#5664] [Q&A]
Why does my query log have all these blank records? I have the AdGuard Home server IP set as my default DNS server on my router. My LAN using ports 192.168.1.1 to 192.168.1.255, I assume these requests are coming from a Docker network.

![](https://i.imgur.com/vZzwJ5K.png)

My Docker Compose file looks like this:

```yaml
version: "3"

networks:
  default:
    name: "adguardhome"

services:
  adguardhome:
    container_name: "adguardhome"
    dns:
      - "9.9.9.9"
      - "149.112.112.112"
    image: "adguard/adguardhome:latest"
    restart: "unless-stopped"
    ports:
      - "53:53"
      - "53:53/udp"
      - "3000:3000"
    volumes:
      - "./workdir:/opt/adguardhome/work"
      - "./confdir:/opt/adguardhome/conf"
```
