### DISCUSSION TITLE
Source: Unbound DNS - show client IP address

### DISCUSSION THREAD

**Discussion by vampywiz17** [AdguardTeam/AdGuardHome#6023] [Q&A] [answered]
Hello there,

My working line is:

Client --> Unbound DNS (opnsense) -->ADguard Home (installed a different server)

Unbound DNS are forward all DNS traffic to ADGuard home (Query Forwarding)

I set Unbund DNS this:

```
server:
  client-subnet-always-forward: yes
  send-client-subnet: 0.0.0.0/0
  send-client-subnet: ::0/0
```

My goal to see client IP adresses on ADGuard home, not only Opnsense IP.

what i doing wrong?
