### DISCUSSION TITLE
Unable to get DOH to work

### DISCUSSION THREAD

**Discussion by xd003** [AdguardTeam/AdGuardHome#6188] [Q&A] [answered]
I have deployed adguard home on linux docker using the following docker compose
```
  adguardhome:
    image: adguard/adguardhome 
    container_name: adguardhome
    restart: unless-stopped
    ports:
      - "53:53"
      - "853:853"
    expose:
      - "80"
      - "443"
      - "3000"
    volumes:
      - /home/ubuntu/docker/adguard/data:/opt/adguardhome/work
      - /home/ubuntu/docker/adguard/config:/opt/adguardhome/conf
  ```

I intend to have both DOT and DOH working. Accordingly, i have enabled encryption in settings, created persistent clients and added their ClientIDs to Allowed Client list. SSL certs and everything is perfect. 
I am using reverse proxy through nginx proxy manager to access the web interface. It is reverse proxying ```http://adguardhome:80``` to ```*.domain.subdomain.site``` & ```domain.subdomain.site```

DOT is working perfectly through the endpoint - ```clientid.domain.subdomain.site``` but i am unable to access DOH through ```https://clientid.domain.subdomain.site/dns-query```
