### DISCUSSION TITLE
How to Fix My AdGuardHome and Caddy Configuration?

### DISCUSSION THREAD

**Discussion by iSanae1** [AdguardTeam/AdGuardHome#6268] [Q&A]
I've installed AdGuardHome(v0.107.38) via Docker and done the initial configuration

<details>
<summary>Docker shell </summary>

```
 docker run --name AdGuardHome\
    --restart always\
    -v /home/AdGuardHome/work:/opt/adguardhome/work\
    -v /home/AdGuardHome/conf:/opt/adguardhome/conf\
    -p 127.0.0.1:3000:3000\
    -d adguard/adguardhome
```
</details>

<details>
<summary>AdGuardHome configuration (with sensitive content removed)</summary>

```
http:
  pprof:
    port: 6060
    enabled: false
  address: 0.0.0.0:3000
  session_ttl: 720h
auth_attempts: 5
block_auth_min: 15
http_proxy: ""
language: zh-cn
theme: auto
dns:
  bind_hosts:
    - 0.0.0.0
  port: 53
  anonymize_client_ip: true
  ratelimit: 0
  ratelimit_whitelist: []
  refuse_any: true
  upstream_dns:
    - https://dns.adguard-dns.com/dns-query
    - quic://dns.adguard-dns.com
    - https://unfiltered.adguard-dns.com/dns-query
    - quic://unfiltered.adguard-dns.com
    - https://mozilla.cloudflare-dns.com/dns-query
    - https://dns.cloudflare.com/dns-query
    - https://security.cloudflare-dns.com/dns-query
    - https://dns.mullvad.net/dns-query
    - https://adblock.dns.mullvad.net/dns-query
    - https://base.dns.mullvad.net/dns-query
  upstream_dns_file: ""
  bootstrap_dns:
    - 1.1.1.1
    - 1.0.0.1
    - 2606:4700:4700::1111
    - 2606:4700:4700::1001
    - 194.242.2.2
    - 2a07:e340::2
  fallback_dns: []
  all_servers: true
  fastest_addr: false
  fastest_timeout: 1s
  allowed_clients: []
  disallowed_clients: []
  blocked_hosts:
    - version.bind
    - id.server
    - hostname.bind
  trusted_proxies:
    - 0.0.0.0/0
  cache_size: 4194304
  cache_ttl_min: 0
  cache_ttl_max: 0
  cache_optimistic: false
  bogus_nxdomain: []
  aaaa_disabled: false
  enable_dnssec: true
  edns_client_subnet:
    custom_ip: ""
    enabled: false
    use_custom: false
  max_goroutines: 300
  handle_ddr: true
  ipset: []
  ipset_file: ""
  bootstrap_prefer_ipv6: false
  upstream_timeout: 10s
  private_networks: []
  use_private_ptr_resolvers: true
  local_ptr_upstreams: []
  use_dns64: false
  dns64_prefixes: []
  serve_http3: false
  use_http3_upstreams: false
tls:
  enabled: false
  server_name: dev.mydomain.moe
  force_https: false
  port_https: 0
  port_dns_over_tls: 0
  port_dns_over_quic: 0
  port_dnscrypt: 0
  dnscrypt_config_file: ""
  allow_unencrypted_doh: true
  certificate_chain: ""
  private_key: ""
  certificate_path: ""
  private_key_path: ""
  strict_sni_check: false
querylog:
  ignored: []
  interval: 12h
  size_memory: 1000
  enabled: true
  file_enabled: true
statistics:
  ignored: []
  interval: 24h
  enabled: true
filters:
  - enabled: false
    url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_1.txt
    name: AdGuard DNS filter
    id: 1
  - enabled: false
    url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_2.txt
    name: AdAway Default Blocklist
    id: 2
  - enabled: true
    url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_21.txt
    name: 'CHN: anti-AD'
    id: 1696181727
  - enabled: true
    url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_29.txt
    name: 'CHN: AdRules DNS List'
    id: 1696181728
whitelist_filters: []
user_rules: []
dhcp:
  enabled: false
  interface_name: ""
  local_domain_name: lan
  dhcpv4:
    gateway_ip: ""
    subnet_mask: ""
    range_start: ""
    range_end: ""
    lease_duration: 86400
    icmp_timeout_msec: 1000
    options: []
  dhcpv6:
    range_start: ""
    lease_duration: 86400
    ra_slaac_only: false
    ra_allow_slaac: false
filtering:
  blocking_ipv4: ""
  blocking_ipv6: ""
  blocked_services:
    schedule:
      time_zone: UTC
    ids: []
  protection_disabled_until: null
  safe_search:
    enabled: false
    bing: true
    duckduckgo: true
    google: true
    pixabay: true
    yandex: true
    youtube: true
  blocking_mode: default
  parental_block_host: family-block.dns.adguard.com
  safebrowsing_block_host: standard-block.dns.adguard.com
  rewrites: []
  safebrowsing_cache_size: 1048576
  safesearch_cache_size: 1048576
  parental_cache_size: 1048576
  cache_time: 30
  filters_update_interval: 12
  blocked_response_ttl: 10
  filtering_enabled: true
  parental_enabled: false
  safebrowsing_enabled: true
  protection_enabled: true
clients:
  runtime_sources:
    whois: true
    arp: true
    rdns: true
    dhcp: true
    hosts: true
  persistent: []
log:
  file: ""
  max_backups: 0
  max_size: 100
  max_age: 3
  compress: false
  local_time: false
  verbose: false
os:
  group: ""
  user: ""
  rlimit_nofile: 0
schema_version: 27
```
</details>

For some reason, I'm using a sub-path to reverse proxy AdGuardHome through Caddy behind Cloudflare, and the relevant part of the configuration is as follows

<details>

<summary>Caddy Config</summary>

```
servers {
                trusted_proxies static 103.21.244.0/22 103.22.200.0/22 103.31.4.0/22 104.16.0.0/13 104.24.0.0/14 108.162.192.0/18 131.0.72.0/22 141.101.64.0/18 162.158.0.0/15 172.64.0.0/13 173.245.48.0/20 188.114.96.0/20 190.93.240.0/20 197.234.240.0/22 198.41.128.0/17 2400:cb00::/32 2606:4700::/32 2803:f800::/32 2405:b500::/32 2405:8100::/32 2a06:98c0::/29 2c0f:f248::/32
        }
}
dev.mydomain.moe {
        route /adguardhome/* {
                uri strip_prefix /adguardhome
                reverse_proxy localhost:3000 {
                        header_down Location /*.html /adguardhome/*.html
                }
        }
```

</details>

According to my configuration, I can access the UI page of AdGuardHome via the /adguardhome path.
![图片](https://github.com/AdguardTeam/AdGuardHome/assets/126803844/c59207eb-101f-4453-a388-6c9e8902d5a2)
I want to change the request path for dns-query to /adguardhome/dns-query, but my configuration only returns Bad Request via cURL. So it doesn't work at all, I can't set this URL as my DNS-over-HTTPS Server.
![图片](https://github.com/AdguardTeam/AdGuardHome/assets/126803844/6fd61672-9cbb-4d6a-8603-ddfcddf4a3b9)

I think it's a problem with my Caddy or AdGuardHome configuration, but I haven't found a solution through the Wiki or other discussions, I hope the AdGuard community can help me, thank you for your reply!
