### DISCUSSION TITLE
Cannot connect to adguard

### DISCUSSION THREAD

**Discussion by AustinZhang1024** [AdguardTeam/AdGuardHome#6396] [Q&A]
I installed adguardhome on my fedora iot device with podman. I turned off the firewall and the selinux. But I still cannot connect to the adguardhome by using adguard on my PC, android and another adguardhome on my router.

```yaml
adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    ports:
      - 3333:3333
      - 8530:8530/tcp
      - 8530:8530/udp
    volumes:
      - /home/odin/usb/adguardhome/work:/opt/adguardhome/work
      - /home/odin/usb/adguardhome/conf:/opt/adguardhome/conf
```

```yaml
dns:
  bind_hosts:
    - 0.0.0.0
  port: 8530
```
