### DISCUSSION TITLE
Unable to run on docker compose

### DISCUSSION THREAD

**Discussion by gaurishhs** [AdguardTeam/AdGuardHome#6475] [Q&A]
Hi! I'm trying to run AGH via docker compose. 

```yml
version: '3.8'
services:
  adguardhome:
    container_name: adguardhome
    image: adguard/adguardhome
    restart: unless-stopped
    networks:
      dockervlan:
        ipv4_address: 192.168.1.225
    ports:
      - 53:53/udp
      - 67:67/udp
      - 68:68/tcp
      - 68:68/udp
      - 80:80/tcp
      - 443:443/tcp
      - 853:853/tcp
      - 3000:3000/tcp
    volumes:
      - ./adguard/work:/opt/adguardhome/work
      - ./adguard/conf:/opt/adguardhome/conf
      - ./adguard/certs:/certs

networks:
  dockervlan:
    name: dockervlan
    driver: macvlan
    driver_opts:
      parent: wlan0
    ipam:
      config:
        - subnet: "192.168.1.0/24"
          ip_range: "192.168.1.225/32"
          gateway: "192.168.1.1"
  default:
    driver: bridge
```

whenever i visit the web ui the connection always times out. As per the logs AGH runs

```
adguardhome         | 2023/11/28 18:48:11.891791 [info] AdGuard Home, version v0.107.41
adguardhome         | 2023/11/28 18:48:11.891867 [info] This is the first time AdGuard Home is launched
adguardhome         | 2023/11/28 18:48:11.891874 [info] Checking if AdGuard Home has necessary permissions
adguardhome         | 2023/11/28 18:48:11.892088 [info] AdGuard Home can bind to port 53
adguardhome         | 2023/11/28 18:48:11.893588 [info] safesearch default: disabled
adguardhome         | 2023/11/28 18:48:11.894088 [info] Initializing auth module: /opt/adguardhome/work/data/sessions.db
adguardhome         | 2023/11/28 18:48:11.894161 [info] auth: initialized.  users:0  sessions:0
adguardhome         | 2023/11/28 18:48:11.894171 [info] AdGuard Home updates are disabled
adguardhome         | 2023/11/28 18:48:11.894176 [info] web: initializing
adguardhome         | 2023/11/28 18:48:11.894184 [info] This is the first launch of AdGuard Home, redirecting everything to /install.html 
adguardhome         | 2023/11/28 18:48:11.894195 [info] AdGuard Home is available at the following addresses:
adguardhome         | 2023/11/28 18:48:11.894626 [info] go to http://127.0.0.1:3000
adguardhome         | 2023/11/28 18:48:11.894635 [info] go to http://192.168.1.225:3000
```

The raspberry pi does have a static ip.
