### DISCUSSION TITLE
nginx reverse proxy

### DISCUSSION THREAD

**Discussion by kajvans** [AdguardTeam/AdGuardHome#6559] [Q&A]
hi everyone i am trying to run it using docker but on some different ports because i already have some other services.
port 80 443 and 3000 are already in use. but whatever i try it wont work. anyone some experience with running it using reverse proxy and on other ports

**Comment by dhaneshsabane** [comment]
I have been trying the same setup -> AdGuard as Docker container with Nginx running on host as the reverse proxy. Frustratingly, I have been unable to get DoH working. My configurations is as follows:

Ports exposed:
* `24480:80`
* `24453:53`

AdGuardHome.yaml

```yaml
tls:
  enabled: true
  server_name: domain.tld
  force_https: false
  port_https: 0
  port_dns_over_tls: 853
  port_dns_over_quic: 853
  port_dnscrypt: 0
  dnscrypt_config_file: ""
  allow_unencrypted_doh: true
  certificate_chain: ""
  private_key: ""
  certificate_path: ""
  private_key_path: ""
  strict_sni_check: false

# And trusted_proxies is
trusted_proxies:
    - 127.0.0.0/8
    - ::1/128
    - 172.17.0.0/32
```

Nginx

```
server {
	listen 443 ssl http2;
	ssl_certificate /etc/letsencrypt/live/domain.tld/fullchain.pem; # managed by Certbot
	ssl_certificate_key /etc/letsencrypt/live/domain.tld/privkey.pem; # managed by Certbot

	location /dns-query {
		proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        	proxy_set_header X-Forwarded-Proto $scheme;
		proxy_set_header Host $host;
	    	proxy_set_header X-Real-IP '1.2.3.4';
	    	proxy_bind 127.0.0.1;
	    	proxy_pass http://0.0.0.0:24480/dns-query;
	    	proxy_http_version 1.1;
	    	proxy_set_header Connection "";
	}
}
```

With the above setup, I'm trying a DNS query for `linkedin.com` using curl as follows:

`curl -v --doh-url https://domain.tld/dns-query linkedin.com`

Which returns "Couldn't resolve host name"

```bash
* DoH: Bad ID type A for linkedin.com
* DoH: Bad ID type AAAA for linkedin.com
* Closing connection
curl: (6) Couldn't resolve host name
```
