### DISCUSSION TITLE
Can't start AdguardHome on Keepalived backup server

### DISCUSSION THREAD

**Discussion by mattheys** [AdguardTeam/AdGuardHome#6886] [Q&A]
I'm not sure how to configure this, Adguard is complaining that it can't bind to the VIP of my Keepalived cluster unless it's acting as the master.

`2024/04/04 10:58:30.064789 [fatal] couldn't start forwarding DNS server: starting listeners: listening on udp addr 192.168.1.100:53: listening to udp socket: listen udp 192.168.1.100:53: bind: cannot assign requested address`

I'm running AdguardHome in docker with network_mode = host. On the primary I'm using.
```
dns:
  bind_hosts:
    - 192.168.1.2
    - 192.168.1.100
```

And on the backup I'm using.
```
dns:
  bind_hosts:
    - 192.168.1.7
    - 192.168.1.100
```

But Adguard will only start on a machine if it's running as the Master VRRP as it has the VIP

I've tried setting it to bind to 0.0.0.0 but because I'm also using the primary as a DHCP server I think this screwed up the advertised DNS server.
```
dhcp:
  enabled: true
  interface_name: eth0
  local_domain_name: lan
  dhcpv4:
    gateway_ip: 192.168.1.1
    subnet_mask: 255.255.255.0
    range_start: 192.168.1.128
    range_end: 192.168.1.254
    lease_duration: 1200
    icmp_timeout_msec: 1000
    options: []
```

Any ideas?

**Comment by seanpdiaz** [comment]
I too have the same issue, cant start any of the BACKUP instances of adguard because the floating IP address doesn't exist on anywhere but the MASTER node. Hopefully someone can answer this or point in a direction of answers.

**Comment by mattheys** [comment]
I just bound to 0.0.0.0 in the end seems to work fine when failing over.

Edit: Sorry I realised I mentioned about the DHCP advertising being screwed up not knowing the correct IP to advertise, I fixed that by specifying option 6 to be my VIP on the VRRP.

``` yaml
dhcp:
  enabled: true
  interface_name: eth0
  local_domain_name: lan
  dhcpv4:
    gateway_ip: 192.168.1.1
    subnet_mask: 255.255.255.0
    range_start: 192.168.1.128
    range_end: 192.168.1.254
    lease_duration: 1200
    icmp_timeout_msec: 1000
    options:
      - 6 ips 192.168.1.100
```
