### DISCUSSION TITLE
Http Bad request for doh uri

### DISCUSSION THREAD

**Discussion by st3l1n** [AdguardTeam/AdGuardHome#6910] [Q&A]
I had an instance of AdGuardHome behind nginx proxy. Everything worked as expected until I decided to pull new AdGuardHome docker image. After pulling the latest image I restarted docker compose. At this point I lost my current configuration (my bad) and started to configuring fresh installation of AdguardHome.

This time everything worked fine until I started to set up encryption settings. In my configuration, nginx rules https for web, but AdGuardHome rules DoH with exact certificate as nginx, and doh requests proxied through nginx. When I tried to reach /dns-query I got the the message 
```  
HTTP/1.1 400 Bad Request
wget: server returned error: HTTP/1.1 400 Bad Request
```
At the time I thought that It was a mistake with nginx configuration. After some efforts I just turned off the nginx to check "bare" installation. And there I got the same result `HTTP/1.1 400 Bad Request`. I tried browser, curl, wget - same result. Here my latest docker config with error.

```
services:
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    ports:
      - "53:53/udp"
      - "3000:3000/tcp"
      - "80:80/tcp"
      - "443:443/tcp"
    volumes:
      - ./certs:/opt/adguardhome/certs
    dns:
      - 127.0.0.1
    restart: always
    networks:
      network:
        ipv4_address: 10.5.0.5
```

Here my encryption settings

<img width="1254" alt="image" src="https://github.com/AdguardTeam/AdGuardHome/assets/57614065/f3fc4b22-a96e-447b-aebc-510af92465a7">

<img width="349" alt="Screenshot 2024-04-11 at 22 47 04" src="https://github.com/AdguardTeam/AdGuardHome/assets/57614065/fb8a9ea2-d838-43c7-858c-935afda9106d">

Any clues?
