### DISCUSSION TITLE
No internet connection after pointing router to AdGuardHome

### DISCUSSION THREAD

**Discussion by harrismck** [AdguardTeam/AdGuardHome#6911] [Q&A] [answered]
### Prerequisites
* [x]  I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer
 
* [x]  I have searched other issues and found no duplicates
 
* [x]  I have set up AdGuard Home correctly and configured clients to use it
 
### Platform (OS and CPU architecture)
Ubuntu Server 22.04.3, x86_64

### Installation
Docker compose

### Issue
After installing AdguardHome via docker compose, and pointing my router to use it as the DNS server, I have no DNS access at all. I can still ping ips between my machines, but that's it. The query logs in the AdguardHome admin panel are also completely blank. I tried setting this up the other day and at least there was queries in the logs (but still a broken connection).

The relevant snippet of my docker compose:
```
  adguardhome:
    container_name: adguardhome
    image: adguard/adguardhome
    volumes:
      - ./config/adguardhome/work:/opt/adguardhome/work
      - ./config/adguardhome/conf:/opt/adguardhome/conf
    ports:
      - "53:53/tcp" # DNS
      - "192.168.1.111:53:53/udp" # DNS (needs the full IP or docker containers can't reach each other??)
      - "67:67/udp" # DHCP
      - "68:68/udp" # DHCP
      - "68:68/tcp" # DHCP
      #- "80:80/tcp" # These are for using adguardhome as an HTTPS/DNS-over-HTTPS, but NPM uses these ports too...
      #- "443:443/tcp"
      #- "443:443/udp"
      - "3434:3000/tcp" # Initial config port: 3434 (default is 3000 but homepage is using that)
      - "853:853/tcp"
      - "784:784/udp"
      - "853:853/udp"
      - "8853:8853/udp"
      - "5443:5443/tcp"
      - "5443:5443/udp"
      - "9999:9999" # Web UI port set in initial config
    restart: unless-stopped
```

Router settings:
![image](https://github.com/AdguardTeam/AdGuardHome/assets/11249652/4ebf8ac5-60dd-4aa0-9547-994733c05198)

AdGuardHome panel:
![image](https://github.com/AdguardTeam/AdGuardHome/assets/11249652/90d6a787-3d8d-4370-8dab-c76cb595eef8)
