### DISCUSSION TITLE
Fatal error during initalize

### DISCUSSION THREAD

**Discussion by AnonymousX86** [AdguardTeam/AdGuardHome#7012] [Q&A] [answered]
I'm trying to deploy AdGuard Home via Portainer, but I'm simply getting error and initalizing goes back to step 2.
![Screenshot 2024-05-21 at 19-12-45 Setup AdGuard Home](https://github.com/AdguardTeam/AdGuardHome/assets/53279236/47d7f274-3261-4df5-9938-b49e7621264b)

Full error text:

```plaintext
Error: control/install/configure | dnsServer.Prepare: preparing internal proxy: validating private RDNS upstreams: no upstream specified | 500
```

I'm attaching my Stack configuration:
```yaml
services:
  app:
    container_name: adguard-home
    image: adguard/adguardhome:latest
    restart: unless-stopped
    volumes:
      - adguard-home:/opt/adguardhome/work
      # - adguard-home:/opt/adguardhome/conf
      - /etc/adguard-home:/opt/adguardhome/conf
    environment:
      TZ: Europe/Warsaw
    ports:
      - 0.0.0.0:553:53/udp
      - 0.0.0.0:8004:3000/tcp
    networks:
      - lab-web
      - lab-dns
  dns:
    container_name: unbound
    image: mvance/unbound:latest
    restart: unless-stopped
    ports:
      - 0.0.0.0:1053:53/udp
    volumes:
      - unbound:/opt/unbound/etc/unbound
      # - /etc/unbound/forward-records.conf:/opt/unbound/etc/unbound/forward-records.conf:ro
      # - /etc/unbound/a-records.conf:/opt/unbound/etc/unbound/a-records.conf:ro
      # - /etc/unbound/unbound.conf:/opt/unbound/etc/unbound/unbound.conf:ro
      # - /etc/unbound/unbound.log:/opt/unbound/etc/unbound/unbound.log
      # - /var/log/unbound.log:/opt/unbound/etc/unbound/unbound.log
    environment:
      TZ: Europe/Warsaw
    networks:
      - lab-dns
    # group_add:
      # - adm

networks:
  lab-web:
    external: true
  lab-dns:
    external: true

volumes:
  adguard-home:
    external: true
  unbound:
    external: true
```
Commented lines are my other tries, but every combination causes same error.

Same configuration works fine without Portainer. I was hosting before on same machine, but simply using `~/docker/adguard-home/compose.yml` and it worked like a charm, but I just wanted to try Portainer (new tech to learn).
Have anyone else had simillar issue?
