### DISCUSSION TITLE
Unable to Enable DHCP Server in AdGuard Home on Ubuntu Server 24.04

### DISCUSSION THREAD

**Discussion by v-grabko1999** [AdguardTeam/AdGuardHome#7361] [Q&A]
Problem: I am unable to enable the DHCP server in AdGuard Home on Ubuntu Server 24.04. Despite having the internet connection correctly configured in the system and setting a static IP address for the Wi-Fi interface (wlp2s0), AdGuard Home displays an error message indicating the need for a static IP.

Network Interfaces:
```
Ethernet: enp0s31f6 (connected to the internet, obtains an IP address via DHCP).
Wi-Fi: wlp2s0 (configured as an access point with a static IP address of 192.168.50.1/24).
```

NAT Configuration with iptables:

```
sudo iptables -t nat -A POSTROUTING -o enp0s31f6 -j MASQUERADE
sudo iptables -A FORWARD -i enp0s31f6 -o wlp2s0 -m state --state RELATED,ESTABLISHED -j ACCEPT
sudo iptables -A FORWARD -i wlp2s0 -o enp0s31f6 -j ACCEPT

```

Netplan Configuration:

```
yaml
network:
  version: 2
  renderer: networkd
  ethernets:
    enp0s31f6:
      dhcp4: yes
  wifis:
    wlp2s0:
      dhcp4: no
      addresses: [192.168.50.1/24]

```

After configuring a static IP address for the wlp2s0 interface in AdGuard Home’s web interface and attempting to enable the DHCP server, the system displays a message

`In order to use DHCP server a static IP address must be set. AdGuard Home failed to determine if this network interface is configured using a static IP address. Please set a static IP address manually.`

**Additional Information**
Translation from Russian to English was done with the help of ChatGPT, as I am not a native speaker.
![image](https://github.com/user-attachments/assets/850b8c7a-0155-436c-b2f0-e0191f10fa1d)
