### DISCUSSION TITLE
Deactivating protection does not work

### DISCUSSION THREAD

**Discussion by DeltaTango69** [AdguardTeam/AdGuardHome#7408] [Q&A]
When I switch the button "deactivate protection" I would assume to disable the protection. But this don't work for me. I have installed adguard home via docker:

```
services:
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    hostname: adguard
    network_mode: host   # überhaupt kein Zugriff wenn aktiv!
    restart: unless-stopped
    ports:
      - "53:53/tcp" # unverschlüsseltes DNS
      - "53:53/udp" # unverschlüsseltes DNS
      - "67:67/udp" # DHCP
      - "68:68/udp" # DHCP
      - "80:80/tcp" # Admin-Webobefläche & DNS over HTTPS
      - "443:443/tcp" # Admin-Webobefläche & DNS over HTTPS
      - "443:443/udp" # Admin-Webobefläche & DNS over HTTPS
      - "3000:3000/tcp" # Ersteinrichtung
      - "853:853/tcp" # DNS over TLS
      - "853:853/udp" # DNS over Quic
      - "784:784/udp" # DNS over Quic
      - "8853:8853/udp" # DNS over Quic
      - "5443:5443/tcp" # DNSCrypt
      - "5443:5443/udp" # DNSCrypt
    volumes:
      - "./work:/opt/adguardhome/work"
      - "./config:/opt/adguardhome/conf"
      - "/etc/localtime:/etc/localtime:ro"

```
What could be wrong?
