### DISCUSSION TITLE
ADH compose file with unbound container?

### DISCUSSION THREAD

**Discussion by BoBBer446** [AdguardTeam/AdGuardHome#7442] [Q&A]
Has anyone a Solution to run unbound and adh on same compose file together ?

**Comment by BoBBer446** [comment]
I was trying this without success:

```bash
mkdir -p ~/dns-setup/{unbound,adguard/workdir,adguard/confdir}
cd ~/dns-setup
```

`nano unbound/unbound.conf`

```yml
server:
  verbosity: 1
  interface: 0.0.0.0
  port: 53
  do-ip4: yes
  do-ip6: yes
  prefetch: yes
  qname-minimisation: yes
  hide-identity: yes
  hide-version: yes
  harden-glue: yes
  harden-dnssec-stripped: yes
  use-cachedb: no 
forward-zone:
  name: "."
  forward-tls-upstream: yes
  forward-addr: 9.9.9.9@853#dns.quad9.net
  forward-addr: 149.112.112.112@853#dns.quad9.net
  forward-addr: 2620:fe::fe@853#dns.quad9.net
  forward-addr: 2620:fe::9@853#dns.quad9.net
```

```yml
services:
  unbound:
    image: mvance/unbound:latest
    container_name: unbound
    restart: unless-stopped
    volumes:
      - ./unbound:/opt/unbound/etc/unbound
    networks:
      dns:
        ipv4_address: 172.28.0.2

  adguardhome:
    image: adguard/adguardhome:latest
    container_name: adguardhome
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80"
      - "443:443"
      - "3000:3000"
    volumes:
      - ./adguard/workdir:/opt/adguardhome/work
      - ./adguard/confdir:/opt/adguardhome/conf
    networks:
      dns:
        ipv4_address: 172.28.0.3
    depends_on:
      - unbound

networks:
  dns:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
```

upstream dns: 172.28.0.2
adh dns chache: 0
