### DISCUSSION TITLE
Reverse lookup for client hostnames does not work with Fritz!Box

### DISCUSSION THREAD

**Discussion by OddMagnet** [AdguardTeam/AdGuardHome#7447] [Q&A] [answered]
It seems this topic is one that appears again and again and so far I wasn't able to find a solution to this, even though there's lots of threads all over the internet...

I have the following setup:

My router is a Fritz!Box, with DNS servers set to the ip's of my two AdGuardHome instances (.199 and .200)
Under `Network` -> `Network Settings` -> `DNS Rebind Protection` (not 100% sure about the english names) I've added the domains I use for my servers.
```
cloud
pi
```
 
Both AGH instances run via docker, and their settings are synced via adguardhome-sync, this is their yml:
```
services:
  adguardhome:
    container_name: adguardhome
    image: adguard/adguardhome:latest
    restart: always
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "443:443/tcp"
      - "853:853/tcp"
      - "784:784/udp"
      - "3300:3000/tcp"
      - "3380:80/tcp"
    volumes:
      - ./adguard/work:/opt/adguardhome/work
      - ./adguard/conf:/opt/adguardhome/conf
    network_mode: host
    cap_add:
      - NET_ADMIN
```

In AGH, under `Settings` -> `DNS Settings`, I have the following settings:
**Upstream DNS Servers**
```
https://dns10.quad9.net/dns-query
[/in-addr.arpa/]192.168.178.1
[/ip6.arpa/]192.168.178.1
[/fritz.box/]192.168.178.1
```

**Private Reverse DNS Servers**
```
192.168.178.1
```

`Use private reverse DNS Resolvers` and `Enable reverse resolving of clients' IP addresses` are both enabled

---

The weirdest part is that a `nslookup` from inside the containers works...
```shell
michael@DietPi:~/.config/docker$ docker exec -it adguardhome sh
/opt/adguardhome/work # nslookup 192.168.178.80
Server:		192.168.178.1
Address:	192.168.178.1:53

80.178.168.192.in-addr.arpa	name = michaels-macbook.fritz.box
```

**Comment by CamelT0E** [comment, marked as answer]
1. You do not have to enter ports in the compose if you use the network mode "host"!
```
services:
  adguardhome:
    container_name: adguardhome
    image: adguard/adguardhome:latest
    restart: always
    volumes:
      - ./adguard/work:/opt/adguardhome/work
      - ./adguard/conf:/opt/adguardhome/conf
    network_mode: host
```
2. i use the following entries in Upstream-DNS-Server:
```
# Fritz!Box
[/178.168.192.in-addr.arpa/]192.168.178.1
[/fritz.box/]192.168.178.1
```
i think this will help you :)

**Comment by OddMagnet** [comment]
Hey, thanks for the reply.

Completely forgot about removing the ports after changing to host mode :D

Somehow I came to the same solution, but completely forgot to reply here, since it's been so long.

There are still some clients showing with just IP (and the docker containers from my server), but that's something I'll just live with

**Comment by CamelT0E** [comment]
For me, all clients are displayed by name. This name was used in the Fritz! Box or come from the client. But I only use IPv4, IPv6 is deactivated for me. In the settings under Clients, you can also set or define the man in AdGuard Home. You can use the IP or Mac addresses as identifiers. 

This also works for Docker. However, you should assign a fixed IP to each container. For me, the display as a docker is enough. I don't need to have every single container listed:

![grafik](https://github.com/user-attachments/assets/791b22d3-6916-4ec0-bbdd-cb4172989e89)

**Reply by OddMagnet** [reply]
Thanks for the suggestion. Upon trying to change that I noticed that my Homeserver hasn't gotten requests from my containers in a long time. 
Totally forgot that I set my Homeserver to use my RaspberryPi AdGuardHome for DNS and there, of course, all the requests show up as coming from `Homeserver` (so that was already solved, lol)

**Comment by CamelT0E** [comment]
I still have a little optimization:
```
services:
  adguardhome:
    container_name: adguardhome
    image: adguard/adguardhome:latest
    restart: always
    volumes:
      - ./work:/opt/adguardhome/work
      - ./conf:/opt/adguardhome/conf
    network_mode: host
```
![grafik](https://github.com/user-attachments/assets/8a26b737-c230-435d-a19b-d21984870929)
You do not need an adguardhome subfolder in the adguardhome folder and the configs and files in it.
So you always have a hierarchy more, which worsens the clarity.
