### DISCUSSION TITLE
DoH not working for IPv6

### DISCUSSION THREAD

**Discussion by Qhilm** [AdguardTeam/AdGuardHome#7491] [Q&A]
Neither is the web admin interface over IPv6.

DoH, DoT, plan DNS, all of this works fine over IPv6.

It's running on opnsense, I can see that the AdGuardHome process is not listening to [my:ip;v6]:443. It only listens to port 443 on IPv4. (I checked using `sockstat -l | grep AdG`)

My yaml looks like this (I have simplified):

```yaml
http:
  pprof:
    port: 6060
    enabled: false
  address: 192.168.1.1:3000
serve_http3: true
http_proxy: ""
dns:
  bind_hosts:
    - 192.168.1.1
    - 127.0.0.1
    - ::1
    - fd00:1::1
  port: 53
tls:
  enabled: true
  server_name: ag.home.domain.com
  force_https: true
  port_https: 443
  port_dns_over_tls: 853
  port_dns_over_quic: 853
  port_dnscrypt: 0
  dnscrypt_config_file: ""
  allow_unencrypted_doh: false
  certificate_chain: ""
  private_key: ""
  certificate_path: /var/etc/acme-client/certs/1234567890/fullchain.pem
  private_key_path: /var/etc/acme-client/keys/1234567890/private.key
  strict_sni_check: false
```
