### DISCUSSION TITLE
Changing the order or blocklists?

### DISCUSSION THREAD

**Discussion by HachimanSec** [AdguardTeam/AdGuardHome#7594] [Q&A] [answered]
Hi everyone, 
I was wondering if one can change the order of the blocklists? 

The thing is I want to have certain blocklists, like abuse.ch, with more specific results before more generic, large ones like HaGeZi. 

As we are feeding the log into our SIEM I want to first hit the more specific abuse.ch to send out an alert. 

So far almost everything hits HaGeZi but never the abuse.co blocklist. 

Any idea how this can be achieved?
Thx!

**Comment by Dynamic5912** [comment]
All the blocklists are checked. I don't think the order in which they are checked can be modified.

**Reply by HachimanSec** [reply]
Thx. Too bad it looks like it.

**Reply by ppfeufer** [reply]
Remove them, and re-add them in the order you want to have them.

**Reply by HachimanSec** [reply]
That is what I thought too @ppfeufer 
Unfortunately it seems like it still doesnt work. 

This is the order of the blocklists (snippet): 
```
filters:
  - enabled: true
    url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_1.txt
    name: AdGuard DNS filter
    id: 1
  - enabled: true
    url: https://urlhaus.abuse.ch/downloads/rpz/
    name: URLhaus abuse.ch
    id: 1710998425
  - enabled: true
    url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_12.txt
    name: Dandelion Sprout's Anti-Malware List
    id: 1710998426
  - enabled: true
    url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_44.txt
    name: HaGeZi's Threat Intelligence Feeds
    id: 1710998427
```

abuse.ch is listed before HaGeZi. 

Looking at the abuse.ch list: https://urlhaus.abuse.ch/downloads/rpz/

I choose this for testing: fransize-veryf[.]com

Looking at the log (see screenshot) the hostname is blocked by HaGeZi instead of abuse.ch - even though abuse.ch is the first list I had added and it has the lowest list id in the conf. 
<img width="1232" alt="Screenshot 2025-01-25 at 11 57 53" src="https://github.com/user-attachments/assets/f8b555a6-4e5b-4573-a053-cc033374ca1d" />
