### DISCUSSION TITLE
Use env variable in config file

### DISCUSSION THREAD

**Discussion by Cilenco** [AdguardTeam/AdGuardHome#7649] [Q&A]
I'm able to start my Docker container with following config:

```
dns:
  port: 5300

filtering:
  rewrites:
    - domain: domain.tld
      answer: xxx.xxx.xxx.xxx
```

I would like to set the `domain.tld` from an env variable. Is templating or so possible within the config file?
