### DISCUSSION TITLE
Port 853 closed

### DISCUSSION THREAD

**Discussion by xgusto** [AdguardTeam/AdGuardHome#7670] [General]
I recently installed docker adguard home. It works fine on LAN. I want to use adguard home outside LAN (I use VPN tunel WG) on Android 14.
In Android 14, I can only use private DNS and it doesn't work with IP address but with FQDN, which expects DOH or DOT.
I tried turning on encryption in adguard home settings. On another machine I generated cert.pem and key.pem, but adguard reports that
Certificate chain is invalid
When I try which ports are open, the output is
```
PORT STATE SERVICE
22/tcp open ssh
53/tcp open domain
80/tcp open http
3000/tcp open ppp
8000/tcp open http-alt
8080/tcp open http-proxy
```
Port 853 is missing
On the local DNS server I use host overrides for the IP address of the server where adguard is installed, so in Android I can use the domain name.
By the way, docker runs in unprivileged LXC.
compose

```
version: "3"
services:
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 784:784/udp
      - 853:853/tcp
      - 3000:3000/tcp
    volumes:
      - ./workdir:/opt/adguardhome/work
      - ./confdir:/opt/adguardhome/conf
    restart: unless-stopped

```
![adgh](https://github.com/user-attachments/assets/7a4e79c1-d20e-4f86-998c-9eded5267bec)
