### DISCUSSION TITLE
How to edit AdGuardHome.yaml and persist changes?

### DISCUSSION THREAD

**Discussion by peracchi** [AdguardTeam/AdGuardHome#7700] [Q&A]
I want to edit `/opt/AdGuardHome/AdGuardHome.yaml` to include some static hosts but as soon I start AdGuard Home the changes to the file are lost.

Tried to add:
```
dns:
  hosts:
    router.home.arpa: 10.111.111.10
```

and also tried to add

```
hosts:
  - ip: 10.111.111.10
    hostnames:
      - router
      - router.home.arpa
```

   No matter what, I always lost the editions to the file.
