### DISCUSSION TITLE
iVentoy DHCP support.

### DISCUSSION THREAD

**Discussion by JMarcosHP** [AdguardTeam/AdGuardHome#7706] [Q&A]
Hi, I'm having trouble to configure Adguard's dhcp for iventoy network boot.

This is my current config:

```
dhcp:
  enabled: true
  interface_name: enp3s0
  local_domain_name: lan
  dhcpv4:
    gateway_ip: 192.168.1.254
    subnet_mask: 255.255.255.0
    range_start: 192.168.1.64
    range_end: 192.168.1.253
    lease_duration: 86400
    icmp_timeout_msec: 0
    options:
      - 66 text 192.168.1.100
      - 67 text iventoy_loader_16000
  dhcpv6:
    range_start: ""
    lease_duration: 86400
    ra_slaac_only: false
    ra_allow_slaac: false
```

As the iventoy's documentation says:

```
2.1 External Mode
The usage scenario of External mode is that iVentoy and the third-party DHCP Server are located in the same LAN/VLAN.
In this mode, iVentoy will still start its internal DHCP server, but the internal DHCP server will only snoop the DHCP packet and will not send any response. So it will not interfere with the work of the external DHCP Server.
By snooping the DHCP packet, iVentoy will record the client's BIOS mode, when the client request bootfile through TFTP, iVentoy will send it the right bootfile.
So in this mode, the DHCP server does not need to care about the client's BIOS mode. It only provides a common bootfile name (for example iventoy_loader_16000)
The bootfile name is actually a virtual file name. iVentoy will provide the real bootfile to the client according to its BIOS mode.
```

iVentoy is set to external mode, but when I try to network boot from a PC I get a null IP when ipxe tries to load the respective menu from the http link:

![IMG_20250319_152117_1.jpg](https://github.com/user-attachments/assets/16e155d6-427a-4c41-8fca-ffbb07c78ff3)

The [ipxe error](https://ipxe.org/err/3e1161) says the dns name does not exist.

So... At this point I don't what's going on, and I hope somebody help me.

This is the iventoy detailed dhcp doc [link](https://www.iventoy.com/en/doc_ext_dhcp.html).
