### DISCUSSION TITLE
API not accepting POST requests

### DISCUSSION THREAD

**Discussion by mikkelandreasen** [AdguardTeam/AdGuardHome#7786] [Q&A]
I'm trying to automate some ongoing configuration changes using the API, but cannot seem to get the API to accept POST requests.

My ADH is running as a container on Ubuntu 24.04 and I'm pretty sure I haven't disabled anything to make it reject POST requests

docker-compose.yaml
```
version: "3"
services:
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 3030:3000/tcp
      - 3080:80/tcp
    volumes:
      - /docker/appdata/adguard/workdir:/opt/adguardhome/work
      - /docker/appdata/adguard/confdir:/opt/adguardhome/conf
    restart: always

```
config file
```

user@mac ~ % cat atv.json 
   {
      "name": "AppleTV.domain.local",
      "upstreams": [
        "1.1.1.1",
        "[/domain.local/]192.168.99.99"
      ],
    }
```
Command
```
user@mac ~ % auth_header=`echo -n "admin:SecretPasswordRedacted" | base64`
  curl -X POST \
  'http://192.168.99.99:3080/control/clients' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -H "Authorization: Basic $auth_header"\
  -d @atv.json
only method GET is allowed
```
