### DISCUSSION TITLE
Clients all have the same IP when connected over DoH

### DISCUSSION THREAD

**Discussion by VixiKitsune** [AdguardTeam/AdGuardHome#7788] [Q&A]
All my my clients connecting over https have the same IP 10.0.6.3

Is this expected behavior or a config issue?

I have AdGuard Home and NPM Plus docker containers on the same bridge network with only port 53 published on the AGH container and NPM Plus is proxying requests to the AGH container on port 443.

**Comment by he-pennypacker** [comment]
That's expected when using the docker bridge network. You need to configure the docker network as host to see client IPs.

https://github.com/AdguardTeam/AdGuardHome/wiki/Docker#client-ips

**Reply by VixiKitsune** [reply]
I've reset it as host and set ports 80 and 443 as host on NPM container.
I've added the NPM container's IP as a trusted proxy.

Now my clients all show as the router IP on Doh.
On non https queries I see the correct client IP.

**Reply by he-pennypacker** [reply]
> I've added the NPM container's IP as a trusted proxy.

Sorry, I'm not familiar with that, but does this help?

https://github.com/AdguardTeam/AdGuardHome/issues/4132#issuecomment-1014141530

**Reply by VixiKitsune** [reply]
No, the last 3 posts are someone else who tried to add add trusted proxy and still can't get client IP.
I wonder if it's a forwarding issue with my router.

**Comment by gvoysey** [comment]
i'm seeing this as well, but i'm not sure why: 

```yaml
name: foo
services:
        adguardhome:
                image: adguard/adguardhome
                restart: unless-stopped
                network_mode: host
                volumes:
                        - adguard-work:/opt/adguardhome/work
                        - adguard-conf:/opt/adguardhome/conf
                # ports:
                #         - "53:53/tcp" # plain DNS
                #         - "53:53/udp" # plain DNS
                #         - "3000:3000/tcp" # admin panel

volumes:
        adguard-work:
        adguard-conf:

```

webapp works, i can see all the blocked things; all client IPs are the same.
