### DISCUSSION TITLE
How to use mac_address in docker compose version 3.8

### DISCUSSION THREAD

**Discussion by Generalnoob** [AdguardTeam/AdGuardHome#7833] [Q&A]
Hi there, I'm trying to assign a mac address to my AdGuard Home docker container but it's not allowing the mac_address  parameter is there something I'm missing?

```
version: "3.8"
services:
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 784:784/udp
      - 853:853/tcp
      - 3000:3000/tcp
      - 7000:80/tcp
      - 7001:443/tcp
    volumes:
      - /opt/data/AdGuard/work:/opt/adguardhome/work
      - /opt/data/AdGuard/config:/opt/adguardhome/conf
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 2gb
    restart: unless-stopped
    networks:
      custom_macvlan:
        ipv4_address: 192.168.0.2
        mac_address: 00:00:00:00:00:00
networks:
  custom_macvlan:
    driver: macvlan
    driver_opts:
      parent: eth0 # Change 'eth0' to match your network interface
    ipam:
      config:
        - subnet: 192.168.0.0/24
          gateway: 192.168.0.1
```
