### ISSUE TITLE
Setting to allow serving DNS-over-HTTPS unencrypted

### ISSUE THREAD

**Issue by yegle** [AdguardTeam/AdGuardHome#1009]
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description
I have a public IP and I already have a reverse proxy (with wildcard certificate) in place to serve different websites.

Adguard Home's DoH support seem to only provide encrypted service, and have no option to provide non-encrypted plaintext HTTP, which means I need to reverse proxy HTTPS traffic to HTTPS backend if I want to keep my existing reverse proxy.

### Proposed Solution
Adguard Home should be able to provide the same HTTP request handler in plaintext HTTP, so that I can terminate HTTPS connection using my reverse proxy and forward to backend via HTTP.

### Alternatives Considered
Reverse proxy HTTPS traffic in HTTPS.

### Additional Information
Full disclosure: I know Adguard Home have closed relationship with CoreDNS and this FR has been rejected: https://github.com/coredns/coredns/issues/3257

But I still think this is a valid feature and should be supported:
1. It's very common to terminate SSL and serve HTTP service on different server (or in the world of containers, on different containers). Requiring HTTPS on the server serving HTTP means the certificate is unnecessarily widely distributed, and additional step each time you renew your certificate.
2. Go's HTTPS support lacks OCSP stapling support which is crucial for a DoH server (See https://tools.ietf.org/html/rfc8484#section-10). This can easily mitigated by terminating SSL with tools like nginx.

I hope you are convinced this is a good idea :-)

**Comment by ameshkov** [comment]
Well, I see no problem with this.

Please submit a pull request.

Here's where you need to make the change:
https://github.com/AdguardTeam/AdGuardHome/blob/master/home/control.go#L521

**Comment by yegle** [comment]
Great! I'll see if I can do it this weekend.

**Comment by Akruidenberg** [comment]
> 
> 
> Great! I'll see if I can do it this weekend.

Any progress?

**Comment by yegle** [comment]
Sorry I was distracted. Will send a PR this weekend.

**Comment by yegle** [comment]
FWIW, I think the user should also be able to enable DNS-over-HTTP via the settings page. That would take a while to get right as I'm not very familiar with the frontend stuff.

**Comment by yegle** [comment]
:-(

It looks like the UI is implemented in React, which I have 0 knowledge of. I guess I'll leave this up to you to implement.

What I want to see in the settings page:

1. One option to enable DoT
2. One option to enable HTTPS, with two radio button "Enable HTTPS" and "Disable HTTPS", but provide a checkbox under "Disable HTTPS" saying "enable DNS-over-HTTPS on HTTP port"

**Comment by OMICRON3069** [comment]
If AGH serves DNS over HTTP behind a reverse proxy, maybe it's a good idea to recognize client's real IP from http header (i.e. `X-Real-IP` and `X-Forwarded-For`) for request coming from localhost?

**Comment by yegle** [comment]
That would be my expectation yes.

**Comment by ameshkov** [comment]
@yegle I suggest starting with something really simple -- not expose this to the UI at all, just add a configuration property that will enable this behavior

**Comment by Akruidenberg** [comment]
Is also possible to do this with DOT?

**Comment by ameshkov** [comment]
@Akruidenberg it does not make much sense to do it for DOT. DOT without encryption is simply plain DNS over TCP which is already supported.

**Comment by szolin** [comment]
ec8fe0b40c5f0cf48ad2c94174e3c23898c86428
Is there something else we should do on this issue?

**Comment by ameshkov** [comment]
@szolin well, I think we should make it possible to change it in the UI.

Let's discuss it later, I've assigned it to v0.104

**Comment by Akruidenberg** [comment]
Is this already implemented in version 0.100.9? The option is available in the config file. Whicj docker labels are needed for traefik to get this working? The example is only of nginx. 
Also, when i set the value from false to true, how can i see if its working?
Nothing changed in the web interface.

**Comment by szolin** [comment]
Yes, it's implemented.  But there's no way to set in via UI, you have to edit yaml file:
https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration
>   * `allow_unencrypted_doh` - Allow DOH queries via unencrypted HTTP (e.g. for reverse proxying)

**Comment by Akruidenberg** [comment]
> Yes, it's implemented. But there's no way to set in via UI, you have to edit yaml file:
> https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration
> 
> > * `allow_unencrypted_doh` - Allow DOH queries via unencrypted HTTP (e.g. for reverse proxying)

Maybe it's an good idea to write a article on the wiki with some examples with nginx and traefik. is a bit difficult to configure to get it working.

**Comment by Akruidenberg** [comment]
> > Yes, it's implemented. But there's no way to set in via UI, you have to edit yaml file:
> > https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration
> > > * `allow_unencrypted_doh` - Allow DOH queries via unencrypted HTTP (e.g. for reverse proxying)
> 
> Maybe it's an good idea to write a article on the wiki with some examples with nginx and traefik. is a bit difficult to configure to get it working.

Got dns over https working now. Not to difficult. set traefik to route over port 80 (http) and set "allow_unencrypted_doh" and the SNI value to true. 

However, how to get Traefik 2 working with dns over tls. Traefik version 2 supports tcp. 
I dont know how to set my compose file to get it working.

This is my config:

```
adguard:
    container_name: adguardhome
    restart: unless-stopped
    image: adguard/adguardhome
    hostname: adguard
    ports:
      - "53:53"
      - "53:53/udp"
    expose:
      - "80"
      - "3000"
      - "443"
      - "853"
    volumes:
      - ${USERDIR}/adguard/conf:/opt/adguardhome/conf
      - ${USERDIR}/adguard/work:/opt/adguardhome/work
    user: ${PUID}
    networks:
      - reverseproxy
    labels:
      traefik.enable: "true"
      ## HTTP Routers
      traefik.http.routers.adguard-rtr.entrypoints: https
      traefik.http.routers.adguard-rtr.rule: Host(`dns.$DOMAINBASE`)
      traefik.http.routers.adguard-rtr.tls: "true"
      traefik.http.routers.adguard-rtr.tls.certresolver: ovh
      ## Middlewares
      ## HTTP Services
      traefik.http.routers.adguard-rtr.service: adguard-svc
      traefik.http.services.adguard-svc.loadbalancer.server.port: 80  
      ###TCP
      traefik.tcp.routers.adguard-tls.entrypoints: tls
      traefik.tcp.routers.adguard-tls.rule: HostSNI(`dns.$DOMAINBASE`)
      traefik.tcp.routers.adguard-tls.tls: "true"
      traefik.tcp.routers.adguard-tls.tls.certresolver: ovh
      ## Middlewares
      ## tcp Services
      traefik.tcp.routers.adguard-tls.service: adguard-svc-tls
      traefik.tcp.services.adguard-svc-tls.loadbalancer.server.port: 853
```

How to get this config working?

**Comment by Akruidenberg** [comment]
its working! wrong port: 853 is wrong. must be 53.

**Comment by Akruidenberg** [comment]
new update: DOT is sometimes slow with complex pages. DOH is working very well with traefik.
I dont get this issue in the past (with self signed certifites and without traefik. 
Tried - **"traefik.tcp.services.mytcpservice.loadbalancer.terminationdelay=100"** but no luck.
Is this a bug in Adguard?

**Comment by tristanXme** [comment]
I can't get DoT working with a custom signed Cert. Can i deactivate the cert validation from AdGuard Home?

**Comment by ameshkov** [comment]
Implemented long time ago. Closing since we don't plan to provide any UI setting for that, unencrypted DOH is an option that's supposed to be used by people who know what they're doing and know how to change the config file.

**Comment by Allen-Hu** [comment]
Sorry for bumping this issue from long ago.
I'm also trying to set up a nginx reverse proxy that manages the certificates and proxy to adguard container unencrypted.

This is my current `tls` part of the config:
```
tls:
  enabled: true
  server_name: my.domain.name
  force_https: false
  port_https: 0
  port_dns_over_tls: 853
  port_dns_over_quic: 784
  port_dnscrypt: 0
  dnscrypt_config_file: ""
  allow_unencrypted_doh: true
  strict_sni_check: false
  certificate_chain: ""
  private_key: ""
  certificate_path: ""
  private_key_path: ""
```
My main question is: How do I set the port DoH server is listening to? Cause I keep getting connection refused on port 80.
