### ISSUE TITLE
Manage safesearch for each service

### ISSUE THREAD

**Issue by ammnt** [AdguardTeam/AdGuardHome#1163]
(Updating the top post to summarize the discussion and make sure nothing is lost; original content is under the `<details>` tag. — @ainar-g)

The way I see it, we'll need the following changes:

 *  UI:
     *  The single *Use Safe Search* boolean should be changed into a section of seven booleans:

         *  enabled (to enable or disable Safe Search entirely);
         *  Bing;
         *  DuckDuckGo;
         *  Google;
         *  Pixabay;
         *  Yandex;
         *  YouTube;

 *  Internals:
     *  We should probably finally switch to the lists from the [Hostlists Registry][1], at least in SafeSearch.  That means using the same machinery that we already use for `dnsrewrite` rules.

     *  The support for these more fine-tuned settings should be extended to persistent clients as well.

 *  Configuration file:
     *  The current `safesearch_enabled` should be replaced by an object containing per-service settings.  E.g.:

        ```yaml
        safe_search:
            enabled: true
            bing: false
            duckduckgo: true
            google: false
            pixabay: false
            yandex: true
            youtube: false
        ```
     *  The same in the `clients.persistent` objects.

[1]: https://adguardteam.github.io/HostlistsRegistry/

* * *

<details>
<summary>Original post content</summary>

Hello,

it would be great to manage a safesearch for each service separately. Because safesearch for engines disables sites for adults mostly, but for YouTube disables half the content marked as unacceptable for kids. For example, this video is not available in safesearch mode:
https://www.youtube.com/watch?v=6YoFkb-LOzg

IMHO this is excessive, but you can only disable it with a safesearch for other services.

Thank you.

</details>
