### ISSUE TITLE
DNS over TLS - ERR_SSL_PROTOCOL_ERROR

### ISSUE THREAD

**Issue by iganeshk** [AdguardTeam/AdGuardHome#1413]
### Issue Details

When accessing some websites with DoT, I get:

* macOS w/ Stubby
Chrome - ERR_SSL_PROTOCOL_ERROR
Firefox (73) - SSL_ERROR_RX_RECORD_TOO_LONG
cURL (7.64.1) - 
```
  curl -i https://my.nextdns.io/ -verbose
    Trying 104.31.89.168...
  TCP_NODELAY set
  Connected to my.nextdns.io (104.31.89.168) port 443 (#0)
  ALPN, offering h2
  ALPN, offering http/1.1
  successfully set certificate verify locations:
    CAfile: /etc/ssl/cert.pem
  CApath: none
  TLSv1.2 (OUT), TLS handshake, Client hello (1):
  error:1400410B:SSL routines:CONNECT_CR_SRVR_HELLO:wrong version number
  Closing connection 0
curl: (35) error:1400410B:SSL routines:CONNECT_CR_SRVR_HELLO:wrong version number
```

* Android (10) w/ Private DNS

![Screenshot_20200216-104116](https://user-images.githubusercontent.com/23004399/74607737-378e7700-50a9-11ea-8953-6725384eb46a.jpg)

### TLS Settings (running without DNS-o-HTTPS)

```
tls:
  enabled: true
  server_name: mydomain.com
  force_https: false
  port_https: 0
  port_dns_over_tls: 853
  allow_unencrypted_doh: false
  strict_sni_check: true
  certificate_chain: ""
  private_key: ""
  certificate_path: /path/to/fullchain.pem
  private_key_path: /path/to/key.pem
```

* **Version of AdGuard Home server:**
* v0.100.9-91-g9a81-dirty

* **How did you setup DNS configuration:**
  * System
* **Operating system and version:**
  * Debian 10.2

### Additional Information
When trying to access without the DoT, I'm able to access the website.
