### ISSUE TITLE
AdGuard Home expects valid TLS config even when allow_unencrypted_doh is configured

### ISSUE THREAD

**Issue by itsnotv** [AdguardTeam/AdGuardHome#1677]
Latest version of adguard docker image is not coming up anymore.

adguard/adguardhome:latest
Digest:sha256:2bba41aaefd6423af3c362dc578624784b2339b86c64f901116e9fcdf4823edf

```
adguard    | 2020/05/15 22:15:27 1#1 [info] AdGuard Home, version v0.102.0, channel release, arch linux amd64
adguard    | 2020/05/15 22:15:27 1#1 [debug] Current working directory is /opt/adguardhome/work
adguard    | 2020/05/15 22:15:27 1#1 [debug] github.com/AdguardTeam/AdGuardHome/home.upgradeConfig(): got schema version 6
adguard    | 2020/05/15 22:15:27 1#1 [debug] Reading config file: /opt/adguardhome/conf/AdGuardHome.yaml
adguard    | 2020/05/15 22:15:27 1#1 [debug] Clients: removed 0 client aliases
adguard    | 2020/05/15 22:15:27 1#1 [debug] Clients: added 0 client aliases from DHCP
adguard    | 2020/05/15 22:15:27 1#1 [debug] Writing YAML file: /opt/adguardhome/conf/AdGuardHome.yaml
adguard    | 2020/05/15 22:15:27 1#1 [info] Initializing auth module: /opt/adguardhome/work/data/sessions.db
adguard    | 2020/05/15 22:15:27 1#1 [debug] Auth: loaded 11 sessions from DB (removed 0 expired)
adguard    | 2020/05/15 22:15:27 1#1 [info] Auth: initialized.  users:1  sessions:11
adguard    | 2020/05/15 22:15:27 1#1 [error]
adguard    | 2020/05/15 22:15:27 1#1 [fatal] Can't initialize TLS module
```
Verified that reverting to "v0.101.0" works.

**Comment by ameshkov** [comment]
@itsnotv hi, is this a new install or are you updating existing version?

**Comment by itsnotv** [comment]
Updated to latest

**Comment by ameshkov** [comment]
I don't yet understand what happened to the TLS module, it seems that it failed to validate the cert.

Could you please tell me how TLS is configured in your case? File path or contents? Server name?

**Comment by itsnotv** [comment]
Here is the config which works with v0.101.0

```
tls:
  enabled: true
  server_name: '<redacted>'
  force_https: false
  port_https: 0
  port_dns_over_tls: 0
  allow_unencrypted_doh: true
  strict_sni_check: false
  certificate_chain: ""
  private_key: ""
  certificate_path: ""
  private_key_path: ""
```

I was using certs before, but removed them sometime back, because I only use dns over https with allow_unencrypted_doh:true, I have nginx proxy for ssl.
