### ISSUE TITLE
Trailing 0 in last IP octet is ignored when specifying disallowed client

### ISSUE THREAD

**Issue by Freekers** [AdguardTeam/AdGuardHome#1687]
### Issue Details

* **Version of AdGuard Home server:**
v0.102.0 (Docker)
* **How did you setup DNS configuration:**
Router
* **If it's a router or IoT, please write device model:**
Mikrotik RB962UiGS-5HacT2HnT hAP AC
* **Operating system and version:**
Windows 10

### Expected Behavior
When specifying disallowed clients, the trailing 0 in the last IP octet is ignored. For example, when adding `192.168.88.100` as disallowed client, `192.168.88.1` will be blocked instead. This also holds for IPs or IP ranges specified using the CIDR notation.

### Actual Behavior
The entire last octet, including trailing 0, should be honored when specifying disallowed clients.

### Screenshots
![image](https://user-images.githubusercontent.com/1370857/82131428-61a12380-97d5-11ea-9588-860da391d207.png)
As shown in the screenshot above, I have only have IP added to the disallowed client list, namely: `192.168.88.100`

![image](https://user-images.githubusercontent.com/1370857/82131438-75e52080-97d5-11ea-8432-0a606527e156.png)
However, in the Dashboard, `192.68.88.1` shows up as being blocked, even though this IP is not present in the disallowed client lists

![image](https://user-images.githubusercontent.com/1370857/82131441-7d0c2e80-97d5-11ea-88f3-fa35a70a2fa7.png)

The same issue holds for all IP addresses ending on one or more zeroes (in the last octet)
</details>

**Comment by szolin** [comment]
But the clients blocked by 'disallowed clients' settings *are not* shown in statistics!
Please check your settings - most likely there's another setting that blocks your `88.1` IP address.

**Comment by ameshkov** [comment]
This must be a UI issue

**Comment by Freekers** [comment]
> But the clients blocked by 'disallowed clients' settings _are not_ shown in statistics!
> Please check your settings - most likely there's another setting that blocks your `88.1` IP address.

@szolin When or what makes a client show up in the statistics with a red banner and unblock button?
I'm almost certain it's caused by having added `192.168.88.100` to the disallowed clients, because if I remove it, `192.68.88.1` doesn't show up as being blocked anymore (nor does `192.168.88.100` of course). Apart from that, I do not have any other disallowed clients. 

Here's my config file:

```
bind_host: 0.0.0.0
bind_port: 8081
users:
- name: freekers
  password: XXXXXXXXXXXXXXXXXXXXX
http_proxy: ""
language: ""
rlimit_nofile: 0
debug_pprof: false
web_session_ttl: 720
dns:
  bind_host: 192.168.88.222
  port: 53
  statistics_interval: 90
  querylog_enabled: true
  querylog_interval: 7
  querylog_size_memory: 1000
  anonymize_client_ip: false
  protection_enabled: true
  blocking_mode: null_ip
  blocking_ipv4: ""
  blocking_ipv6: ""
  blocked_response_ttl: 10
  parental_block_host: family-block.dns.adguard.com
  safebrowsing_block_host: standard-block.dns.adguard.com
  ratelimit: 100
  ratelimit_whitelist: []
  refuse_any: false
  upstream_dns:
  - 192.168.88.222:5353
  bootstrap_dns:
  - 9.9.9.10
  - 149.112.112.10
  - 2620:fe::10
  - 2620:fe::fe:10
  all_servers: false
  fastest_addr: false
  allowed_clients: []
  disallowed_clients:
  - 192.168.88.100
  blocked_hosts: []
  cache_size: 0
  cache_ttl_min: 0
  cache_ttl_max: 0
  bogus_nxdomain: []
  aaaa_disabled: false
  enable_dnssec: true
  edns_client_subnet: false
  filtering_enabled: true
  filters_update_interval: 12
  parental_enabled: false
  safesearch_enabled: false
  safebrowsing_enabled: false
  safebrowsing_cache_size: 1048576
  safesearch_cache_size: 1048576
  parental_cache_size: 1048576
  cache_time: 30
  rewrites:
  - domain: adguard.XXXXXX
    answer: 192.168.88.222
  blocked_services: []
tls:
  enabled: true
  server_name: adguard.XXXXXX
  force_https: false
  port_https: 444
  port_dns_over_tls: 853
  allow_unencrypted_doh: false
  strict_sni_check: false
  certificate_chain: ""
  private_key: ""
  certificate_path: /opt/adguardhome/fullchain.pem
  private_key_path: /opt/adguardhome/privkey.pem
filters:
- enabled: true
  url: https://abp.oisd.nl/
  name: OISD
  id: 1589486914
- enabled: true
  url: https://raw.githubusercontent.com/ookangzheng/dbl-oisd-nl/master/abp.txt
  name: OISD Mirror
  id: 1589486915
whitelist_filters:
- enabled: true
  url: https://raw.githubusercontent.com/Freekers/whitelist/master/domains/whitelist.txt
  name: Freekers
  id: 1589486916
user_rules:
- '||cloudlinks.cn^'
- '||cloud-links.net^'
- '||secu100.net^'
dhcp:
  enabled: false
  interface_name: ""
  gateway_ip: ""
  subnet_mask: ""
  range_start: ""
  range_end: ""
  lease_duration: 86400
  icmp_timeout_msec: 1000
clients: []
log_file: ""
verbose: false
schema_version: 6
```

> This must be a UI issue

@ameshkov I did some more testing and I suspect the same. I have found that adding *any* IP address that starts with `192.168.88.1` to the disallowed client list, will make the particular IP show up as blocked (as intended), but also the gateway/router (i.e. 192.168.88.1) will show up as blocked, even though it is _not_ on the disallowed client list.  

For example, if 192.168.88.111 is added as disallowed client, both 192.168.88.111 and 192.168.88.1 show as blocked. Another example; if 192.168.88.184 is added as disallowed client, both 192.168.88.184 and 192.168.88.1 show as blocked, and so on.

DNS resolution for the gateway/router (192.168.88.1) seems to be working though, even though it shows up as blocked.
