### ISSUE TITLE
Error when checking for existing DHCP servers on Docker

### ISSUE THREAD

**Issue by nassoor** [AdguardTeam/AdGuardHome#1756]
### Issue Details

* **Version of AdGuard Home server:**
  *  v0.102.0
* **Operating system and version:**
  *  Docker 18.09.8, Synology DSM 6.2.2

When clicking the Check for DHCP server button I get:

> In order to use DHCP server a static IP address must be set. We failed to determine if this network interface is configured using static IP address. Please set a static IP address manually.
> 
> Error details:
> open /etc/dhcpcd.conf: no such file or directory

My docker-compose file:
```
version: '2'

services:
 adguard:
   container_name: adguard
   image: adguard/adguardhome:latest
   networks:
     adguard_network:
       ipv4_address: 192.168.100.9
   volumes:
     - "/volume1/docker/adguard/config:/opt/adguardhome/conf"
     - "/volume1/docker/adguard/data:/opt/adguardhome/work"
   restart: unless-stopped

networks:
 adguard_network:
   driver: macvlan
   driver_opts:
     parent: eth0
   ipam:
     config:
       - subnet: 192.168.100.0/24
         gateway: 192.168.100.254
         ip_range: 192.168.100.9/32
```
