### ISSUE TITLE
Option to output DNS responses (like in query log) to stdout

### ISSUE THREAD

**Issue by MadDud** [AdguardTeam/AdGuardHome#1821]
### Problem Description
Can AdGuard return DNS responses to STDOUT with exact same data as listed in query log (time, domain name, type, response, client) in key:value pair format? If we get this data in stdout, we could forward these events to different systems for further investigation.

### Proposed Solution
Add new option in command-line agrument --dns-logs to include them in data, which goes to whatever --logfile is configured to. 

### Additional Information
I want to forward these events to Splunk, which wolud allow me to have alerting and reporting functionality.

**Comment by szolin** [comment]
You can parse querylog.json file exactly the same way you would parse the output from the stdout.  I doubt that we need an additional setting for that.
Note that you should use `querylog_size_memory: 0` setting to prevent logs from being buffer in memory before they are flushed to a file.

**Comment by mazay** [comment]
that was one of my struggles with multi-node setup on k8s

found a workaround that works for me but would be great to have a proper/native solution

```yaml
containers:
# AGH container
- name: adguard
  image: adguard/adguardhome:v0.107.56
  readinessProbe:
    tcpSocket:
      port: dns-tcp
    timeoutSeconds: 30
    initialDelaySeconds: 30
    failureThreshold: 2
  livenessProbe:
    tcpSocket:
      port: dns-tcp
    timeoutSeconds: 30
    failureThreshold: 2
  resources:
    requests:
      cpu: 500m
      memory: 768Mi
    limits:
      cpu: 4000m
      memory: 768Mi
  ports:
  - containerPort: 53
    name: dns
    protocol: UDP
    hostPort: 53
  - containerPort: 53
    name: dns-tcp
    protocol: TCP
    hostPort: 53
  - containerPort: 80
    name: ui
    protocol: TCP
  volumeMounts:
  - name: config
    mountPath: /opt/adguardhome/conf
  - name: logs
    mountPath: /opt/agh/logs
# AGH exporter, so I can have consiolidated metrics in Prometheus/Grafana
- name: adguard-exporter
  image: ghcr.io/henrywhitaker3/adguard-exporter:v1.2.0
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      cpu: 50m
      memory: 32Mi
  ports:
  - containerPort: 9618
    name: metrics
    protocol: TCP
  env:
  - name: ADGUARD_SERVERS
    value: "http://localhost"
  - name: INTERVAL
    value: "15s"
  - name: ADGUARD_USERNAMES
    valueFrom:
      secretKeyRef:
        name: agh-credentials
        key: username
  - name: ADGUARD_PASSWORDS
    valueFrom:
      secretKeyRef:
        name: agh-credentials
        key: password
# AGH querylog container, so I can have query logs in Loki/Grafana
- name: querylog
  image: busybox:stable
  imagePullPolicy: Always
  command: ["/bin/sh"]
  args:
  - -c
  - until [ -f /opt/agh/logs/querylog.json ]; do sleep 5; done; tail -f /opt/agh/logs/querylog.json
  resources:
    requests:
      cpu: 10m
      memory: 8Mi
    limits:
      cpu: 50m
      memory: 8Mi
  volumeMounts:
  - name: logs
    mountPath: /opt/agh/logs
volumes:
- name: config
  persistentVolumeClaim:
    claimName: adguard-config # shared config directory
- name: logs
  emptyDir: {}
```
