### ISSUE TITLE
Docker use with a reverse proxy in host mode (traefik or caddy) 

### ISSUE THREAD

**Issue by MeisterTea** [AdguardTeam/AdGuardHome#1872]
### Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

My isp router does not provide a way to input the dns server. The only way I found to be working is to use the dhcp server of adguardhome (or pi hole) 

I am using docker-compose with traefik at the moment (thinking to use caddy) 

If I understand correctly, in order to use the dhcp function of agh, I have to use it in host_mode: network 
If I use host_mode: network and remap port 80, it seems to be still used and prevents traefik to start correctly. 

Could you provide me with a working docker-compose example with either traefik or caddy working? 

* **Version of AdGuard Home server:**
  * armhf-edge
* **How did you setup DNS configuration:**
  * docker
* **If it's a router or IoT, please write device model:**
  * raspberry pi 4
* **Operating system and version:**
  * raspberry pi os

### Expected Behavior
I should be able to use adguardhome with a reverse proxy in network mode

### Actual Behavior
As adguardhome uses the port 80, I can't use it with a reverse proxy (traefik) on network_mode: host because when I remap the port 80 it looks like it's still used by default. (seems like a docker issue) 

### Screenshots
None

### Additional Information
None

**Comment by ameshkov** [comment]
I am not an expert at traefik so let's wait maybe someone else can advise

**Comment by MeisterTea** [comment]
This works fine

```
version: "3.6"

services:
  adguard:
    command: "-p 8201"
    container_name: adguard
    image: adguard/adguardhome:armhf-edge
    network_mode: host
    restart: always
    volumes:
      - /etc/opt/adguardhome:/opt/adguardhome/conf
      - /opt/adguardhome/work:/opt/adguardhome/work
```
