### ISSUE TITLE
Adguard Home has high cpu usage, high memory usage, constantly spikes the cpu and remains unresponsive during filterlist/allowlist or blocklist changes - insanely more so than pihole.

### ISSUE THREAD

**Issue by waffshappen** [AdguardTeam/AdGuardHome#2041]
### Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * 0.103.3 , raspi 32 bit arm version
* **How did you setup DNS configuration:**
  * dnsmasq handing it out as DHCP option
* **If it's a router or IoT, please write device model:**
  * Router: Zbox Nano with Fedora, Adguard Home: Raspberry Pi 3B
* **Operating system and version:**
  * Raspian current 32bit, Fedora 32 on Raspi4 with rpi4-uefi

### Expected Behavior
When comparing adguard home to pihole i expected the following:

For the same amount of Filterlists it should remain as responsive, even if there are a lot
Remain fast when i add or delete entries to the blocklists/allowlists
Startup fast-ish
To not constantly use cpu time

### Actual Behavior
When booting the pi or restarting adguard home it takes ~2 Minutes to initialize and build the filterlists.
The same goes for when i add or remove blocklist entires and adguard entirely stops responding for up to several minutes.
This also shows in the "average time to process" since those queries are then listed as taking 3+ Minutes.

Adguard, after boot, constantly spikes on the cpu. It entirely goes 100% for 2 Minutes while rebuilding filterlists and keeps constantly using a surprisingly huge amount of cpu time afterwards. This also drives the pi into much higher thermals than with pihole.

Of course, entirely not responding via dns during filterlist rebuild - or boot - is less than an optimal experience.

And to top the above it uses several times the memory of pihole, making it only feasible to be run on a larger vm/raspi4 because the system already starts swapping on the pi3.

I expected it to be a smooth swap-over to get Dnscrypt/DoH/DoT but in this state, especially since debugging takes 2-3 minutes to rebuild with no dns response of any kind during the time when i add black/whitelists its not as easy to go entirely in on Adguard Home. Especially since everything here is setup the same way. Same dns servers (just with DoH/DoT/Dnscrypt), same filterlists as pihole before.

#### You can clearly see when i switched on adguard.

<details open><summary>Screenshots:</summary>

Cpu vs pihole
The spike on the left is a pihole filterlist update, the spike on the right are adguards'.

![adguardcpu](https://user-images.githubusercontent.com/44290023/91024862-d8ca2d00-e5f8-11ea-8320-d6a8e4d930a1.png)

Cpu spiking closeup
![adguardcpu-closeup](https://user-images.githubusercontent.com/44290023/91024871-dc5db400-e5f8-11ea-871b-b22f72387eac.png)

Memory over time vs pihole
![adguardmemory](https://user-images.githubusercontent.com/44290023/91024880-dec00e00-e5f8-11ea-9add-2f42f5f03350.png)

</details>

<details><summary>Full Config:</summary>

```yml
bind_host: 0.0.0.0
bind_port: 80
users:
- name: [omitted]
  password: [omitted]
http_proxy: ""
language: ""
rlimit_nofile: 0
debug_pprof: false
web_session_ttl: 720
dns:
  bind_host: 0.0.0.0
  port: 53
  statistics_interval: 90
  querylog_enabled: true
  querylog_file_enabled: true
  querylog_interval: 90
  querylog_size_memory: 1000
  anonymize_client_ip: false
  protection_enabled: true
  blocking_mode: default
  blocking_ipv4: ""
  blocking_ipv6: ""
  blocked_response_ttl: 10
  parental_block_host: family-block.dns.adguard.com
  safebrowsing_block_host: standard-block.dns.adguard.com
  ratelimit: 20
  ratelimit_whitelist: []
  refuse_any: true
  upstream_dns:
  - https://dns.digitale-gesellschaft.ch/dns-query
  - tls://dns2.digitalcourage.de#853
  - tls://dns.digitale-gesellschaft.ch#853
  - sdns://AQcAAAAAAAAAEzYyLjIxMC4xNzcuMTg5OjEwNTMgW8vytBGk6u3kvCpl4q88XjqW-w6JJiJ7QBObcFV7gYAfMi5kbnNjcnlwdC1jZXJ0Lm5zMS5pcmlzZWRlbi5mcg
  bootstrap_dns:
  - 46.182.19.48
  - 1.1.1.1
  all_servers: true
  fastest_addr: false
  allowed_clients: []
  disallowed_clients: []
  blocked_hosts: []
  cache_size: 4194304
  cache_ttl_min: 0
  cache_ttl_max: 0
  bogus_nxdomain: []
  aaaa_disabled: false
  enable_dnssec: true
  edns_client_subnet: false
  filtering_enabled: true
  filters_update_interval: 24
  parental_enabled: false
  safesearch_enabled: false
  safebrowsing_enabled: false
  safebrowsing_cache_size: 1048576
  safesearch_cache_size: 1048576
  parental_cache_size: 1048576
  cache_time: 30
  rewrites:
  - domain: [omitted]
    answer: [omitted]
  - domain: [omitted]
    answer: [omitted]
  - domain: [omitted]
    answer: [omitted]
  blocked_services:
  - skype
  - origin
  - epic_games
  - vk
  - snapchat
  - facebook
  - whatsapp
  - mail_ru
  - instagram
  - discord
  - ok
  - tiktok
tls:
  enabled: false
  server_name: ""
  force_https: false
  port_https: 443
  port_dns_over_tls: 853
  allow_unencrypted_doh: false
  strict_sni_check: false
  certificate_chain: ""
  private_key: ""
  certificate_path: ""
  private_key_path: ""
filters:
- enabled: true
  url: https://adaway.org/hosts.txt
  name: https://adaway.org/hosts.txt
  id: 1
- enabled: true
  url: https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt
  name: https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt
  id: 2
- enabled: true
  url: https://bitbucket.org/ethanr/dns-blacklists/raw/8575c9f96e5b4a1308f2f12394abd86d0927a4a0/bad_lists/Mandiant_APT1_Report_Appendix_D.txt
  name: https://bitbucket.org/ethanr/dns-blacklists/raw/8575c9f96e5b4a1308f2f12394abd86d0927a4a0/bad_lists/Mandiant_APT1_Report_Appendix_D.txt
  id: 3
- enabled: true
  url: https://block.energized.pro/basic/formats/hosts.txt
  name: https://block.energized.pro/basic/formats/hosts.txt
  id: 4
- enabled: true
  url: https://blocklistproject.github.io/Lists/abuse.txt
  name: https://blocklistproject.github.io/Lists/abuse.txt
  id: 5
- enabled: true
  url: https://blocklistproject.github.io/Lists/ads.txt
  name: https://blocklistproject.github.io/Lists/ads.txt
  id: 6
- enabled: true
  url: https://blocklistproject.github.io/Lists/fraud.txt
  name: https://blocklistproject.github.io/Lists/fraud.txt
  id: 7
- enabled: true
  url: https://blocklistproject.github.io/Lists/ransomware.txt
  name: https://blocklistproject.github.io/Lists/ransomware.txt
  id: 8
- enabled: true
  url: https://blocklistproject.github.io/Lists/scam.txt
  name: https://blocklistproject.github.io/Lists/scam.txt
  id: 9
- enabled: true
  url: https://blocklistproject.github.io/Lists/tracking.txt
  name: https://blocklistproject.github.io/Lists/tracking.txt
  id: 10
- enabled: true
  url: https://dbl.oisd.nl/
  name: https://dbl.oisd.nl/
  id: 11
- enabled: true
  url: https://gist.githubusercontent.com/BBcan177/b6df57cef74e28d90acf1eec93d62d3b/raw/f0996cf5248657ada2adb396f3636be8716b99eb/MS-4
  name: https://gist.githubusercontent.com/BBcan177/b6df57cef74e28d90acf1eec93d62d3b/raw/f0996cf5248657ada2adb396f3636be8716b99eb/MS-4
  id: 12
- enabled: true
  url: https://github.com/AdAway/adaway.github.io/blob/master/hosts.txt
  name: https://github.com/AdAway/adaway.github.io/blob/master/hosts.txt
  id: 13
- enabled: true
  url: https://gitlab.com/curben/urlhaus-filter/raw/master/urlhaus-filter-hosts.txt
  name: https://gitlab.com/curben/urlhaus-filter/raw/master/urlhaus-filter-hosts.txt
  id: 14
- enabled: true
  url: https://gitlab.com/quidsup/notrack-blocklists/raw/master/notrack-blocklist.txt
  name: https://gitlab.com/quidsup/notrack-blocklists/raw/master/notrack-blocklist.txt
  id: 15
- enabled: true
  url: https://gitlab.com/quidsup/notrack-blocklists/raw/master/notrack-malware.txt
  name: https://gitlab.com/quidsup/notrack-blocklists/raw/master/notrack-malware.txt
  id: 16
- enabled: true
  url: https://gitlab.com/ZeroDot1/CoinBlockerLists/raw/master/list_browser.txt
  name: https://gitlab.com/ZeroDot1/CoinBlockerLists/raw/master/list_browser.txt
  id: 17
- enabled: true
  url: https://gitlab.com/ZeroDot1/CoinBlockerLists/raw/master/list.txt
  name: https://gitlab.com/ZeroDot1/CoinBlockerLists/raw/master/list.txt
  id: 18
- enabled: true
  url: https://gnuzilla.gnu.org/filters/blacklist.txt
  name: https://gnuzilla.gnu.org/filters/blacklist.txt
  id: 19
- enabled: true
  url: https://hostfiles.frogeye.fr/firstparty-trackers-hosts.txt
  name: https://hostfiles.frogeye.fr/firstparty-trackers-hosts.txt
  id: 20
- enabled: true
  url: https://hosts.nfz.moe/basic/hosts
  name: https://hosts.nfz.moe/basic/hosts
  id: 21
- enabled: true
  url: https://mirror1.malwaredomains.com/files/justdomains
  name: https://mirror1.malwaredomains.com/files/justdomains
  id: 22
- enabled: true
  url: https://mirror.cedia.org.ec/malwaredomains/immortal_domains.txt
  name: https://mirror.cedia.org.ec/malwaredomains/immortal_domains.txt
  id: 23
- enabled: true
  url: https://osint.digitalside.it/Threat-Intel/lists/latestdomains.txt
  name: https://osint.digitalside.it/Threat-Intel/lists/latestdomains.txt
  id: 24
- enabled: true
  url: https://paulgb.github.io/BarbBlock/blacklists/domain-list.txt
  name: https://paulgb.github.io/BarbBlock/blacklists/domain-list.txt
  id: 25
- enabled: true
  url: https://pgl.yoyo.org/adservers/serverlist.php?hostformat=adblockplus&showintro=1&mimetype=plaintext
  name: https://pgl.yoyo.org/adservers/serverlist.php?hostformat=adblockplus&showintro=1&mimetype=plaintext
  id: 26
- enabled: true
  url: https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=0&mimetype=plaintext
  name: https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=0&mimetype=plaintext
  id: 27
- enabled: true
  url: https://phishing.army/download/phishing_army_blocklist_extended.txt
  name: https://phishing.army/download/phishing_army_blocklist_extended.txt
  id: 28
- enabled: true
  url: https://raw.github.com/notracking/hosts-blocklists/master/hostnames.txt
  name: https://raw.github.com/notracking/hosts-blocklists/master/hostnames.txt
  id: 29
- enabled: true
  url: https://raw.githubusercontent.com/AdAway/adaway.github.io/master/hosts.txt
  name: https://raw.githubusercontent.com/AdAway/adaway.github.io/master/hosts.txt
  id: 30
- enabled: true
  url: https://raw.githubusercontent.com/Akamaru/Pi-Hole-Lists/master/adobeblock.txt
  name: https://raw.githubusercontent.com/Akamaru/Pi-Hole-Lists/master/adobeblock.txt
  id: 31
- enabled: true
  url: https://raw.githubusercontent.com/Akamaru/Pi-Hole-Lists/master/cryptomine.txt
  name: https://raw.githubusercontent.com/Akamaru/Pi-Hole-Lists/master/cryptomine.txt
  id: 32
- enabled: true
  url: https://raw.githubusercontent.com/Akamaru/Pi-Hole-Lists/master/fakenewsde.txt
  name: https://raw.githubusercontent.com/Akamaru/Pi-Hole-Lists/master/fakenewsde.txt
  id: 33
- enabled: true
  url: https://raw.githubusercontent.com/Akamaru/Pi-Hole-Lists/master/gamefake.txt
  name: https://raw.githubusercontent.com/Akamaru/Pi-Hole-Lists/master/gamefake.txt
  id: 34
- enabled: true
  url: https://raw.githubusercontent.com/Akamaru/Pi-Hole-Lists/master/jbfake.txt
  name: https://raw.githubusercontent.com/Akamaru/Pi-Hole-Lists/master/jbfake.txt
  id: 35
- enabled: true
  url: https://raw.githubusercontent.com/Akamaru/Pi-Hole-Lists/master/nintendoblock.txt
  name: https://raw.githubusercontent.com/Akamaru/Pi-Hole-Lists/master/nintendoblock.txt
  id: 36
- enabled: true
  url: https://raw.githubusercontent.com/Akamaru/Pi-Hole-Lists/master/nomsdata.txt
  name: https://raw.githubusercontent.com/Akamaru/Pi-Hole-Lists/master/nomsdata.txt
  id: 37
- enabled: true
  url: https://raw.githubusercontent.com/anudeepND/blacklist/master/adservers.txt
  name: https://raw.githubusercontent.com/anudeepND/blacklist/master/adservers.txt
  id: 38
- enabled: true
  url: https://raw.githubusercontent.com/autinerd/anti-axelspringer-hosts/master/axelspringer-hosts
  name: https://raw.githubusercontent.com/autinerd/anti-axelspringer-hosts/master/axelspringer-hosts
  id: 39
- enabled: true
  url: https://raw.githubusercontent.com/bigdargon/hostsVN/master/hosts
  name: https://raw.githubusercontent.com/bigdargon/hostsVN/master/hosts
  id: 40
- enabled: true
  url: https://raw.githubusercontent.com/bloodhunterd/pi-hole-blocklists/master/Baidu.txt
  name: https://raw.githubusercontent.com/bloodhunterd/pi-hole-blocklists/master/Baidu.txt
  id: 41
- enabled: true
  url: https://raw.githubusercontent.com/bloodhunterd/pi-hole-blocklists/master/HP.txt
  name: https://raw.githubusercontent.com/bloodhunterd/pi-hole-blocklists/master/HP.txt
  id: 42
- enabled: true
  url: https://raw.githubusercontent.com/bloodhunterd/pi-hole-blocklists/master/LG.txt
  name: https://raw.githubusercontent.com/bloodhunterd/pi-hole-blocklists/master/LG.txt
  id: 43
- enabled: true
  url: https://raw.githubusercontent.com/bloodhunterd/pi-hole-blocklists/master/Synology.txt
  name: https://raw.githubusercontent.com/bloodhunterd/pi-hole-blocklists/master/Synology.txt
  id: 44
- enabled: true
  url: https://raw.githubusercontent.com/bloodhunterd/pi-hole-blocklists/master/Ubisoft.txt
  name: https://raw.githubusercontent.com/bloodhunterd/pi-hole-blocklists/master/Ubisoft.txt
  id: 45
- enabled: true
  url: https://raw.githubusercontent.com/bloodhunterd/pi-hole-blocklists/master/Xiaomi.txt
  name: https://raw.githubusercontent.com/bloodhunterd/pi-hole-blocklists/master/Xiaomi.txt
  id: 46
- enabled: true
  url: https://raw.githubusercontent.com/buggerman/SwitchBlockerForPiHole/master/Paranoid.txt
  name: https://raw.githubusercontent.com/buggerman/SwitchBlockerForPiHole/master/Paranoid.txt
  id: 47
- enabled: true
  url: https://raw.githubusercontent.com/cbuijs/shallalist/master/adv/domains
  name: https://raw.githubusercontent.com/cbuijs/shallalist/master/adv/domains
  id: 48
- enabled: true
  url: https://raw.githubusercontent.com/cbuijs/shallalist/master/costtraps/domains
  name: https://raw.githubusercontent.com/cbuijs/shallalist/master/costtraps/domains
  id: 49
- enabled: true
  url: https://raw.githubusercontent.com/cbuijs/shallalist/master/religion/domains
  name: https://raw.githubusercontent.com/cbuijs/shallalist/master/religion/domains
  id: 50
- enabled: true
  url: https://raw.githubusercontent.com/cbuijs/shallalist/master/spyware/domains
  name: https://raw.githubusercontent.com/cbuijs/shallalist/master/spyware/domains
  id: 51
- enabled: true
  url: https://raw.githubusercontent.com/cbuijs/shallalist/master/tracker/domains
  name: https://raw.githubusercontent.com/cbuijs/shallalist/master/tracker/domains
  id: 52
- enabled: true
  url: https://raw.githubusercontent.com/CHEF-KOCH/Anti-Avast-Telemetry/master/HOSTS.txt
  name: https://raw.githubusercontent.com/CHEF-KOCH/Anti-Avast-Telemetry/master/HOSTS.txt
  id: 53
- enabled: true
  url: https://raw.githubusercontent.com/CHEF-KOCH/NSABlocklist/master/HOSTS/HOSTS
  name: https://raw.githubusercontent.com/CHEF-KOCH/NSABlocklist/master/HOSTS/HOSTS
  id: 54
- enabled: true
  url: https://raw.githubusercontent.com/CHEF-KOCH/PayWall-domains/master/HOSTS.txt
  name: https://raw.githubusercontent.com/CHEF-KOCH/PayWall-domains/master/HOSTS.txt
  id: 55
- enabled: true
  url: https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/extra.txt
  name: https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/extra.txt
  id: 56
- enabled: true
  url: https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy.txt
  name: https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy.txt
  id: 57
- enabled: true
  url: https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/update.txt
  name: https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/update.txt
  id: 58
- enabled: true
  url: https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Alternate%20versions%20Anti-Malware%20List/AntiMalwareHosts.txt
  name: https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Alternate%20versions%20Anti-Malware%20List/AntiMalwareHosts.txt
  id: 59
- enabled: true
  url: https://raw.githubusercontent.com/DandelionSprout/adfilt/master/GameConsoleAdblockList.txt
  name: https://raw.githubusercontent.com/DandelionSprout/adfilt/master/GameConsoleAdblockList.txt
  id: 60
- enabled: true
  url: https://raw.githubusercontent.com/Dawsey21/Lists/master/main-blacklist.txt
  name: https://raw.githubusercontent.com/Dawsey21/Lists/master/main-blacklist.txt
  id: 61
- enabled: true
  url: https://raw.githubusercontent.com/durablenapkin/scamblocklist/master/adguard.txt
  name: https://raw.githubusercontent.com/durablenapkin/scamblocklist/master/adguard.txt
  id: 62
- enabled: true
  url: https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Risk/hosts
  name: https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Risk/hosts
  id: 63
- enabled: true
  url: https://raw.githubusercontent.com/FadeMind/hosts.extras/master/UncheckyAds/hosts
  name: https://raw.githubusercontent.com/FadeMind/hosts.extras/master/UncheckyAds/hosts
  id: 64
- enabled: true
  url: https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/hosts.txt
  name: https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/hosts.txt
  id: 65
- enabled: true
  url: https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/nocoin.txt
  name: https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/nocoin.txt
  id: 66
- enabled: true
  url: https://raw.githubusercontent.com/Kees1958/W3C_annual_most_used_survey_blocklist/master/Top500
  name: https://raw.githubusercontent.com/Kees1958/W3C_annual_most_used_survey_blocklist/master/Top500
  id: 67
- enabled: true
  url: https://raw.githubusercontent.com/KurzGedanke/kurzBlock/master/kurzBlock.txt
  name: https://raw.githubusercontent.com/KurzGedanke/kurzBlock/master/kurzBlock.txt
  id: 68
- enabled: true
  url: https://raw.githubusercontent.com/matomo-org/referrer-spam-blacklist/master/spammers.txt
  name: https://raw.githubusercontent.com/matomo-org/referrer-spam-blacklist/master/spammers.txt
  id: 69
- enabled: true
  url: https://raw.githubusercontent.com/mitchellkrogza/The-Big-List-of-Hacked-Malware-Web-Sites/master/hacked-domains.list
  name: https://raw.githubusercontent.com/mitchellkrogza/The-Big-List-of-Hacked-Malware-Web-Sites/master/hacked-domains.list
  id: 70
- enabled: true
  url: https://raw.githubusercontent.com/mkb2091/blockconvert/master/output/hosts.txt
  name: https://raw.githubusercontent.com/mkb2091/blockconvert/master/output/hosts.txt
  id: 71
- enabled: true
  url: https://raw.githubusercontent.com/mmotti/adguard-home-filters/master/filters.txt
  name: https://raw.githubusercontent.com/mmotti/adguard-home-filters/master/filters.txt
  id: 72
- enabled: true
  url: https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/AmazonFireTV.txt
  name: https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/AmazonFireTV.txt
  id: 73
- enabled: true
  url: https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/android-tracking.txt
  name: https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/android-tracking.txt
  id: 74
- enabled: true
  url: https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/SmartTV-AGH.txt
  name: https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/SmartTV-AGH.txt
  id: 75
- enabled: true
  url: https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/SmartTV.txt
  name: https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/SmartTV.txt
  id: 76
- enabled: true
  url: https://raw.githubusercontent.com/pirat28/IHateTracker/master/iHateTracker.txt
  name: https://raw.githubusercontent.com/pirat28/IHateTracker/master/iHateTracker.txt
  id: 77
- enabled: true
  url: https://raw.githubusercontent.com/PolishFiltersTeam/KADhosts/master/KADhosts_without_controversies.txt
  name: https://raw.githubusercontent.com/PolishFiltersTeam/KADhosts/master/KADhosts_without_controversies.txt
  id: 78
- enabled: true
  url: https://raw.githubusercontent.com/PoorPocketsMcNewHold/steamscamsites/master/steamscamsite.txt
  name: https://raw.githubusercontent.com/PoorPocketsMcNewHold/steamscamsites/master/steamscamsite.txt
  id: 79
- enabled: true
  url: https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/Corona-Blocklist
  name: https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/Corona-Blocklist
  id: 80
- enabled: true
  url: https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/crypto
  name: https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/crypto
  id: 81
- enabled: true
  url: https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/Fake-Science
  name: https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/Fake-Science
  id: 82
- enabled: true
  url: https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/gambling
  name: https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/gambling
  id: 83
- enabled: true
  url: https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/malware
  name: https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/malware
  id: 84
- enabled: true
  url: https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/notserious
  name: https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/notserious
  id: 85
- enabled: true
  url: https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/Phishing-Angriffe
  name: https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/Phishing-Angriffe
  id: 86
- enabled: true
  url: https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/samsung
  name: https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/samsung
  id: 87
- enabled: true
  url: https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/spam.mails
  name: https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/spam.mails
  id: 88
- enabled: true
  url: https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/Streaming
  name: https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/Streaming
  id: 89
- enabled: true
  url: https://raw.githubusercontent.com/Spam404/lists/master/main-blacklist.txt
  name: https://raw.githubusercontent.com/Spam404/lists/master/main-blacklist.txt
  id: 90
- enabled: true
  url: https://raw.githubusercontent.com/StevenBlack/hosts/master/data/add.2o7Net/hosts
  name: https://raw.githubusercontent.com/StevenBlack/hosts/master/data/add.2o7Net/hosts
  id: 91
- enabled: true
  url: https://raw.githubusercontent.com/StevenBlack/hosts/master/data/add.Risk/hosts
  name: https://raw.githubusercontent.com/StevenBlack/hosts/master/data/add.Risk/hosts
  id: 92
- enabled: true
  url: https://raw.githubusercontent.com/StevenBlack/hosts/master/data/add.Spam/hosts
  name: https://raw.githubusercontent.com/StevenBlack/hosts/master/data/add.Spam/hosts
  id: 93
- enabled: true
  url: https://raw.githubusercontent.com/StevenBlack/hosts/master/data/KADhosts/hosts
  name: https://raw.githubusercontent.com/StevenBlack/hosts/master/data/KADhosts/hosts
  id: 94
- enabled: true
  url: https://raw.githubusercontent.com/StevenBlack/hosts/master/data/UncheckyAds/hosts
  name: https://raw.githubusercontent.com/StevenBlack/hosts/master/data/UncheckyAds/hosts
  id: 95
- enabled: true
  url: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
  name: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
  id: 96
- enabled: true
  url: https://raw.githubusercontent.com/vokins/yhosts/master/hosts
  name: https://raw.githubusercontent.com/vokins/yhosts/master/hosts
  id: 97
- enabled: true
  url: https://raw.githubusercontent.com/wlqY8gkVb9w1Ck5MVD4lBre9nWJez8/W10TelemetryBlocklist/master/W10TelemetryBlocklist
  name: https://raw.githubusercontent.com/wlqY8gkVb9w1Ck5MVD4lBre9nWJez8/W10TelemetryBlocklist/master/W10TelemetryBlocklist
  id: 98
- enabled: true
  url: https://reddestdream.github.io/Projects/MinimalHosts/etc/MinimalHostsBlocker/minimalhosts
  name: https://reddestdream.github.io/Projects/MinimalHosts/etc/MinimalHostsBlocker/minimalhosts
  id: 99
- enabled: true
  url: https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
  name: https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
  id: 100
- enabled: true
  url: https://s3.amazonaws.com/lists.disconnect.me/simple_malvertising.txt
  name: https://s3.amazonaws.com/lists.disconnect.me/simple_malvertising.txt
  id: 101
- enabled: true
  url: https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt
  name: https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt
  id: 102
- enabled: true
  url: https://someonewhocares.org/hosts/zero/hosts
  name: https://someonewhocares.org/hosts/zero/hosts
  id: 103
- enabled: true
  url: https://ssl.bblck.me/blacklists/hosts-file.txt
  name: https://ssl.bblck.me/blacklists/hosts-file.txt
  id: 104
- enabled: true
  url: https://sysctl.org/cameleon/hosts
  name: https://sysctl.org/cameleon/hosts
  id: 105
- enabled: true
  url: https://urlhaus.abuse.ch/downloads/hostfile/
  name: https://urlhaus.abuse.ch/downloads/hostfile/
  id: 106
- enabled: true
  url: https://v.firebog.net/hosts/BillStearns.txt
  name: https://v.firebog.net/hosts/BillStearns.txt
  id: 107
- enabled: true
  url: https://v.firebog.net/hosts/Easylist.txt
  name: https://v.firebog.net/hosts/Easylist.txt
  id: 108
- enabled: true
  url: https://v.firebog.net/hosts/Easyprivacy.txt
  name: https://v.firebog.net/hosts/Easyprivacy.txt
  id: 109
- enabled: true
  url: https://v.firebog.net/hosts/Prigent-Ads.txt
  name: https://v.firebog.net/hosts/Prigent-Ads.txt
  id: 110
- enabled: true
  url: https://v.firebog.net/hosts/Prigent-Malware.txt
  name: https://v.firebog.net/hosts/Prigent-Malware.txt
  id: 111
- enabled: true
  url: https://v.firebog.net/hosts/Prigent-Phishing.txt
  name: https://v.firebog.net/hosts/Prigent-Phishing.txt
  id: 112
- enabled: true
  url: https://v.firebog.net/hosts/Shalla-mal.txt
  name: https://v.firebog.net/hosts/Shalla-mal.txt
  id: 113
- enabled: true
  url: https://v.firebog.net/hosts/static/SamsungSmart.txt
  name: https://v.firebog.net/hosts/static/SamsungSmart.txt
  id: 114
- enabled: true
  url: https://v.firebog.net/hosts/static/w3kbl.txt
  name: https://v.firebog.net/hosts/static/w3kbl.txt
  id: 115
- enabled: true
  url: https://winhelp2002.mvps.org/hosts.txt
  name: https://winhelp2002.mvps.org/hosts.txt
  id: 116
- enabled: true
  url: https://www.github.developerdan.com/hosts/lists/ads-and-tracking-extended.txt
  name: https://www.github.developerdan.com/hosts/lists/ads-and-tracking-extended.txt
  id: 117
- enabled: true
  url: https://www.github.developerdan.com/hosts/lists/amp-hosts-extended.txt
  name: https://www.github.developerdan.com/hosts/lists/amp-hosts-extended.txt
  id: 118
- enabled: true
  url: https://www.github.developerdan.com/hosts/lists/tracking-aggressive-extended.txt
  name: https://www.github.developerdan.com/hosts/lists/tracking-aggressive-extended.txt
  id: 119
- enabled: true
  url: https://www.malwaredomainlist.com/hostslist/hosts.txt
  name: https://www.malwaredomainlist.com/hostslist/hosts.txt
  id: 120
- enabled: true
  url: https://zerodot1.gitlab.io/CoinBlockerLists/hosts_browser
  name: https://zerodot1.gitlab.io/CoinBlockerLists/hosts_browser
  id: 121
whitelist_filters: []
user_rules:
- [omitted]
- '@@||www.hcaptcha.com^$important'
- ""
dhcp:
  enabled: false
  interface_name: ""
  gateway_ip: ""
  subnet_mask: ""
  range_start: ""
  range_end: ""
  lease_duration: 86400
  icmp_timeout_msec: 1000
clients: []
log_compress: false
log_localtime: false
log_max_backups: 0
log_max_size: 100
log_max_age: 3
log_file: ""
verbose: false
schema_version: 6
```

</details>
