### ISSUE TITLE
Processing time is all over the place

### ISSUE THREAD

**Issue by Bluscream** [AdguardTeam/AdGuardHome#2107]
![image](https://user-images.githubusercontent.com/3318223/93350633-240ede80-f839-11ea-8e21-1c75466c7086.png)
![image](https://user-images.githubusercontent.com/3318223/93350747-43a60700-f839-11ea-82b5-3f945dd4c938.png)
```
blu@netguard:~ $ lsb_release -a
No LSB modules are available.
Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 10 (buster)
Release:        10
Codename:       buster
blu@netguard:~ $ uname -a
Linux netguard 5.4.51-v7+ #1333 SMP Mon Aug 10 16:45:19 BST 2020 armv7l GNU/Linux
blu@netguard:~/AdGuardHome $ ./AdGuardHome --version
AdGuard Home, version 0.103.3, channel release, arch linux arm v6
```

<details>
<summary>AdguardHome.yaml</summary>

```yaml
bind_host: 0.0.0.0
bind_port: 80
users:
- name: blu
  password: 
http_proxy: ""
language: ""
rlimit_nofile: 0
debug_pprof: false
web_session_ttl: 720
dns:
  bind_host: 0.0.0.0
  port: 53
  statistics_interval: 90
  querylog_enabled: true
  querylog_file_enabled: true
  querylog_interval: 7
  querylog_size_memory: 1000
  anonymize_client_ip: false
  protection_enabled: true
  blocking_mode: default
  blocking_ipv4: ""
  blocking_ipv6: ""
  blocked_response_ttl: 10
  parental_block_host: family-block.dns.adguard.com
  safebrowsing_block_host: standard-block.dns.adguard.com
  ratelimit: 20
  ratelimit_whitelist: []
  refuse_any: true
  upstream_dns:
  - https://dns10.quad9.net/dns-query
  bootstrap_dns:
  - 9.9.9.10
  - 149.112.112.10
  - 2620:fe::10
  - 2620:fe::fe:10
  all_servers: false
  fastest_addr: true
  allowed_clients: []
  disallowed_clients: []
  blocked_hosts: []
  cache_size: 4194304
  cache_ttl_min: 0
  cache_ttl_max: 0
  bogus_nxdomain: []
  aaaa_disabled: false
  enable_dnssec: false
  edns_client_subnet: true
  filtering_enabled: true
  filters_update_interval: 24
  parental_enabled: false
  safesearch_enabled: false
  safebrowsing_enabled: false
  safebrowsing_cache_size: 1048576
  safesearch_cache_size: 1048576
  parental_cache_size: 1048576
  cache_time: 30
  rewrites:
  - domain: blacklist.teamspeak.com
    answer: 0.0.0.0
  - domain: blacklist2.teamspeak.com
    answer: 0.0.0.0
  - domain: '*.wpad.fritz.box'
    answer: 0.0.0.0
  - domain: '*.wpad.box'
    answer: 0.0.0.0
  - domain: wpad.box
    answer: 0.0.0.0
  blocked_services:
  - mail_ru
  - tiktok
  - ok
  - vk
tls:
  enabled: false
  server_name: ""
  force_https: false
  port_https: 443
  port_dns_over_tls: 853
  allow_unencrypted_doh: false
  strict_sni_check: false
  certificate_chain: ""
  private_key: ""
  certificate_path: ""
  private_key_path: ""
filters:
- enabled: true
  url: https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt
  name: AdGuard DNS filter
  id: 1
- enabled: true
  url: https://adaway.org/hosts.txt
  name: AdAway
  id: 2
- enabled: true
  url: https://www.malwaredomainlist.com/hostslist/hosts.txt
  name: MalwareDomainList.com Hosts List
  id: 4
- enabled: true
  url: https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/nocoin.txt
  name: NoCoin Filter List
  id: 1600227713
- enabled: true
  url: https://raw.githubusercontent.com/mitchellkrogza/The-Big-List-of-Hacked-Malware-Web-Sites/master/hacked-domains.list
  name: The Big List of Hacked Malware Web Sites
  id: 1600227714
- enabled: true
  url: https://raw.githubusercontent.com/Spam404/lists/master/main-blacklist.txt
  name: Spam404
  id: 1600227715
- enabled: true
  url: https://raw.githubusercontent.com/durablenapkin/scamblocklist/master/adguard.txt
  name: Scam Blocklist by DurableNapkin
  id: 1600227716
- enabled: true
  url: https://raw.githubusercontent.com/DandelionSprout/adfilt/master/GameConsoleAdblockList.txt
  name: Game Console Adblock List
  id: 1600227717
- enabled: true
  url: https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/SmartTV-AGH.txt
  name: Perflyst and Dandelion Sprout's Smart-TV Blocklist
  id: 1600227718
- enabled: true
  url: https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/Win10Telemetry
  name: Win10Telemetry
  id: 1600227719
- enabled: true
  url: https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/notserious
  name: notserious
  id: 1600227720
- enabled: true
  url: https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/crypto
  name: crypto
  id: 1600227721
- enabled: true
  url: https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/spam.mails
  name: spam.mails
  id: 1600227722
- enabled: true
  url: https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/Phishing-Angriffe
  name: Phishing-Angriffe
  id: 1600227723
- enabled: true
  url: https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/malware
  name: malware
  id: 1600227724
- enabled: true
  url: https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/Fake-Science
  name: Fake-Science
  id: 1600227725
- enabled: true
  url: https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/samsung
  name: samsung
  id: 1600227726
whitelist_filters: []
user_rules:
- '||graph.oculus.com^$important'
- ""
dhcp:
  enabled: false
  interface_name: ""
  gateway_ip: ""
  subnet_mask: ""
  range_start: ""
  range_end: ""
  lease_duration: 86400
  icmp_timeout_msec: 1000
clients:
- name: XXX
  tags:
  - device_pc
  - os_windows
  - user_admin
  ids:
  - YYXX
  use_global_settings: true
  filtering_enabled: false
  parental_enabled: false
  safesearch_enabled: false
  safebrowsing_enabled: false
  use_global_blocked_services: true
  blocked_services: []
  upstreams: []
log_compress: false
log_localtime: false
log_max_backups: 0
log_max_size: 100
log_max_age: 3
log_file: ""
verbose: false
schema_version: 6

```

</details>
