### ISSUE TITLE
Snap 1052 cannot bind DHCP to network interface

### ISSUE THREAD

**Issue by marxjohnson** [AdguardTeam/AdGuardHome#2228]
### Issue Details

* **Version of AdGuard Home server:**
  * 0.104.0
* **How did you setup DNS configuration:**
  * System
* **Operating system and version:**
  * Ubuntu 18.04.5

### Expected Behavior
Before the snap refreshed (snap rev 606/adguard version 0.103.3), DHCP was enabled and working. After it updated, I expected it to continue working.

### Actual Behavior
DHCP stopped working after the refresh. Attempting to disable and re-enable the service resulted in the following error:
`Error: control/dhcp/set_config | Failed to start DHCP server: cannot bind to interface enp3s0: operation not permitted | 400`

**Comment by marxjohnson** [comment]
As a workaround until a fix is published, running `snap revert adguard-home` restored the previous version.

**Comment by Tloram** [comment]
Same issue here. DHCP stopped working over night when the snap updated to 0.104

Network is now down. Oh dear.

**Comment by ameshkov** [comment]
We're looking into it, don't worry.

Meanwhile, could you please post the `dhcp:` section of your config files? (`AdGuardHome.yaml`)

**Comment by marxjohnson** [comment]
Here is the `dchp` section of mine:
Snap rev 606 (working):
```
dhcp:
  enabled: true
  interface_name: enp3s0
  gateway_ip: 192.168.0.1
  subnet_mask: 255.255.255.0
  range_start: 192.168.0.50
  range_end: 192.168.0.150
  lease_duration: 86400
  icmp_timeout_msec: 1000
```

Snap rev 1052 (not working):
```
dhcp:
  enabled: true
  interface_name: enp3s0
  dhcpv4:
    gateway_ip: 192.168.0.1
    subnet_mask: 255.255.255.0
    range_start: 192.168.0.50
    range_end: 192.168.0.150
    lease_duration: 86400
    icmp_timeout_msec: 1000
    options: []
  dhcpv6:
    range_start: ""
    lease_duration: 86400
    ra_slaac_only: false
    ra_allow_slaac: false
```
