### ISSUE TITLE
DHCP options with multiple IPs

### ISSUE THREAD

**Issue by ainar-g** [AdguardTeam/AdGuardHome#2385]
<p><a href="https://github.com/AdguardTeam/AdGuardHome/issues/1708#issuecomment-736852712">Context</a>.</p>

<p>Currently,&#xA0;we have two option formats for&#xA0;our DHCP server:
the&#xA0;hex format (<code>1 hex abcd1234</code>) and&#xA0;the&#xA0;IP format
(<code>1 ip 127.0.0.1</code>).&#x2003;A&#xA0;common use for&#xA0;the&#xA0;second
format is setting custom DNS servers
with&#xA0;option&#xA0;6.&#x2003;But&#xA0;in&#xA0;many cases we want
at&#xA0;least two DNS addresses.&#x2003;So,&#xA0;we should either&#xA0;create
a&#xA0;new type of&#xA0;option (something
like&#xA0;<code>1 ips 127.0.0.1 127.0.0.2</code>), patch the&#xA0;IP option
to&#xA0;accept multiple IPs, or&#xA0;define rules for&#xA0;merging
options&#xA0;together.</p>

**Comment by ainar-g** [comment]
As of snapshot e6a8fe452c5 we have added the two new DHCP option types: `ips` and `text.`

@loll31, values for options `6` and `252`, which you were interested in, can now be spelled more clearly:

```yaml
# …
'dhcp':
  # …
  'dhcpv4':
    # …
    'options':
    - '6 ips 192.168.1.1,192.168.1.2'
    - '252 text socks://proxy.example.org'
```

We will soon update the Wiki as well.
