### ISSUE TITLE
$dnsrewrite rules should look like DNS rewrites in the query log

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardHome#2491]
Here's how they look like now:
https://uploads.adguard.com/up04_AdGuard_Home_mb7wq.png

We can reuse existing "rewritten" reason for that and no additional changes will be needed on the UI side.

**Comment by ainar-g** [comment]
Can you elaborate on at what stage you see the backend replacing the reason value?  If we do this from the very beginning, then this value will be persisted to query log, and if we later want the distinction back, it'll require a hard migration.

I personally am in favour of doing that on the UI.

**Comment by ameshkov** [comment]
I don't think this is the responsibility of the UI to take care of such things. There is a clear distinction between "Blocked", "Whitelisted/Allowed" and "Rewritten/Modified". We already do this for "Blocked" and "Whitelisted/Allowed", why would we not do this for rewrites?

**Comment by ainar-g** [comment]
I don't quite understand your reasoning there.  From what I can see, there isn't a “clear distinction”, but there are many different reasons:

```yaml
'reason':
  'type': 'string'
  'description': 'Request filtering status.'
  'enum':
  - 'NotFilteredNotFound'
  - 'NotFilteredWhiteList'
  - 'NotFilteredError'
  - 'FilteredBlackList'
  - 'FilteredSafeBrowsing'
  - 'FilteredParental'
  - 'FilteredInvalid'
  - 'FilteredSafeSearch'
  - 'FilteredBlockedService'
  - 'Rewrite'
  - 'RewriteEtcHosts'
  - 'DNSRewriteRule'
```

In fact, we already make a distinction between `Rewrite` and `RewriteEtcHosts`.  And the UI already merges them into one:

```js
[FILTERED_STATUS.REWRITE]: {
    LABEL: RESPONSE_FILTER.REWRITTEN.LABEL,
    COLOR: QUERY_STATUS_COLORS.BLUE,
},
[FILTERED_STATUS.REWRITE_HOSTS]: {
    LABEL: RESPONSE_FILTER.REWRITTEN.LABEL,
    COLOR: QUERY_STATUS_COLORS.BLUE,
},
```

We can discuss adding those three groups you mentioned—`Blocked`, `Allowed`, and `Rewritten`—in the v1 HTTP API, but for now that's just not the case.
