### ISSUE TITLE
DoH(DNS-over-https) is not available through the IP of bind_host in DNS settings.

### ISSUE THREAD

**Issue by parkkw472** [AdguardTeam/AdGuardHome#2914]
### Problem Description
DoH(DNS-over-https) is not available through the IP of bind_host in DNS settings.

```
bind_host: IP-1
bind_port: 80

~~(Omit)~~

dns:
  bind_host: IP-2

~~(Omit)~~

tls:
  enabled: true
  server_name: A Record Domain (point to IP-2)
  force_https: false
  port_https: 443
  port_dns_over_tls: 853
  port_dns_over_quic: 784
```
In the case of the above configuration, DoH cannot be used through the domain because the DoH port has not been opened for the domain pointing to IP-2, so DoH can only be used if the domain points to IP-1.

### Proposed Solution
The DoH server should also be opened with the bind_host IP in DNS settings.

### Additional Information
If you leave a comment for the lack of explanation, I will respond quickly.
