### ISSUE TITLE
local_domain_name: when set lost rewrites: from that domain

### ISSUE THREAD

**Issue by bcookatpcsd** [AdguardTeam/AdGuardHome#2983]
local defined dns record:

 - domain: option252.domain
    answer: 10.20.0.30

```
> drill option252.domain @10.20.0.53
> ;; ->>HEADER<<- opcode: QUERY, rcode: NXDOMAIN, id: 27792
> ;; flags: qr rd ra ; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 0 
> ;; QUESTION SECTION:
> ;; option252.domain.	IN	A
> 
> ;; ANSWER SECTION:
> 
> ;; AUTHORITY SECTION:
> option252.domain.	10	IN	SOA	fake-for-negative-caching.adguard.com. hostmaster.option252.domain. 100500 1800 900 604800 86400
> 
> ;; ADDITIONAL SECTION:
> 
> ;; Query time: 233 msec
> ;; SERVER: 10.20.0.53
> ;; WHEN: Mon Apr 19 12:35:52 2021
> ;; MSG SIZE  rcvd: 132
```

Also:

local_ptr_upstream not filled in.

- '[/20.10.in-addr.arpa/]172.16.254.241:53'
- '[/120.10.in-addr.arpa/]172.16.254.241:53'
- '[/16.172.in-addr.arpa/]172.16.254.241:53'

these entries did not get me PTR entries with local_domain_name filled in.  When I changed local_domain_name: back to lan and restarted.. I had static entries and ptr working again.. 

I also changed:

log_compress: true
log_localtime: true

**Comment by vrutkovs** [comment]
Reproducible in v0.106.3

**Comment by shawly** [comment]
I also got this issue with v0.106.3

As soon as I add lan.mydomain.net as local_domain_name I cannot resolve any local domains anymore.

**Comment by ainar-g** [comment]
@vrutkovs, @shawly, what upstreams did you put into the “Private reverse DNS servers” field?  Requests for names within `local_domain_name` are redirected there.

**Comment by bcookatpcsd** [comment]
Sorry to somewhat hijack this.. 

How does AGH know which domains to that are private.. 

What is the difference between the two sections? 

![image](https://user-images.githubusercontent.com/55087301/134911081-017ea63b-a2bd-4614-8e9b-3bdf04d7fc3a.png)


![image](https://user-images.githubusercontent.com/55087301/134911219-93015067-2ec6-42f7-ba0c-c95ff822504c.png)


and within my config file:

`
  local_domain_name: lan
  resolve_clients: true
  use_private_ptr_resolvers: true
  local_ptr_upstreams:
  - '[/20.10.in-addr.arpa/]172.16.254.241'
  - '[/16.172.in-addr.arpa/]172.16.254.241'
  - '[/120.10.in-addr.arpa/]172.16.254.241'
`

AdGuard Home, version v0.107.0-b.11

ptr resolution works as expected. 

But I forget the reasoning that things went in the bottom and not the top section.. to avoid queries to AG services? For the local recursion/speed? 

![image](https://user-images.githubusercontent.com/55087301/134911987-09686382-94ca-4260-8736-e014fcf75ff8.png)


Is everything in the top section sent to AG services for 'checking', if the choice is made to do so? 

github dnsproxy has no other documentation about the local_domain_section.. so assuming that is a AGH 'thing' and not a dnsproxy setting.. 

Thanks in advance..

**Comment by EugeneOne1** [comment]
@bcookatpcsd, AdGuard Home uses registries from [RFC-6303](https://datatracker.ietf.org/doc/html/rfc6303) to consider the address being private.  The upstream servers from **Private reverse DNS servers** field are used only to resolve the PTR requests for these addresses.

`local_domain_name` is only used to resolve the hostnames leased by AdGuard Home's DHCP server.  In fact these requests aren't sent to upstream at all.

Since the screenshot tells that default local resolvers couldn't be determined, I can assume, that the problem may be caused by this domain-specific configuration for **Private reverse DNS servers**.  Could you please try to leave it with only a single upstream `172.16.254.241`.

**Comment by bcookatpcsd** [comment]
in the config file:

```
  upstream_dns:
  - sdns://AgYAAAAAAAAACDkuOS45LjEwICoV9dastufAkBreTrvHQ7LM1IkDK0bhZC8Gk2gwASWKFGRuczEwLnF1YWQ5Lm5ldDo1MDUzCi9kbnMtcXVlcnk
  - '# quad9-doh-ip4-port5053-nofilter-pri'
  - sdns://AQcAAAAAAAAAEjQ1LjYzLjExMC4xODc6ODQ0MyCcjeRhPcJTsKhZ8iViALPd39CussG6SnprFT9z_1f03x0yLmRuc2NyeXB0LWNlcnQucGxhbjktbnMyLmNvbQ
  - '# dnscrypt cryptostorm plan9-ns2'
  - sdns://BAYAAAAAAAAAAAAeZG5zLXVuZmlsdGVyZWQuYWRndWFyZC5jb206Nzg0
  - '# adguard quic 784'
  - sdns://AgcAAAAAAAAADjE3Mi42Ny4xMzQuMTU3AA1kb2guY3J5cHRvLnN4Ci9kbnMtcXVlcnk
  - '# doh-crypto-sx'
  - '[/vlan10.dns/]192.168.10.105:531'
  - '[/vlan20.dns/]192.168.10.105:531'
  - '[/vlan172.dns/]192.168.10.105:531'

  bootstrap_dns:
  - 45.90.28.0

  local_domain_name: lan
  resolve_clients: true
  use_private_ptr_resolvers: true
  local_ptr_upstreams:
  - '[/168.192.in-addr.arpa/]192.168.10.105:531'


```

![image](https://user-images.githubusercontent.com/55087301/136798766-793246f4-ac31-4e17-91a6-138a9acd9f4f.png)

Not sure if this helps..
