### ISSUE TITLE
System Stops working After Reboot

### ISSUE THREAD

**Issue by jimmysofat6864** [AdguardTeam/AdGuardHome#3119]
### Issue Details

* **Version of AdGuard Home server:**
v0.106.2
* **How did you install AdGuard Home:**
Automated Install Method
* **How did you setup DNS configuration:**
Per Device Basis
* **If it's a router or IoT, please write device model:**
Raspberry Pi 2
* **CPU architecture:**
ARM
* **Operating system and version:**
Rasbian Latest

### Expected Behavior
Server works and DNS is resolved
### Actual Behavior
Web interface does not connect and I keep getting various errors as described below. Keep getting Failed to start AdGuard Home service: exit status 1 and Couldn't parse config file: yaml: line 29: could not find expected ':'

### Screenshots
![image](https://user-images.githubusercontent.com/69532417/117587956-6b522400-b0d5-11eb-981e-15fdf98174bc.png)
![image](https://user-images.githubusercontent.com/69532417/117587976-802eb780-b0d5-11eb-8a3c-21a3e3a0b7db.png)

### Configuration
```
bind_host: 0.0.0.0
bind_port: 80
beta_bind_port: 0
users:
- name: [REDACTED]
- password: [REDACTED]
auth_attempts: 5
block_auth_min: 15
http_proxy: ""
language: ""
rlimit_nofile: 0
debug_pprof: false
web_session_ttl: 720
dns:
  bind_hosts:
  - 0.0.0.0
  port: 53
  statistics_interval: 1
  querylog_enabled: true
  querylog_file_enabled: true
  querylog_interval: 90
  querylog_size_memory: 1000
  anonymize_client_ip: false
  protection_enabled: true
  blocking_mode: default
  blocking_ipv4: ""
  blocking_ipv6: ""
  blocked_response_ttl:30
  parental_block_host: family-block.dns.adguard.com
  safebrowsing_block_host: standard-block.dns.adguard.com
  ratelimit: 20
  ratelimit_whitelist: []
  refuse_any: true
  upstream_dns:
  - https://doh.opendns.com/dns-query
  - tls://dns.quad9.net
  - tls://dns.google
  - tls://1.1.1.1
  upstream_dns_file: ""
  bootstrap_dns:
  - 9.9.9.10
  - 149.112.112.10
  - 2620:fe::10
  - 2620:fe::fe:10
  - 208.67.222.222
  - 208.67.220.220
  - 2620:119:35::35
  - 2620:119:53::53
  all_servers: false
  fastest_addr: false
  allowed_clients: []
  disallowed_clients: []
  blocked_hosts:
  - version.bind
  - id.server
  - hostname.bind
  cache_size: 4194304
  cache_ttl_min: 0
  cache_ttl_max: 0
  bogus_nxdomain: []
  aaaa_disabled: false
  enable_dnssec: true
  edns_client_subnet: false
  max_goroutines: 300
  ipset: []
  filtering_enabled: true
  filters_update_interval: 24
  parental_enabled: false
  safesearch_enabled: false
  safebrowsing_enabled: true
  safebrowsing_cache_size: 1048576
  safesearch_cache_size: 1048576
  parental_cache_size: 1048576
  cache_time: 30
  rewrites: []
  blocked_services: []
  local_domain_name: lan
  resolve_clients: true
  local_ptr_upstreams: []
tls:
  enabled: false
  server_name: ""
  force_https: false
  port_https: 443
  port_dns_over_tls: 853
  port_dns_over_quic: 784
  port_dnscrypt: 0
  dnscrypt_config_file: ""
  allow_unencrypted_doh: false
  strict_sni_check: false
  certificate_chain: ""
  private_key: ""
  certificate_path: ""
  private_key_path: ""
filters:
- enabled: true
  url: https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt
  name: AdGuard DNS filter
  id: 1
- enabled: true
  url: https://adaway.org/hosts.txt
  name: AdAway Default Blocklist
  id: 2
- enabled: true
  url: https://pgl.yoyo.org/adservers/serverlist.php?hostformat=adblockplus&showintro=1&mimetype=plaintext
  name: Peter Lowe's List
  id: 1615417065
- enabled: true
  url: https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/hosts.txt
  name: NoCoin Filter List
  id: 1615417066
- enabled: true
  url: https://raw.githubusercontent.com/Spam404/lists/master/main-blacklist.txt
  name: Spam404
  id: 1615417067
- enabled: true
  url: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
  name: Steven Black
  id: 1615417068
- enabled: true
 url: https://block.energized.pro/basic/formats/hosts.txt
  name: Energized Basic
  id: 1615417069
- enabled: true
  url: https://dbl.oisd.nl/basic/
  name: OISD Basic
  id: 1615417071
- enabled: true
  url: https://www.github.developerdan.com/hosts/lists/ads-and-tracking-extended.txt
  name: Developer Dan
  id: 1615417072
whitelist_filters: []
user_rules:
- '@@||sdx.xfinity.com^$important'
- '@@||filters.adtidy.org^$important'
- '@@||s.youtube.com^$important'
- '@@||video-stats.l.google.com^$important'
- '@@||alb.reddit.com^'
- '@@||click.redditmail.com^'
dhcp:
  enabled: false
  interface_name: ""
  dhcpv4:
    gateway_ip: ""
    subnet_mask: ""
    range_start: ""
    range_end: ""
    lease_duration: 86400
    icmp_timeout_msec: 1000
    options: []
  dhcpv6:
    range_start: ""
    lease_duration: 86400
    ra_slaac_only: false
    ra_allow_slaac: false
clients: []
log_compress: false
log_localtime: false
log_max_backups: 0
log_max_size: 100
log_max_age: 3
log_file: ""
verbose: false
schema_version: 10
```
