### ISSUE TITLE
Adguard installed in LXD container not starting every time after reboot

### ISSUE THREAD

**Issue by xiki808** [AdguardTeam/AdGuardHome#3602]
### Issue Details

I have a script that creates a container and installs AdGuard Home in the container. Once done, I change my router’s DNS IP to that of my host and reboot the host system.

Generally I have internet after reboot is done, but I have noticed that this is not happening all the time. Some times I reboot and it seems like the DNS is not working, and in fact I have no connection to the internet.

If I reboot again, I might or might not have a connection to the internet. What I noticed is that when I don’t have internet, and restart the DNS container, internet comes back up. So all it takes is a container restart to get it back to working. I would like to avoid this and have DNS and internet immediately once the machine has rebooted.

Anyone had a similar scenario? Any help how I can debug this? I’m at a loss, I’ve spent a whole week trying to different scenarios and restarting the system and sometimes I still have no connection to the internet.

### Additional Information
1. System running rasbian lite and container running debian/11/armhf

2.  When I don't have connection, the container is running, has an IP and also adguard status shows that it is running.

3. Ports forwarded for the DNS container:
```
proxy53T:
    connect: tcp:127.0.0.1:53
    listen: tcp:10.0.0.4:53
    type: proxy
  proxy53U:
    connect: udp:127.0.0.1:53
    listen: udp:10.0.0.4:53
    type: proxy
  proxy80:
    connect: tcp:127.0.0.1:80
    listen: tcp:10.0.0.4:80
    type: proxy
  proxy443:
    connect: tcp:127.0.0.1:443
    listen: tcp:10.0.0.4:443
    type: proxy
  proxy3000:
    connect: tcp:127.0.0.1:3000
    listen: tcp:10.0.0.4:3000
    type: proxy
  proxy8080:
    connect: tcp:127.0.0.1:8080
    listen: tcp:10.0.0.4:10301
    type: proxy
  proxy51820:
    connect: udp:127.0.0.1:51820
    listen: udp:10.0.0.4:51820
    type: proxy
```
