### ISSUE TITLE
DHCP server check failed

### ISSUE THREAD

**Issue by fonlan** [AdguardTeam/AdGuardHome#3615]
### Issue Details

* **Version of AdGuard Home server:**
  * v0.107.0-b.11
* **How did you install AdGuard Home:**
  * Automated install script
* **How did you setup DNS configuration:**
  * Standalone linux running ADH
* **If it's a router or IoT, please write device model:**
  * Ubuntu in ESXi
* **CPU architecture:**
  * AMD64
* **Operating system and version:**
  * Ubuntu 18.04.5 LTS

### Expected Behavior
No other DHCP server and "Enable DHCP server" button be clickable

### Actual Behavior
Show error message as below screenshot

### Screenshots
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/7898348/133714096-5413f1fb-7587-4a86-84df-6245275df15c.png)

</details>

### Additional Information
System running ADH is a Ubuntu with only one network interface. And it's static address.

**Comment by fonlan** [comment]
Below is the configuration for ens160 NIC. It's static ip address.
![image](https://user-images.githubusercontent.com/7898348/134270555-a8798a8f-1cb5-41e3-ae6a-b43aed4cc0f5.png)
![image](https://user-images.githubusercontent.com/7898348/134270721-b67973ef-eb26-4d61-be3a-412c624f6f46.png)

**Comment by EugeneOne1** [comment]
@fonlan, thanks!  To ensure the problem source, could you please also [collect verbose log](https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog) for us?  You may either post it here or send to devteam@adguard.com.

In short, the issue may be related to AdGuard Home's static IP detection mechanism which doesn't cover all the possible network configuration ways among different Linuxes, Netplan in particular.  We've filled issue #3640 about that.  However, it would be really helpful for us to look at the contents of `/etc/network` directory on your machine.

As a temporary workaround, you may configure and enable the DHCP server via `dhcp` section of `AdGuardHome.yaml` configuration file.  By default for this installation method it should be located in `/opt/AdGuardHome` directory.  Don't forget to stop AdGuard Home before modifying it.  The configuration in your case should be something like this:

```yaml
dhcp:
  enabled: true
  interface_name: "ens160"
  dhcpv4:
    gateway_ip: 192.168.123.1
    subnet_mask: 255.255.255.0
    range_start: 192.168.123.100
    range_end: 192.168.123.200
    lease_duration: 86400
    icmp_timeout_msec: 1000
    options: []
  dhcpv6:
    range_start: ""
    lease_duration: 86400
    ra_slaac_only: false
    ra_allow_slaac: false
```
