### ISSUE TITLE
yaml config file not applied

### ISSUE THREAD

**Issue by trhdon123** [AdguardTeam/AdGuardHome#381]
### Steps to reproduce

1. Open AdGuardHome.yaml
2. Set bind_port: xxxx (I set 8888)
3. Set coredns > port: yyyy (> 1024). I set 1025.
4. Save changes.
5. Launch from root directory. Example: `/home/username/.AdGuardHome/AdGuardHome`

### Expected behavior

Console logs message telling OK.
### Actual behavior

Console logs message as following:
```
2018/10/17 23:34:04 AdGuard Home web interface backend, version v0.9
main.renameOldConfigIfNeccessary(): File /home/username/.AdGuardHome/AdguardDNS.yaml doesn't exist, nothing to do
main.askUsernamePasswordIfPossible(): File /home/username/.AdGuardHome/AdGuardHome.yaml exists, won't ask for password
2018/10/17 23:34:04 Reading YAML file: /home/username/.AdGuardHome/AdGuardHome.yaml
2018/10/17 23:34:04 Writing YAML file: /home/username/.AdGuardHome/AdGuardHome.yaml
2018/10/17 23:34:04 Writing DNS config: /home/username/.AdGuardHome/Corefile
2018/10/17 23:34:04 Writing filter file: /home/username/.AdGuardHome/dnsfilter.txt
2018/10/17 23:34:04 Go to http://127.0.0.1:8888
2018/10/17 23:34:04 listen tcp :53: bind: permission denied
```

<details><summary>Screenshot:</summary>

**Fail** (launch from root directory):
![screenshot from 2018-10-17 23-44-19](https://user-images.githubusercontent.com/20873969/47102613-60a9b800-d267-11e8-93ce-459b63adaf88.jpg)
**Success** (launch right from folder):
![screenshot from 2018-10-17 23-52-21](https://user-images.githubusercontent.com/20873969/47102854-ffceaf80-d267-11e8-91f8-ffd96ace1f96.jpg)
</details>

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| Version of AdGuard Home server:| 0.9
| How did you setup DNS configuration:| (System/Router/IoT) set DNS IPv4: 1.1.1.1, 8.8.8.8 through built-in Settings
| If it's a router or IoT, please write device model:| none
| Operating system and version:| Elementary 5.0 (Ubuntu 18.04 based)

**Comment by ameshkov** [comment]
Hi! Could it be that AdGuardHome was already running when you were editing the config file? It needs to be stop at that moment.

**Comment by hmage** [comment]
@trhdon123 

Hi.

It saves config file in same directory the binary is located, this is to protect against situations where users unknowingly run it from their home folder (as seen in neighbouring issue). Did you try editing `/home/username/.AdGuardHome/AdGuardHome.yaml` instead?

**Comment by trhdon123** [comment]
I surely did stop AGH before every new try.
Sorry I used `/AdguardHome/AdGuardHome` just to simplified. Actually placed everything in  `.AdGuardHome` folder and scripts did call to the right directory.

**Comment by hmage** [comment]
Hmm. Can you show me contents of `/home/username/.AdGuardHome/Corefile`? Would be greatly appreciated.

**Comment by trhdon123** [comment]
Here you are
![screenshot from 2018-10-18 00-12-22](https://user-images.githubusercontent.com/20873969/47103975-93a17b00-d26a-11e8-9e42-364ee584b2bc.png)

**Comment by hmage** [comment]
@trhdon123 that's not contents 😆 

Can you send me *contents* of both files I mentioned above? Attach them or quote them using ```, they're not big.

**Comment by trhdon123** [comment]
Sorrrry it's bed time here I took my eyes some elsewhere reading your reply :(
Corefile:
```
.:1025 {
    dnsfilter dnsfilter.txt {
        safebrowsing
        querylog
        blocked_ttl 10
    }
    hosts {
        fallthrough
    }
    forward . tls://1.1.1.1 tls://1.0.0.1
    cache
    prometheus :9153
}
```
yaml:
```
bind_host: 127.0.0.1
bind_port: 8888
auth_name: ""
auth_pass: ""
coredns:
  port: 1025
  protection_enabled: true
  filtering_enabled: true
  safebrowsing_enabled: true
  safesearch_enabled: false
  parental_enabled: false
  parental_sensitivity: 0
  blocked_response_ttl: 10
  querylog_enabled: true
  upstream_dns:
  - tls://1.1.1.1
  - tls://1.0.0.1
filters:
- url: https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt
  name: AdGuard Simplified Domain Names filter
  enabled: true
- url: https://cdn.rawgit.com/NanoAdblocker/NanoFilters/master/NanoMirror/NanoDefender.txt
  name: Nano Defender Integration
  enabled: true
- url: https://cdn.rawgit.com/NanoAdblocker/NanoFilters/master/NanoFilters/NanoBase.txt
  name: Nano filters
  enabled: true
- url: https://cdn.rawgit.com/NanoAdblocker/NanoFilters/master/NanoFilters/NanoWhitelist.txt
  name: Nano filters - Whitelist
  enabled: true
- url: https://raw.githubusercontent.com/StevenBlack/hosts/master/data/StevenBlack/hosts
  name: StevenBlack
  enabled: true
- url: https://easylist.to/easylist/easylist.txt
  name: EasyList
  enabled: true
- url: https://easylist-downloads.adblockplus.org/antiadblockfilters.txt
  name: Adblock Warning Removal List
  enabled: true
- url: https://easylist.to/easylist/fanboy-annoyance.txt
  name: Fanboy's Annoyance List
  enabled: true
- url: https://abpvn.com/filter/abpvn-gBcoLm.txt
  name: ABPVN List [vnexpress.net]
  enabled: true
user_rules: []
```
