### ISSUE TITLE
AdGuardHome 0.107.2 error in handling tcp: reading msg: reading len: read tcp: i/o timeout

### ISSUE THREAD

**Issue by grzesiczek1** [AdguardTeam/AdGuardHome#4128]
### Issue Details

* **Version of AdGuard Home server:**
  * v0.107.2 
* **How did you install AdGuard Home:**
  * Docker 
* **How did you setup DNS configuration:**
  * System 
* **If it's a router or IoT, please write device model:**
  * Raspberry Pi 4
* **CPU architecture:**
  * ARM 
* **Operating system and version:**
  * Raspbian 11 

### Expected Behavior
No error in the error log

### Actual Behavior
Error log flooded with following events:
2022/01/12 04:30:06.582567 [error] handling tcp: reading msg: reading len: read tcp x.x.x.x:853->x.x.x.x:36114: i/o timeout

### Screenshots
<details><summary>Screenshot:</summary>

![AGH error example](https://user-images.githubusercontent.com/58589583/149147523-86aee3de-5023-4ff5-adee-9869fde0f64c.png)

</details>

**Comment by seanob86** [comment]
I too have the same error events in similar setup as OP. AdGuard Home 0.107.2 in docker container. Appears events only occur while clients are connecting via DoT to the the server.

**Comment by sturmstar** [comment]
I observed exactly the same - only when clients connecting via DoT

**Comment by grzesiczek1** [comment]
I can add that this is visible for both IPv4 and IPv6 addresses with exactly same output.

**Comment by ainar-g** [comment]
Hello.  Those looks like either the client connection was improperly closed or the client just didn't respond.

@ameshkov, how about hiding timeout errors from `dnsproxy` behind the `debug` level?

**Comment by sturmstar** [comment]
Hi. In my case DoT is fully working (for the client) - it's just the anoying log

**Comment by ainar-g** [comment]
@grzesiczek1, @sturmstar, the newest release on the `edge` channel should include the fix for the issue.  Could you please check if the error messages are gone for you?  Thanks.

**Comment by sturmstar** [comment]
Hi! Issue is gone with edge channel - perfect - thank you very much

**Comment by zbulb** [comment]
Encountered this issue in v0.107.3

**Comment by ainar-g** [comment]
@zbulb, thanks for the info!  We'll fix it in v0.107.4.

**Comment by dnomd343** [comment]
This problem still seems to exist in `v0.107.14` of docker environment.

![image](https://user-images.githubusercontent.com/54678581/193810059-610ec3ac-a07b-4417-bc2b-80f1fd42cb68.png)

**Comment by ameshkov** [comment]
@dnomd343 this one seems different, it cannot verify the upstream certificate.

**Comment by dnomd343** [comment]
My AdGuardHome is running on the intranet, its upstream is not DoT or DoH, I suspect the problem comes from the enabled DoH service.

```
bind_host: 0.0.0.0
bind_port: 80
beta_bind_port: 0
users:
  - name: dnomd343
    password: $2a$10$CWm1blOqFpV1/xN7m32mQeRrCQFIxy4ZXB7DnxiyT5IX3qBHXkTQ2
auth_attempts: 5
block_auth_min: 15
http_proxy: ""
language: zh-cn
debug_pprof: false
web_session_ttl: 720
dns:
  bind_hosts:
    - 0.0.0.0
  port: 53
  statistics_interval: 30
  querylog_enabled: true
  querylog_file_enabled: true
  querylog_interval: 720h
  querylog_size_memory: 1000
  anonymize_client_ip: false
  protection_enabled: true
  blocking_mode: default
  blocking_ipv4: ""
  blocking_ipv6: ""
  blocked_response_ttl: 10
  parental_block_host: family-block.dns.adguard.com
  safebrowsing_block_host: standard-block.dns.adguard.com
  ratelimit: 0
  ratelimit_whitelist: []
  refuse_any: true
  upstream_dns:
    - 127.0.0.1:5353
  upstream_dns_file: ""
  bootstrap_dns:
    - 9.9.9.10
    - 149.112.112.10
    - 2620:fe::10
    - 2620:fe::fe:10
  all_servers: false
  fastest_addr: false
  fastest_timeout: 1s
  allowed_clients: []
  disallowed_clients: []
  blocked_hosts:
    - version.bind
    - id.server
    - hostname.bind
  trusted_proxies:
    - 127.0.0.0/8
    - ::1/128
  cache_size: 16777216
  cache_ttl_min: 60
  cache_ttl_max: 518400
  cache_optimistic: true
  bogus_nxdomain: []
  aaaa_disabled: false
  enable_dnssec: true
  edns_client_subnet: false
  max_goroutines: 300
  handle_ddr: true
  ipset: []
  ipset_file: ""
  filtering_enabled: true
  filters_update_interval: 24
  parental_enabled: false
  safesearch_enabled: false
  safebrowsing_enabled: false
  safebrowsing_cache_size: 1048576
  safesearch_cache_size: 1048576
  parental_cache_size: 1048576
  cache_time: 30
  rewrites:
    - domain: dns.343.re
      answer: 8.210.148.24
    - domain: dns.scutbot.cn
      answer: 106.55.62.186
    - domain: dns.scutrobot.com
      answer: 119.28.88.230
    - domain: nps.dnomd343.top
      answer: 8.210.148.24
    - domain: '*.scut.343.re'
      answer: 192.168.2.34
    - domain: dns.scut.343.re
      answer: 192.168.2.3
  blocked_services: []
  upstream_timeout: 10s
  private_networks: []
  use_private_ptr_resolvers: true
  local_ptr_upstreams: []
tls:
  enabled: true
  server_name: dns.scut.343.re
  force_https: false
  port_https: 443
  port_dns_over_tls: 853
  port_dns_over_quic: 784
  port_dnscrypt: 0
  dnscrypt_config_file: ""
  allow_unencrypted_doh: false
  strict_sni_check: false
  certificate_chain: ""
  private_key: ""
  certificate_path: /etc/ssl/certs/scut.343.re/fullchain.pem
  private_key_path: /etc/ssl/certs/scut.343.re/privkey.pem
filters:
  - enabled: true
    url: https://res.343.re/Share/Adblock-Rules/xinggsf.txt
    name: 乘风规则
    id: 1646875485
  - enabled: true
    url: https://adaway.org/hosts.txt
    name: AdAway
    id: 1646875486
  - enabled: true
    url: https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt
    name: AdGuard
    id: 1646875487
  - enabled: true
    url: https://anti-ad.net/easylist.txt
    name: Anti AD
    id: 1646875488
whitelist_filters: []
user_rules:
  - ""
dhcp:
  enabled: false
  interface_name: ""
  local_domain_name: lan
  dhcpv4:
    gateway_ip: ""
    subnet_mask: ""
    range_start: ""
    range_end: ""
    lease_duration: 86400
    icmp_timeout_msec: 1000
    options: []
  dhcpv6:
    range_start: ""
    lease_duration: 86400
    ra_slaac_only: false
    ra_allow_slaac: false
clients:
  runtime_sources:
    whois: true
    arp: true
    rdns: true
    dhcp: true
    hosts: true
  persistent: []
log_file: ""
log_max_backups: 0
log_max_size: 100
log_max_age: 3
log_compress: false
log_localtime: false
verbose: false
os:
  group: ""
  user: ""
  rlimit_nofile: 0
schema_version: 14
```

I will try to turn off the external encrypted DNS service and see if the problem still occurs.
