### ISSUE TITLE
adguard + traefik + docker  DOH not working DOT working file

### ISSUE THREAD

**Issue by sakearzoo** [AdguardTeam/AdGuardHome#4135]
Hi, This is my docker compose file for adguard . After this DOT working file at port 853 (android private dns) but whenever i am trying with chrome browser use secure DNS . I am getting error _"Please verify that this is a valid provider or try again later"_ . i have tried adding adding certs to adguard then also not working. Any idea how to fix this ?

```
version: '3.7'

services:
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - prox 
    volumes:
      - ./data:/opt/adguardhome/work
      - /conf:/opt/adguardhome/conf
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=prox"

    # https
      - "traefik.http.routers.adguardhome-secure.rule=Host(`mydomain.tld`)"
      - "traefik.http.routers.adguardhome-secure.entrypoints=https"
   #   - "traefik.http.services.adguardhome.loadbalancer.server.scheme=https"
      - "traefik.http.services.adguardhome.loadbalancer.server.port=80" #tried with port 443 still getting error
      - "traefik.http.routers.adguardhome-secure.tls=true"
      - "traefik.http.routers.adguardhome-secure.service=adguardhome"
      - "traefik.http.services.adguardhome.loadbalancer.passhostheader=true"
          
      # DNS-over-TLS 
      - "traefik.tcp.routers.adguard-dot.rule=HostSNI(`mydomain.tld`)"
      - "traefik.tcp.routers.adguard-dot.entrypoints=dnsovertls"
      - "traefik.tcp.routers.adguard-dot.tls=true"
      - "traefik.tcp.routers.adguard-dot.service=adguardhome"
      - "traefik.tcp.services.adguardhome.loadbalancer.server.port=53"
 
networks:
  prox:
    external: true
```

Is there any way to fix the issue with chrome i.e _Please verify that this is a valid provider or try again later_ ?
