### ISSUE TITLE
Problem running with Traefik and dhcp-relay

### ISSUE THREAD

**Issue by FlorentLM** [AdguardTeam/AdGuardHome#4194]
### Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * v0.107.2
* **How did you install AdGuard Home:**
  * Docker
* **How did you setup DNS configuration:**
  * Using Adguard's DHCP
* **If it's a router or IoT, please write device model:**
  * Raspberry Pi 4
* **CPU architecture:**
  * armv7
* **Operating system and version:**
  * Raspbian 11 bullseye

### Expected Behavior
I would like to use Adguard's DHCP because my router does not allow setting custom DNS servers. I would like to run Adguard behind Traefik, which means I have to use a dhcp-relay in order to have the DHCP exposed on the machine's host network.

### Actual Behavior
I can successfully use DHCP-bridge to give my devices DHCP, but they receive a wrong DNS IP: they get the 10.0.0.10 IP that I defined for the bridge network between Adguard and dhcp-relay. Thus the clients have no internet access (local access works though).

I found a related issue for Pihole here: https://discourse.pi-hole.net/t/dhcp-with-docker-compose-and-bridge-networking/17038
And the fix is to apply `dhcp-option=option:dns-server,x.x.x.x` to dnsmasq, where x.x.x.x would stand for the actual IP of my Pi on the network (192.168.x.x), right?

How can I do this with Adguard?

Thanks!

### Additional Information
My docker-compose:

```
version: "3.3"

services:

  dhcp-relay:
    image: modem7/dhcprelay:latest
    container_name: dhcp-relay
    command: ["-id", "wlan0", "-iu", "br_adguard", "10.0.0.10"]
    cap_add:
      - NET_ADMIN
    network_mode: host
    mem_limit: 20m
    mem_reservation: 5m

  adguard:
    image: adguard/adguardhome
    container_name: adguard
    networks:
      default:
        ipv4_address: 10.0.0.10
      traefiknet:
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 784:784/udp
      - 853:853/tcp
      - 67:67/udp
#      - 68:68/udp
#      - 68:68/tcp
#      - 3000:3000/tcp
#      - 80:80/tcp
#      - 443:443/tcp
    dns:
      - 127.0.0.1
      - 1.1.1.1
    volumes:
      - ./data:/opt/adguardhome/work
      - ./config:/opt/adguardhome/conf
    labels:
      - traefik.enable=true
      - traefik.http.services.adguard.loadbalancer.server.port=2999
      - traefik.http.routers.adguard.rule=Host(`adguard.xxxx.local`)
      - "traefik.http.routers.adguard.entrypoints=web"
      - "traefik.http.routers.adguard.service=adguard@docker"
      - "traefik.http.services.adguard.loadbalancer.server.scheme=http"

networks:
  traefiknet:
    external: true
  default:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br_adguard
    ipam:
      config:
        - subnet: 10.0.0.0/24
```
