### ISSUE TITLE
Port 53 already in use

### ISSUE THREAD

**Issue by b3nd1k** [AdguardTeam/AdGuardHome#4283]
Hey! I'm trying to get AdGuard Home running on Docker with Portainer using the following stack. 

```
---
version: "2"
services:
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    networks:
      - milkyway
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 67:67/udp
      - 68:68/tcp
      - 68:68/udp
      - 853:853/tcp
      - 81:80/tcp #change this to something like 81:80 if port 80 is already in use
      - 3000:3000/tcp
    volumes:
      - /mnt/volume/appdata/adguard/workdir:/opt/adguardhome/work
      - /mnt/volume/appdata/adguard/confdir:/opt/adguardhome/conf
    restart: unless-stopped
networks:
  milkyway:
    external: true
```

However, when I try to deploy the stack, I get the following error. However, as far as I can tell, there shouldn't be anything else running on port 53. Any idea what I can do? 
<img width="316" alt="Screenshot 2022-02-12 at 17 15 10" src="https://user-images.githubusercontent.com/96381857/153719083-b2fdca03-2d54-4025-8bfd-12c2e80f0701.png">
