### ISSUE TITLE
Clients not being identified using DoT

### ISSUE THREAD

**Issue by accountForIssues** [AdguardTeam/AdGuardHome#4288]
Using `adguardhome:edge` from docker as of issue creation.

### Issue Details

I added persistent clients and then I added the client ids to the access list. DoH works fine, identifies clients and returns dns. DoT on the other end rejects all queries.

I use Caddy as reverse proxy but only for DoH. DoT is directly connected via the default port. So,

DoH -> Caddy -> AGH
DoT -> AGH

DoT works fine if I remove the client IDs from the access list.

AGH is served on `dns.domain.tld`. I add `testclient` as client ID in persistent clients.

### Expected Behavior

A request to `tls://testclient.domain.tld` should be recognized as a DoT request from `testclient`.

### Actual Behavior

DoT request from `tls://testclient.domain.tld` is dropped.

Relevant part of debug log:
`[debug] client __REDACTED_IP__ (id "") is not in access allowlist`

So, it looks like the client id is being dropped from the DoT url. If the access list is empty, everything works as usual.

Adguard tls settings
```
tls:
  enabled: true
  server_name: dns.domain.tld
  force_https: false
  port_https: 443
  port_dns_over_tls: 853
  port_dns_over_quic: 0
  port_dnscrypt: 0
  dnscrypt_config_file: ""
  allow_unencrypted_doh: true
  strict_sni_check: false
  certificate_chain: ""
  private_key: ""
  certificate_path: certs/wildcard_.domain.tld.crt
  private_key_path: certs/wildcard_.domain.tld.key
```

The TLS cert is valid for *.domain.tld

Am I missing something simple ? Why is the id part being dropped from the DoT url ?
