### ISSUE TITLE
Adguard DHCP serveur not working

### ISSUE THREAD

**Issue by gamersalpha** [AdguardTeam/AdGuardHome#4430]
### Prerequisites

- [X ] I am running the latest version
- [ X] I checked the documentation and found no answer
- [ ]X I checked to make sure that this issue has not already been filed

### Issue Details
* **Version of AdGuard Home server:**
  * version:  v0.107.5
* **How did you install AdGuard Home:**
  * script install
* **How did you setup DNS configuration:**
  * i want use the dhcp from adguard to push the dns on my network
* **If it's a router or IoT, please write device model:**
  * Proxmox virtual machine
* **CPU architecture:**
  * CORE I5
* **Operating system and version:**
  * Ubuntu 20.04 LTS

### Expected Behavior
I want start the dhcp serveur on Adguard 👍 
![image](https://user-images.githubusercontent.com/32466950/160235774-b09e4c9b-3f94-4301-8bcd-c0dd0e1794af.png)

First i try to detect if an dhcp serveur are On on my network and i got this error : 
![image](https://user-images.githubusercontent.com/32466950/160235839-aa206d04-af5f-4c8f-9f8b-5324f07db103.png)

ok so i look my network config files on my server i got this : 

```
network:
    ethernets:
        ens18:
            addresses: [192.168.1.6/24]
            gateway4: 192.168.1.1
            nameservers:
                addresses: [192.168.1.1]
    version: 2
```

but when i try to connect a computer nothing happenning

### Actual Behavior

The dhcp of adguard don't  add dhcp  to my client

### Screenshots

<details><summary>Screenshot:</summary>

No way to get an ip :
![image](https://user-images.githubusercontent.com/32466950/160235958-c7ed4bfa-0e54-4f2e-9122-2e99302e8a22.png)

</details>

### Additional Information

How make the dhcp works on my network with adguard please
