### ISSUE TITLE
Memory leak and device crash

### ISSUE THREAD

**Issue by timkgh** [AdguardTeam/AdGuardHome#4437]
### Issue Details

* **Version of AdGuard Home server:**
  * v0.107.5
* **How did you install AdGuard Home:**
  * GitHub releases
* **How did you setup DNS configuration:**
  * router
* **If it's a router or IoT, please write device model:**
  * Ubiquiti  EdgeRouter ER-12, EdgeOS
* **CPU architecture:**
  * mips64_softfloat (Cavium Octeon III V0.2  FPU V0.0)
* **Operating system and version:**
  * EdgeOS v2.0.9-hotfix.2

### Expected Behavior
Run for long periods of time without crashes/memory leak.

### Actual Behavior
Leaks memory until the router is out of memory and it crashes.

### Screenshots

After about 26 days of uptime:

![agh1](https://user-images.githubusercontent.com/23507658/160289629-6bf188d5-25be-4b09-a632-3fd7150b9dbd.jpg)

After the screenshot above, I restarted AGH and it shows a reasonable memory footprint:

![agh2](https://user-images.githubusercontent.com/23507658/160289635-e88b869c-744c-4bb2-a05e-6b2658f76fb2.jpg)

You can see the memory use on the device drops from 456M to 177M after an AGH restart, but it continues to climb until it eventually exhausts the entire device memory.

### Additional Information

Cache settings:
```
cache_size: 4194304
cache_ttl_min: 300
cache_ttl_max: 86400
cache_optimistic: true
safebrowsing_cache_size: 1048576
safesearch_cache_size: 1048576
parental_cache_size: 1048576
cache_time: 30
```

Clearing the stats and logs while AGH is running does not help reclaim memory, only an AGH restart does.

**Comment by EugeneOne1** [comment]
@timkgh, hello and apologies for a late response.   Unfortunally, we can't reproduce the issue on our test machines.  Could you please answer a couple of questions:

 1. How many filter lists do you use?  How many rules in total?
 1. What value of `querylog_size_memory` (section `dns`) is set in `AdGuardHome.yaml` file?

Also could you please collect some profiling info to enrich the issue details?  Here is how to perform it:

 1. Set `debug_pprof` in `AdGuardHome.yaml` to `true`.  This will enable some profiling HTTP endpoints for localhost (`127.0.0.1`);
 1. Then, run AGH for some time.  A few minutes should be enough;
 1. Next, fetch the `http://127.0.0.1:6060/debug/pprof/heap` and save it to the text file;
 1. Finally, send the resulting file to devteam@adguard.com with the subject like "Issue #4437".

Sorry for a bit complicated request.  Thanks.

**Comment by timkgh** [comment]
I believe it's a cache issue. I've been running it with:
```
cache_size: 0
cache_optimistic: false
```
for a few days now and it's stable, the memory use does not creep up.

I don't think the cache limit of 4M from my previous config is being enforced, it appears that the cache grows unbounded.

<img width="905" alt="image" src="https://user-images.githubusercontent.com/23507658/161284517-8e6a383e-0f3c-44d2-9d50-b6f8b43d46ce.png">

As for your other question, I don't run lots of filters, just filters from the built-in lists:
```
filters:
- enabled: true
  url: https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt
  name: AdGuard DNS filter
  id: 1
- enabled: true
  url: https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/hosts.txt
  name: NoCoin Filter List
  id: 1634786883
- enabled: true
  url: https://raw.githubusercontent.com/durablenapkin/scamblocklist/master/adguard.txt
  name: Scam Blocklist by DurableNapkin
  id: 1634786884
- enabled: true
  url: https://raw.githubusercontent.com/Spam404/lists/master/main-blacklist.txt
  name: Spam404
  id: 1634786885
- enabled: true
  url: https://curben.gitlab.io/malware-filter/urlhaus-filter-agh-online.txt
  name: Online Malicious URL Blocklist
  id: 1634786886
- enabled: true
  url: https://raw.githubusercontent.com/mitchellkrogza/The-Big-List-of-Hacked-Malware-Web-Sites/master/hosts
  name: The Big List of Hacked Malware Web Sites
  id: 1634786887
- enabled: true
  url: https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Alternate%20versions%20Anti-Malware%20List/AntiMalwareAdGua
  name: Dandelion Sprout's Anti-Malware List
  id: 1640801008
- enabled: true
  url: https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy.txt
  name: WindowsSpyBlocker - Hosts spy rules
  id: 1645727393
```
