### ISSUE TITLE
Seeing DoH requests from 127.0.0.1

### ISSUE THREAD

**Issue by SlothCroissant** [AdguardTeam/AdGuardHome#4521]
Have a question or an idea? Please search it [on our forum](https://github.com/AdguardTeam/AdGuardHome/discussions) to make sure it was not yet asked. If you cannot find what you had in mind, please [submit it here](https://github.com/AdguardTeam/AdGuardHome/discussions/new).

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * v0.107.6
* **How did you install AdGuard Home:**
  * via: https://raw.githubusercontent.com/AdguardTeam/AdGuardHome/master/scripts/install.sh
* **How did you setup DNS configuration:**
  * DHCP points DNS to the AGH instance
* **If it's a router or IoT, please write device model:**
  * 
* **CPU architecture:**
  * AMD64
* **Operating system and version:**
  * Debian 11

### Expected Behavior

Not to see a bunch of HTTPS DNS requests coming from AGH itself

### Screenshots

<details><summary>Screenshot:</summary>

<img width="1198" alt="Screen Shot 2022-04-23 at 22 57 09" src="https://user-images.githubusercontent.com/5846854/164955915-ce1adbe7-e528-4a15-b370-525503270a8c.png">

</details>

### Additional Information

My AdGuardHome server  (actually, two of them) is seeing a *ton* of DNS-over-HTTPS requests looking for a host in my network. The host is docker.lan, and is a real host resolved via the following query rules:

```
- '||docker.lan^$dnstype=A,dnsrewrite=NOERROR;A;10.1.10.10'
- '||10.10.1.10.in-addr.arpa^$dnsrewrite=NOERROR;PTR;docker.lan.'
- '||lan^$dnstype=AAAA,dnsrewrite=NOERROR'

```

Oddly, though - AGH is showing DNS-over-HTTPS requests come in looking for that hostname, and the requests come from 127.0.0.1:

```
Request details
Time: 22:56:48.170
Date: 4/23/2022
Domain: docker.lan
Type: HTTPS
Protocol: Plain DNS
```

The request hits a SERVFAIL: 

```
Response details
Status: Processed
DNS server: 127.0.0.1:53
Elapsed: 190 ms
Response code: SERVFAIL
```

Thing is - I am not running a DNS-over-HTTPS server for AGH. I'm only using simple UDP DNS. It's disabled entirely in config. What could be causing these requests to show up, and why? Also, even if it was some rogue thing on my host, why is AGH even thinking about HTTPS requests when it isn't even listening for DNS-over-HTTPS requests?

More details:

* My TLS config:
  ```
  tls:
    enabled: false
    server_name: ""
    force_https: false
    port_https: 443
    port_dns_over_tls: 853
    port_dns_over_quic: 784
    port_dnscrypt: 0
    dnscrypt_config_file: ""
    allow_unencrypted_doh: false
    strict_sni_check: false
    certificate_chain: ""
    private_key: ""
    certificate_path: ""
    private_key_path: ""
  ```

* My forwarders:
  ```
    upstream_dns:
    - https://1.1.1.1/dns-query
    - https://1.0.0.1/dns-query
    - '[/lan/]127.0.0.1'
  ```
   (.lan is served locally via rewrites).

Any help would be great. Thanks!
