### ISSUE TITLE
Adguard home DNS rewrites not functioning with DHCP server enabled

### ISSUE THREAD

**Issue by anaander** [AdguardTeam/AdGuardHome#4865]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, Other (please mention the version in the description)

### CPU architecture

AMD64

### Installation

Docker

### Setup

On one machine

### AdGuard Home version

v0.107.11

#### What did you do?

Created multiple DNS rewrites for hosts in the local IPs space in this format hostname.local.lan

#### Expected result

I can lookup the hosts

#### Actual result

I can only lookup the hosts with the DHCP server disabled

#### Additional information

lookup with DHCP disabled

.\doggo.exe cable.local.lan -n 10.0.0.206
NAME                    TYPE    CLASS   TTL     ADDRESS         NAMESERVER
cable.local.lan.        A       IN      10s     192.168.100.1   10.0.0.206:53

lookup with DHCP enabled

.\doggo.exe cable.local.lan -n 10.0.0.206
NAME                    TYPE    CLASS   TTL     ADDRESS                                 NAMESERVER      STATUS
cable.local.lan.        SOA     IN      10s     fake-for-negative-caching.adguard.com.  10.0.0.206:53   NXDOMAIN
                                                hostmaster.cable.local.lan. 100500
                                                1800 900 604800 86400

**Comment by anaander** [comment]
More about this; sort of "found a solution" but I'd still call it a bug.

Since my internal domain is "local.lan" I had to set the dhcp.local_domain_name to something else (in my case I just put in client.lan)

This allowed me use DNS rewrites for local.lan with DHCP enabled.

I also had to add 

dhcp.dhcpv4.options:
      - 15 hex 6C6F63616C2E6C616E

which pushed the actual domain name down to the clients when they lease an IP.

**Comment by ainar-g** [comment]
Hello.  Just to be clear, can you provide an example of the filtering rule you're applying?  Or do you mean the _Filters → DNS rewrites_ ones?

**Comment by anaander** [comment]
In AdGuardHome.yaml

```
user_rules:
  - '||pa-vm.local.lan^$dnsrewrite=NOERROR;A;10.0.0.248'
  - '||248.0.0.10.in-addr.arpa^$dnsrewrite=NOERROR;PTR;pa-vm.local.lan.'
dhcp:
  enabled: true
  interface_name: eth0
  local_domain_name: client.lan
  dhcpv4:
    gateway_ip: 10.0.0.254
    subnet_mask: 255.255.255.0
    range_start: 10.0.0.100
    range_end: 10.0.0.180
    lease_duration: 604800
    icmp_timeout_msec: 1000
    options:
      - 15 hex 6C6F63616C2E6C616E

```
Setting local_domain_name to 'local.lan' and enabling dhcp causes the custom filter to fail. Setting it to anything else (client.lan in this case) makes them to work.
