### ISSUE TITLE
Failed to start DHCP server in Podman container

### ISSUE THREAD

**Issue by skerit** [AdguardTeam/AdGuardHome#4887]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, Other (please mention the version in the description)

### CPU architecture

AMD64

### Installation

Docker

### Setup

On one machine

### AdGuard Home version

v0.107.11

#### What did you do?

I installed AdguardHome:

```
podman run --name adguardhome\
    --restart unless-stopped\
    -v /usr/local/etc/adguard/work:/opt/adguardhome/work\
    -v /usr/local/etc/adguard/conf:/opt/adguardhome/conf\
    --network host\
    -d adguard/adguardhome
```

#### Expected result

It should act as a DHCP server

#### Actual result

I got this error in the log:

```
starting dhcp server: dhcpv4: creating raw udp connection: listen packet 04:d4:c4:58:3d:69: socket: operation not permitted
```

It would also really help if this was somehow apparent in the web interface.

**Comment by agneevX** [comment]
> Installation
> 
> Docker

Docker != Podman.

Related to #2809.

**Comment by ainar-g** [comment]
I'm not familiar with Podman, but it seems like if you're running a rootless installation, binding to privileged ports is not possible.  See [their documentation][1].  I'll leave this issue open, in case anyone else has some input.

[1]: https://github.com/containers/podman/blob/main/rootless.md

**Comment by bobobo1618** [comment]
I've got AdGuardHome working in a Podman container with DHCP. I'm using Quadlet to configure the container, the config is as follows:

```
[Install]
WantedBy=default.target

[Unit]
Description=AdGuard Home DNS
After=network-online.target

[Container]
Image=docker.io/adguard/adguardhome:latest
Label=io.containers.autoupdate=registry
Volume=<insert conf here>:/opt/adguardhome/conf
Volume=<insert work here>:/opt/adguardhome/work
Network=host
AddCapability=NET_RAW
``` 

Alternatively you should just be able to do something like `podman run --net host --add-cap NET_RAW -v <volumes> docker.io/adguard/adguardhome:latest`

**Comment by warlordattack** [comment]
Hello a have the same error message : 
2024/11/12 16:53:00.954638 [error] POST 192.168.50.201 /control/dhcp/set_config: enabling dhcp: starting dhcp server: dhcpv4: creating raw udp connection: listen packet 8a:86:9f:c4:ea:55: socket: operation not permitted

But i like my adguard to have it's own IP so i run it on macvlan network,
so not with --net host.

It seems to run well but i have this error message in the logs.

Is there a way to get rid of this error running on macvlan network ?

My config : 
```

    echo "---- +MVLAN ----"
    # ip-range(29) : 7 adresses 192.168.50.200-207
    # parent : enp6s18 (ubuntu) / ens18 (rocky) / eth0 (autres)
    podman network create -d macvlan \
    --gateway=192.168.50.1 \
    --subnet=192.168.50.0/24 \
    --ip-range=192.168.50.200/29 \
    --opt parent=ens18 \
    mvlan
    #--opt com.docker.network.driver.mtu=9216 \

version: "2.1"
services:

  srv_adguard: # https://hub.docker.com/r/adguard/adguardhome
    user: ${PUID}:${PGID}
    container_name: ${C_AD}
    image: ${C_AD_IMG}
    restart: ${C_ALL_RESTART}
    hostname: ${C_AD_HOST}
    volumes:
      - ${REP_APPDATA}/${C_AD}/conf:/opt/adguardhome/conf:rw
      - ${REP_APPDATA}/${C_AD}/work:/opt/adguardhome/work:rw
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
    labels:
      - "com.centurylinklabs.watchtower.enable=${WATCHTOWER_LABEL_ENABLE}"
    cap_add:
      - NET_ADMIN   # failed to sufficiently increase receive buffer size
      - NET_RAW     # POST 192.168.50.201 /control/dhcp/set_config: enabling dhcp: starting dhcp server: dhcpv4: creating raw udp connection: listen packet 8a:86:9f:c4:ea:55: socket: operation not permitted
    mac_address: ${C_AD_MAC}
    networks:
      mvlan:
        ipv4_address: ${C_AD_IP_MVL}
networks: 
  mvlan: 
    external: true

#    ports: # en MACVLAN tous les ports sont accessibles
#      # admin panel
#      - ${C_AD_80}:80/tcp
#      - ${C_AD_443}:443/tcp
#      - ${C_AD_443}:443/udp
#      # DHCP server
#      - ${C_AD_67}:67/udp
#      - ${C_AD_68}:68/tcp
#      - ${C_AD_68}:68/udp
#      # plain DNS
#      - ${C_AD_53}:53/tcp     
#      - ${C_AD_53}:53/udp
#      # DNS-over-TLS server
#      - ${C_AD_853}:853/tcp
#      # HTTPS/DNS-over-HTTPS server
#      - ${C_AD_3000}:3000/tcp
#      # DNS-over-QUIC serve
#      - ${C_AD_784}:784/udp
#      - ${C_AD_853}:853/udp
#      - ${C_AD_8853}:8853/udp
#      # DNSCrypt server
#      - ${C_AD_5443}:5443/tcp
#      - ${C_AD_5443}:5443/udp
```

Best regards :)

**Comment by cutnicace** [comment]
Chiming in on the topic...
I am just getting started with podman and have similar issues.

Wanted to migrate from docker to rootless podman.
Got the following podman-compose file running on an ubuntu server :
```
services:
  adguardhome:
    image: docker.io/adguard/adguardhome:latest
    container_name: adguardhome
    network_mode: host
    cap_add:
      - CAP_NET_RAW
    volumes:
      - ./workdir:/opt/adguardhome/work
      - ./confdir:/opt/adguardhome/conf
    restart: unless-stopped
```
(Also needed to lower the unprivileged port numbers `sysctl net.ipv4.ip_unprivileged_port_start=53`)

But I can not get the DHCP server started.
When I try to enable it (or when the container is starting and it is enabled) the following log message appears:
`2025/04/23 18:58:20.166153 [error] starting dhcp server: dhcpv4: creating raw udp connection: listen packet 92:f0:de:ea:1f:4d: socket: operation not permitted
`

According to what I could find (and was stated in this thread), the problem should go away when adding the "CAP_NET_RAW" capability to the container?
But not in my case...

The interface on which I want to run the DHCP Server is a bridge on the server which contains my "Smart" TV's and prevents them from "talking home" too much.
Therefore all connections which are destined for udp/tcp 53 are rerouted via iptables rules to adguard home...

Could it be that the connection to the bridge is the issue here?
