### ISSUE TITLE
DOT Identifier not working in ipv6

### ISSUE THREAD

**Issue by ssrahul96** [AdguardTeam/AdGuardHome#4922]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Other (please mention in the description)

### CPU architecture

AMD64

### Installation

Docker

### Setup

On one machine

### AdGuard Home version

v0.108.0-b.15, even tried in v0.107.13

#### What did you do?

DOH Identifier is not working as expected on ipv6.

I ve setup Adguard home on a VPC, which has both ipv4 and ipv6 public addresses,

I ve private dns in Android and specified the device identifier as below

`rahul-mobile.ag.example.com` 

When my mobile is on ipv4 network (Broadband Connection), the Identifier is working as expected, 

But when my mobile is on ipv6 network (Mobile Data), the identifier is not working, and its pointing to docker proxy  address `172.18.0.1` 

#### Expected result

DOH should work in ipv6

#### Screenshots (if applicable)

<img width="1186" alt="image" src="https://user-images.githubusercontent.com/15570570/190342542-ef992c80-fbb9-40cd-a2b3-837fba37ffd3.png">

#### Additional information

docker-compose.yaml

``` yaml
  adguard:
    image: adguard/adguardhome:beta
    container_name: adguard
    ports:
      - 8443:443
      - 853:853
      - 53:53/tcp
      - 53:53/udp
    environment:
      - TZ=${TZ}
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERCONFDIR}/adguard/work:/opt/adguardhome/work
      - ${DOCKERCONFDIR}/adguard/conf:/opt/adguardhome/conf
```

**Comment by ainar-g** [comment]
Hello.  This seems like either container or DNS misconfiguration.  Please make sure that:

1.  The domain name `rahul-mobile.ag.example.com` is resolved to the correct IP addresses in both networks using both `A` and `AAAA` queries.

2.  That the IPv6 address is not behind some kind of proxy that can remove ClientHello information.

3.  You've mentioned both DoT and DoH in your report.  Does using a DoH URL with the AdGuard Home ClientID in the URL path work properly?

4.  Try enabling `--network=host`.

5.  In any case, you can [enable verbose logs][1] and see if there is any useful hints there, for example something about certificates.

[1]: https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog

**Comment by ssrahul96** [comment]
@ainar-g , 

1,2,3 are configured correctly,

I tried with `--network=host` in docker-compose, then it started to listen on `ipv6` only

<img width="840" alt="image" src="https://user-images.githubusercontent.com/15570570/190461700-59ea8ce9-7e38-4e2e-80d8-73a5ce267dae.png">

At this point in time, only connection over `ipv6` was working  

Found few helpful links 

https://stackoverflow.com/questions/29957143/make-docker-use-ipv4-for-port-binding
https://stackoverflow.com/questions/52179746/ipv4-https-request-not-forwarded-to-docker-container
https://github.com/moby/moby/issues/2174

flushing iptables after deploying the container seems to be working, Not sure whether it has to fixed in docker or OS,

**Comment by ainar-g** [comment]
Listening on `::` should be fine, since Go prefers to listen on `AF_INET6` with IPv4 mapped to IPv6.  See [here][1].

 >  At this point in time, only connection over `ipv6` was working

Does this mean that IPv4 isn't working?  What address do you have in the configuration file for `dns.bind_hosts`?  Having `0.0.0.0` works for me.

[1]: https://github.com/golang/go/blob/5231ba2f054f2ecb1387bad00b8745d6fe532ea4/src/net/ipsock_posix.go#L81-L89

**Comment by ssrahul96** [comment]
> 

``` yaml
dns:
  bind_hosts:
    - 0.0.0.0
``` 

i didnt change anything on the `bind_hosts` it seems to be default

after flushing the iptables it has worked.
