### ISSUE TITLE
Use different IP-Range for different MACs

### ISSUE THREAD

**Issue by misery** [AdguardTeam/AdGuardHome#5072]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

#### What problem are you trying to solve?
I have a lot of IOT devices in same /23 network. Those devices should be in the range 192.168.110.x and all other devices should be in 192.168.111.x to have a better overview of the IPs.

#### Proposed solution
Most IOT devices can be filtered by MAC address like ESP chips `7C:DF:A1:08:__:__`.
So it would be nice to have multiple ranges for different MAC-Ranges:

```
dhcp:
  enabled: false
  interface_name: ""
  local_domain_name: lan
  dhcpv4:
    - gateway_ip: "192.168.111.1"
      subnet_mask: "23"
      range_start: "192.168.110.0"
      range_end: "92.168.110.200"
      mac_start: "7C:DF:A1:08:00:00"
      mac_end: "7C:DF:A1:08:FF:FF"
      lease_duration: 86400
      icmp_timeout_msec: 1000
      options: []
    - gateway_ip: "192.168.111.1"
      subnet_mask: "23"
      range_start: "192.168.111.100"
      range_end: "192.168.111.200"
      mac_start: ""
      mac_end: ""
      lease_duration: 86400
      icmp_timeout_msec: 1000
      options: []
```
