### ISSUE TITLE
Add support for nftables set

### ISSUE THREAD

**Issue by mm2231031** [AdguardTeam/AdGuardHome#5136]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

#### What problem are you trying to solve?
Now that nftables is widely used, some systems no longer support the ipset function. It is reasonable to add support for nftset now.
#### Proposed solution
Dnsmasq v2.87 has added support for nfset.

**Comment by Voidstranger** [comment]
Agreed, very useful feature .

**Comment by cjom** [comment]
> Now that nftables is widely used, some systems no longer support the ipset function. It is reasonable to add support for nftset now.

OpenWrt no longer supports ipset, now is nft sets.

**Comment by emlimap** [comment]
There is a go module to work with nftables. It is still in early stages as per readme https://github.com/google/nftables

**Comment by hayzamjs** [comment]
+1

**Comment by lexbritvin** [comment]
Maybe it would be better to implement some hooks for CRUD operations. 
In yaml, we may list:
```
hooks:
  add:
    - domains: [domains as in ipset or *]
       command: ./script-add.sh
```
The scripts will be called with `os.Exec` like `script.sh domain ip`
It also covers webhooks #3662 as users may implement their own curl scripts.
There can also be predefined hooks for ipset and nftables for less tech-savy people.

The proposal is more prone to errors, but we won't rely on ipset or nftables directly. Run errors may be ignored by the app but with a warning log. 
That way, we won't wait for user specific feature requests for operations related to AGH internal processes.

What do you think?

**Comment by cjom** [comment]
Very interesting idea, I did not know about hooks.

**Comment by lexbritvin** [comment]
Very good point.

We may define timeouts. 
Let's say for critical applications like ipset/nfset we will have blocking timeout of 200ms (or any other reasonable time for dns resolution). If blocking timeout exceeds, we just continue execution ignoring the ipset. 
We may also give users a field to configure this timeout if they are running some slow hardware. They will know why DNS is slower than expected.
For cases like webhooks, the deadline for the script to run in the background is 10s-30s (also configurable) not to block the whole app.

Again, as I suggested for ipset and nfset we may have predefined implementations. Such implementations may not have timeouts as they know what they do internally. Having an internal tool for writing hooks may increase feature adoption like this FR for nftables.

Yaml example:
```yaml
hooks:
  pre-add:
    - domains: [domains as in ipset or *]
      type: ipset|nfset|... # predefined implementations
  post-add:
    - domains: [domains as in ipset or *]
      command: ./script-add.sh
      timeout: 200ms # Time until we wait for the script to finish successfully. May be -1 to block, 0 no wait, >0 for timeout.
      deadline: 30s # Time until we kill the script
```
