### ISSUE TITLE
[question] Reverse proxy in docker for DoH

### ISSUE THREAD

**Issue by mercurykd** [AdguardTeam/AdGuardHome#5334]
hi, help with setup in docker case pls
I am trying to set up DoH. I register in Windows 11 the IP of my server and the template https://mydomain.com/dns-query. If you run only adguard with open port 443 of the container, then everything works. But if I hide adguard behind nginx, then only the web interface works, and dns does not work, DNS_PROBE_FINISHED_BAD_CONFIG. What am I missing?

docker compose
```
ad:
    image: adguard/adguardhome
    volumes:
        - ./config/adguard/work:/opt/adguardhome/work
        - ./config/adguard/conf:/opt/adguardhome/conf
    networks:
        default:
            ipv4_address: 10.10.0.5
ng:
    image: nginx:stable
    volumes:
        - ./config/.profile:/root/.bashrc:ro
        - ./config/nginx.conf:/etc/nginx/nginx.conf
        - ./certs/:/certs/
    ports:
        - 443:443
    networks:
        default:
            ipv4_address: 10.10.0.6
```

nginx
```
server {
        listen       443 ssl;
        server_name  mydomain.com;
        server_tokens off;

        ssl_certificate /certs/letsencrypt;
        ssl_certificate_key /certs/letsencrypt_key;

        location / {
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-Protocol $scheme;
            proxy_pass https://10.10.0.5/;
        }
    }
```

adguard.yaml
```
trusted_proxies:
    - 10.10.0.0/24
    - 127.0.0.0/8
    - ::1/128
 tls:
  enabled: true
  server_name: mydomain.com
  force_https: false
  port_https: 443
  port_dns_over_tls: 853
  port_dns_over_quic: 853
  port_dnscrypt: 0
  dnscrypt_config_file: ""
  allow_unencrypted_doh: true
```

_Originally posted by @mercurykd in https://github.com/AdguardTeam/AdGuardHome/issues/4266#issuecomment-1374029999_
