### ISSUE TITLE
Dashboard doesnt load after setup

### ISSUE THREAD

**Issue by IThundxr** [AdguardTeam/AdGuardHome#5517]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, Other (please mention the version in the description)

### CPU architecture

Other (please mention in the description)

### Installation

Docker

### Setup

On one machine

### AdGuard Home version

latest

#### What did you do?
Setup Adguard 
#### Expected result
Dashboard shows and i can do stuff
#### Actual result
Site cant be reached error 
#### Additional information
its a intel i5 like 3rd gen cpu or smt not really sure
ive gotten 
`AdGuard Home cannot configure it automatically for this network interface. Please look for an instruction on how to do this manually.`
During the setup

```
adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 784:784/udp
      - 853:853/tcp
      - 3000:3000/tcp
      - 80:80/tcp
      - 443:443/tcp
    volumes:
      - ./adguardhome/work:/opt/adguardhome/work
      - ./adguardhome/conf:/opt/adguardhome/conf
```

My docker-compose.yaml file
      
      
      my files are structured as 
      /home
        /server
          docker-compose.yaml
          /conf
          /work
