### ISSUE TITLE
failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 2048 kiB, got: 416 kiB). See https://github.com/lucas-clemente/quic-go/wiki/UDP-Receive-Buffer-Size for details.

### ISSUE THREAD

**Issue by YouveGotMeowxy** [AdguardTeam/AdGuardHome#5555]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Other (please mention in the description)

### CPU architecture

Other (please mention in the description)

### Installation

Docker

### Setup

Other (please mention in the description)

### AdGuard Home version

AdGuard Home, version v0.107.21

#### What did you do?

I'm running the AGH Docker container and getting this in my log:

`2023/03/01 20:01:10.439323 failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 2048 kiB, got: 416 kiB). See https://github.com/lucas-clemente/quic-go/wiki/UDP-Receive-Buffer-Size for details.`

#### Expected result

No error :)

#### Actual result

Error :)

#### Additional information

I have read the link in the error, and when I manually do a:

`sudo sysctl -w net.core.rmem_max=2500000`

it sets it, even if I immediately check it with:

`sysctl -n net.core.rmem_max`

But (not sure when) it seems to get reset (or lowered) to `212992`.

I also already have this in my `/etc/sysctl.conf`:

`net.core.rmem_max=2500000`

Any ideas? Am I maybe setting the value system wide in the wrong conf file?

**Comment by ainar-g** [comment]
Are you performing these commands on the host machine or inside of the container?  According to [this](https://stackoverflow.com/a/75489483/1892060) and [this](https://unix.stackexchange.com/questions/673933/sysctl-w-net-core-rmem-max-8388608-in-docker-image-affects-host-settings#comment1271917_673933), `rmem_max` is not namespaced, so you might need to set it on the host machine and use `--net host`.

I'm not sure, what's causing the value to reset either.  In any case, this warning should really only concern configurations where a lot of QUIC traffic is expected, so it may not cause issues in most personal AGH uses.

**Comment by YouveGotMeowxy** [comment]
> Are you performing these commands on the host machine or inside of the container? According to [this](https://stackoverflow.com/a/75489483/1892060) and [this](https://unix.stackexchange.com/questions/673933/sysctl-w-net-core-rmem-max-8388608-in-docker-image-affects-host-settings#comment1271917_673933), `rmem_max` is not namespaced, so you might need to set it on the host machine and use `--net host`.
> 
> I'm not sure, what's causing the value to reset either. In any case, this warning should really only concern configurations where a lot of QUIC traffic is expected, so it may not cause issues in most personal AGH uses.

Hi @ainar-g 

I am running Docker Desktop, swarm, and WSL, and run the commands in the actual WSL VM, so the "host".

I'm just wondering if adding the `--net host` value will really matter if it's getting lowered on the "host" machine?

Here's my current ADGH Compose if it helps at all:

```
version: "3.8"

services:
    adguard:
        hostname: 'adguard'
        image: 'adguard/adguardhome:latest'
        environment:
          TZ: 'America/Chicago'
          PUID: '1000'
          PGID: '1000'
        volumes:
          - '/opt/docker/configs/adguard/config:/opt/adguardhome/conf:rw'
          - '/mnt/e/Docker/adguard/data:/opt/adguardhome/work:rw'
          - '/opt/docker/configs/swag/config/etc:/le-ssl:ro'              # Share SWAG certs
        ports:
          - '3000:3000/tcp'
          - '53:53/tcp' 
          - '53:53/udp' 
          - '853:853/tcp'
          - '853:853/udp'
          - '784:784/udp'
          - '8853:8853/udp'
          - '5443:5443/tcp'
          - '5443:5443/udp'
        networks:
          - 'dns'
        deploy:
          mode: 'replicated'
          replicas: 1
          placement:
            constraints:
              - 'node.labels.MainDaemon == true'
          restart_policy:
            condition: 'any'

networks:
  dns:
    external: true
    name: 'dns'
```
