### ISSUE TITLE
webui / login.html 404 page not found

### ISSUE THREAD

**Issue by trippleflux** [AdguardTeam/AdGuardHome#5559]
### Prerequisites

- [x] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, OpenWrt

### CPU architecture

AMD64

### Installation

Custom port

### Setup

On a router, DHCP is handled by the router

### AdGuard Home version

012e5beb51daff6eee9a10c897880505da4a5e92

#### What did you do?
Compiled my own AdGuardHome vanilla git version for OpenWrt x86_64, but the webui seems doesn't work with login.html error 404 page not found from the browsers (chrome & firefox).

Tried : 
Deleted the /etc/adguardhome.yaml to start from scratch but also getting install.html error 404 page not found

Functionalities wise, eventough webui is not accessible, AdGuardHome still able to update the blocklist and response to DNS request from LAN

#### Expected result
Able to access AdGuardHome webui

#### Actual result
webui files not accessible from browsers.

#### Additional information
OpenWrt snapshot version is r22191-f6a7ce2501

**Comment by trippleflux** [comment]
My adguardhome.yaml : 
```
bind_host: 10.10.8.1
bind_port: 9999
users:
  - name: root
    password: password
auth_attempts: 5
block_auth_min: 15
http_proxy: ""
language: ""
theme: auto
debug_pprof: false
web_session_ttl: 720
dns:
  bind_hosts:
    - 10.10.8.1
  port: 53
  anonymize_client_ip: false
  protection_enabled: true
  blocking_mode: default
  blocking_ipv4: ""
  blocking_ipv6: ""
  blocked_response_ttl: 10
  parental_block_host: family-block.dns.adguard.com
  safebrowsing_block_host: standard-block.dns.adguard.com
  ratelimit: 0
  ratelimit_whitelist: []
  refuse_any: true
  upstream_dns:
    - tls://1.1.1.1
    - tls://1.0.0.1
    - tls://9.9.9.10
    - tls://149.112.112.10
    - quic://94.140.14.140
    - quic://94.140.14.141
    - tls://8.8.8.8
    - tls://8.8.4.4
    - '[/lan/]127.0.0.1:5353'
    - '[//]127.0.0.1:5353'
  upstream_dns_file: ""
  bootstrap_dns:
    - 9.9.9.10
    - 149.112.112.10
    - 2620:fe::10
    - 2620:fe::fe:10
  all_servers: true
  fastest_addr: false
  fastest_timeout: 1s
  allowed_clients: []
  disallowed_clients: []
  blocked_hosts:
    - version.bind
    - id.server
    - hostname.bind
  trusted_proxies:
    - 127.0.0.0/8
    - ::1/128
  cache_size: 4194304
  cache_ttl_min: 0
  cache_ttl_max: 0
  cache_optimistic: true
  bogus_nxdomain: []
  aaaa_disabled: true
  enable_dnssec: false
  edns_client_subnet:
    custom_ip: ""
    enabled: false
    use_custom: false
  max_goroutines: 300
  handle_ddr: true
  ipset: []
  ipset_file: ""
  filtering_enabled: true
  filters_update_interval: 1
  parental_enabled: false
  safesearch_enabled: false
  safebrowsing_enabled: false
  safebrowsing_cache_size: 1048576
  safesearch_cache_size: 1048576
  parental_cache_size: 1048576
  cache_time: 30
  rewrites: []
  blocked_services: []
  upstream_timeout: 10s
  private_networks: []
  use_private_ptr_resolvers: true
  local_ptr_upstreams:
    - 127.0.0.1:5353
  use_dns64: false
  dns64_prefixes: []
  serve_http3: false
  use_http3_upstreams: false
tls:
  enabled: false
  server_name: ""
  force_https: false
  port_https: 443
  port_dns_over_tls: 853
  port_dns_over_quic: 853
  port_dnscrypt: 0
  dnscrypt_config_file: ""
  allow_unencrypted_doh: false
  certificate_chain: ""
  private_key: ""
  certificate_path: ""
  private_key_path: ""
  strict_sni_check: false
querylog:
  enabled: true
  file_enabled: true
  interval: 6h
  size_memory: 1000
  ignored: []
statistics:
  enabled: true
  interval: 90
  ignored: []
filters:
  - enabled: true
    url: https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt
    name: AdGuard DNS filter
    id: 1
  - enabled: true
    url: https://adaway.org/hosts.txt
    name: AdAway Default Blocklist
    id: 2
  - enabled: true
    url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_27.txt
    name: OISD Blocklist Full
    id: 1670456622
  - enabled: true
    url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_8.txt
    name: NoCoin Filter List
    id: 1670456623
  - enabled: true
    url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_23.txt
    name: WindowsSpyBlocker - Hosts spy rules
    id: 1670456624
  - enabled: true
    url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_21.txt
    name: 'CHN: anti-AD'
    id: 1670456625
  - enabled: true
    url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_12.txt
    name: Dandelion Sprout's Anti-Malware List
    id: 1670456626
  - enabled: true
    url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_22.txt
    name: 'IDN: ABPindo'
    id: 1670456627
  - enabled: true
    url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_30.txt
    name: Phishing URL Blocklist (PhishTank and OpenPhish)
    id: 1670456628
  - enabled: true
    url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_10.txt
    name: Scam Blocklist by DurableNapkin
    id: 1670456629
  - enabled: true
    url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_11.txt
    name: Malicious URL Blocklist (URLHaus)
    id: 1670456630
whitelist_filters: []
user_rules:
  - '@@||i.top4top.io^$important'
  - '@@||pulpstone.pw^$important'
  - '##||api.miwifi.com'
  - '@@||click.redditmail.com^$important'
  - '||www.taobao.com^$important'
  - '||www.baidu.com^$important'
  - '@@||download.coolhub.top^$important'
  - '@@||track.gojek.com^$important'
  - '@@||api-secure.solvemedia.com^$important'
  - '@@||sg.acdid.acdsystems.com^$important'
  - '@@||api16-access-sg.pangle.io^$important'
  - '@@||config.emb-api.com^$important'
  - '@@||eu1-spiky.clevertap-prod.com^$important'
  - '@@||api16-log-sg.pangle-b.io^$important'
  - '@@||frontier.byteoversea.com^$important'
  - '@@||i.isnssdk.com^$important'
  - '@@||events.appsflyer.com^$important'
  - '@@||t.appsflyer.com^$important'
  - '@@||api.radar.io^$important'
  - '@@||c-api-bit.shopeemobile.com^$important'
  - '@@||adashx4ae.ut.taobao.com^$important'
  - '||www.googleadservices.com^$important'
  - '@@||fls-na.amazon.com^$important'
  - ""
dhcp:
  enabled: false
  interface_name: ""
  local_domain_name: lan
  dhcpv4:
    gateway_ip: ""
    subnet_mask: ""
    range_start: ""
    range_end: ""
    lease_duration: 86400
    icmp_timeout_msec: 1000
    options: []
  dhcpv6:
    range_start: ""
    lease_duration: 86400
    ra_slaac_only: false
    ra_allow_slaac: false
clients:
  runtime_sources:
    whois: true
    arp: true
    rdns: true
    dhcp: true
    hosts: true
  persistent: []
log_file: ""
log_max_backups: 0
log_max_size: 100
log_max_age: 3
log_compress: false
log_localtime: false
verbose: false
os:
  group: ""
  user: ""
  rlimit_nofile: 0
schema_version: 17
```
