### ISSUE TITLE
AdguardHome high CPU usage and without response suddenly

### ISSUE THREAD

**Issue by tomac4t** [AdguardTeam/AdGuardHome#5674]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer
- [X] I have searched other issues and found no duplicates
- [X] I want to report a bug and not ask a question

### Operating system type

Linux, OpenWrt

### CPU architecture

ARMv7

### Installation

Other (please mention in the description)

Pre-install AdguardHome on GL.INet GL-AX1800 router: https://www.gl-inet.com/products/gl-ax1800/

### Setup

On a router, DHCP is handled by the router

### AdGuard Home version

v0.107.5

#### What did you do?

DNS with no response suddenly and found CPU usage of AdguardHome is so high.

![2023-04-02_18-43](https://user-images.githubusercontent.com/47532693/229355785-44a6174b-da41-47cb-b3d3-c4c38a33e068.png)

According to #4437, I did 
- Disable Optimistic caching
- Only keep 4 blocklists
```yaml
filters:
- enabled: true
  url: https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt
  name: AdGuard DNS filter
  id: 1
- enabled: true
  url: https://cdn.jsdelivr.net/gh/neoFelhz/neohosts@gh-pages/basic/hosts.txt
  name: neohosts
  id: 1662349650
- enabled: true
  url: https://adaway.org/hosts.txt
  name: AdAway Default Blocklist
  id: 1669113138
- enabled: true
  url: https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy.txt
  name: WindowsSpyBlocker - Hosts spy rules
  id: 1680198205
```
But recently this situation is more frequent, and I meet this every day. Then I did  
- Disable Log
- Disable Filters update interval
But it no help, still continue happened.

I also do https://github.com/AdguardTeam/AdGuardHome/issues/4437#issuecomment-1084956572, `ssh root@192.168.1.1 -p 22 'curl http://127.0.0.1:6060/debug/pprof/heap' > /tmp/heap` on the begining of restart AdguardHome. (send to [devteam@adguard.com](mailto:devteam@adguard.com)?) But there is no response when AdguardHome high CPU usage happened:
```bash
$ ssh root@192.168.1.1 -p 22 'curl http://127.0.0.1:6060/debug/pprof/heap' > /tmp/heap
root@192.168.1.1's password: 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:03:52 --:--:--     0
curl: (56) Recv failure: Connection reset by peer
```

#### Expected result

AdguardHome running as DNS service stability.

#### Actual result

Stopping DNS response and use a lot of CPU, like crash.

#### Screenshots (if applicable)

Can't open web dashboard.
