### ISSUE TITLE
docker-compose overwrites the bind_host web interface in AdGuardHome.yaml file (even when the container is down)

### ISSUE THREAD

**Issue by KalyaSc** [AdguardTeam/AdGuardHome#5747]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, Other (please mention the version in the description)

### CPU architecture

AMD64

### Installation

Docker

### Setup

On one machine

### AdGuard Home version

latest

### Description

First, I read the docs saying that the container must be down before changing the AdGuardHome.yaml, otherwise it overwrites it. So that's not the issue here. Actually on first startup and configuration, choosing the desired listen interface for the Admin Web is properly saved in the AdGuardHome.yaml. But after a docker-compose down / docker-compose up, the bind_host is getting **overwritten to 0.0.0.0** (listening on all interfaces).

### What did you do?
docker-compose down / docker-compose up (even without looking in the AdGuardHome.yaml first)

### Unexpected result
bind_host is getting overwritten to 0.0.0.0 (listening on all interfaces) in the AdGuardHome.yaml

### Things I tried
- Changing the bind_host manually in the AdGuardHome.yaml (while the container is down)
- Pulled the new adguardhome image and recreating the docker-compose
- Changing the Network mode
- Use another single bind_host (other than wireguard)

### Additional information
OS: Ubuntu 20.04

I don't know if the information is somehow related, but I'm binding to a wireguard network interface. But as I said, I also tried to bind to another single bind_host.

I though it was relate to [#5714](https://github.com/AdguardTeam/AdGuardHome/issues/5714), but disabling the healthcheck changed nothing.

### Docker-compose file
```
---
version: "3.7"
services:
  adguardhome:
    container_name: adguardhome
    restart: unless-stopped
    network_mode: host
    volumes:
      - /etc/adguardhome/work:/opt/adguardhome/work
      - /etc/adguardhome/conf:/opt/adguardhome/conf
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 80:80/tcp
      - 3000:3000/tcp
    image: adguard/adguardhome
    healthcheck:
      disable: true
```
