### ISSUE TITLE
AGH v0.107.29 on Docker doesn't work

### ISSUE THREAD

**Issue by boardlord1** [AdguardTeam/AdGuardHome#5751]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, Other (please mention the version in the description)

### CPU architecture

AMD64

### Installation

Docker

### Setup

On one machine

### AdGuard Home version

0.107.29

#### What did you do?
I've updated AGH via Portainer as usual (recreate image by re-pulling). I've been using AGH On Synology NAS for many months without problems. 

#### Expected result
Like mane times before, a simple update.

#### Actual result
The logs don't display any errors, AGH starts, binds addresses successfully.

However, it doesn't resolve addresses, and the AGH GUI doesn't load on 192.168.7.124:8080 - just times out.

#### Additional information
My Docker compose in my stack for AGH 
```
  adguard:
    image: adguard/adguardhome
    container_name: "adguardhome"
    cap_add:
      - NET_ADMIN
    networks:
      composemacvlan:
        ipv4_address: 192.168.7.124
    environment:
      - PGID=100
      - PUID=1037
      - TZ=Europe/Budapest
    privileged: true
    volumes:
      - "/volume1/docker/adguard/conf:/opt/adguardhome/conf:rw"
      - "/volume1/docker/adguard/work:/opt/adguardhome/work:rw"
```
