### ISSUE TITLE
Container keeps restarting (exec /sbin/tini: no such file or directory)

### ISSUE THREAD

**Issue by talesam** [AdguardTeam/AdGuardHome#5899]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, Other (please mention the version in the description)

### CPU architecture

x86

### Installation

Docker

### Setup

On one machine

### AdGuard Home version

latest - Docker

#### What did you do?
I ran the following docker-compose based on the official documentation:
```
 
version: "3"
services:
   adguard:
     container_name: adguardhome
     restart: unless-stopped
     volumes:
       - ./workdir:/opt/adguardhome/work
       - ./confdir:/opt/adguardhome/conf
     ports:
       - 6000:53/tcp
       - 6000:53/udp
       #- 67:67/udp
       #- 68:68/udp
       #- 80:80/tcp
       #- 443:443/tcp
       #- 443:443/udp
       - 3030:3000/tcp
       #- 853:853/tcp
       #- 784:784/udp
       #- 853:853/udp
       #- 8853:8853/udp
       #- 5443:5443/tcp
       #- 5443:5443/udp
     image: adguard/adguardhome
```

#### Expected result
Run the container and open the web application on localhost:3030

#### Actual result
Container keeps resetting, I went to check the log showing the following:

```
❯ docker-compose ps
NAME IMAGE COMMAND SERVICE CREATED STATUS PORTS
adguardhome adguard/adguardhome "/sbin/tini -- /opt/…" adguard 7 seconds ago Up Less than a second (health: starting) 80/tcp, 67-68/udp, 443/udp, 443/tcp, 784/ udp, 853/udp, 853/tcp, 3000/udp, 5443/tcp, 5443/udp, 8853/udp, 6060/tcp, 0.0.0.0:6000->53/tcp, 0.0.0.0:6000->53/ udp, :::6000->53/tcp, :::6000->53/udp, 0.0.0.0:3030->3000/tcp, :::3030->3000/tcp
❯ docker-compose ps
NAME IMAGE COMMAND SERVICE CREATED STATUS PORTS
adguardhome adguard/adguardhome "/sbin/tini -- /opt/…" adguard 59 seconds ago Restarting (1) 20 seconds ago
❯ docker-compose logs
adguardhome | exec /sbin/tini: no such file or directory
adguardhome | exec /sbin/tini: no such file or directory
adguardhome | exec /sbin/tini: no such file or directory
```

#### Screenshots (if applicable)

![image](https://github.com/AdguardTeam/AdGuardHome/assets/981368/f01e4ced-8524-4188-aefc-7f1c883e649e)
