### ISSUE TITLE
"failed to sufficiently increase send buffer size" log error even though UDP buffer size was increased to ~2.5MB in /etc/sysctl.conf

### ISSUE THREAD

**Issue by kosmonot** [AdguardTeam/AdGuardHome#5903]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, Other (please mention the version in the description)

### CPU architecture

x86

### Installation

GitHub releases or script from README

### Setup

On a router, DHCP is handled by the router

### AdGuard Home version

v0.107.31

#### What did you do?
Upgraded container to v.107.31 (this started happening at the prior version v0.107.30). It does not happen in v0.107.29.

I had edited my `/etc/sysctl.conf` to add the line `net.core.rmem_max=2500000` to allocate ~2.5MB of buffer 

#### Expected result
No  `failed to sufficiently increase send buffer size` error

#### Actual result
`failed to sufficiently increase send buffer size` error

#### Additional information

This started happening on all my adguardhome instances:

- Debian 11
- Ubuntu 20.04
- RPI Debian 11 64 bit 

Rolling back to v0.107.29 fixes the issue

**Comment by kosmonot** [comment]
This is the full error message I receive on all my instances after upgrading to v0.107.29:

`failed to sufficiently increase send buffer size (was: 208 kiB, wanted: 2048 kiB, got: 416 kiB). See https://github.com/quic-go/quic-go/wiki/UDP-Receive-Buffer-Size for details.`

**Comment by ainar-g** [comment]
Is AdGuard Home running in a container or on the host system itself?  Because in your issue template you've written that you've used the installation script as opposed to selecting the “Docker” option.  If it's in a Docker container, [there are known Docker issues with `sysctl`](https://stackoverflow.com/a/54845286/1892060), and resolving those requires running the container in a more privileged manner.

**Comment by timkgh** [comment]
Does this setting really matter for DNS queries over http/3? I can see how in general it's important for http/3 connections that move a lot of data, but DNS queries should be very small. Maybe it is important for AGH servers that see a lot of traffic and not an issue in a home setup.

**Comment by kosmonot** [comment]
> Is AdGuard Home running in a container or on the host system itself? Because in your issue template you've written that you've used the installation script as opposed to selecting the “Docker” option. If it's in a Docker container, [there are known Docker issues with `sysctl`](https://stackoverflow.com/a/54845286/1892060), and resolving those requires running the container in a more privileged manner.

Apologies, I am running in a docker container using a standard AGH docker compose stack.

**Comment by Unrepentant-Atheist** [comment]
Same problem here...

Just using 
```
---
version: "2"
services:
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    hostname: adguardhome
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 784:784/udp
      - 853:853/tcp
      - 3000:3000/tcp
      - 80:80/tcp
      - 443:443/tcp
    network_mode: "host"
    restart: unless-stopped
    #healthcheck:
      #test: wget --no-verbose --tries=1 --spider http://localhost || exit 1
      #interval: 120s
      #retries: 5
      #start_period: 20s
      #timeout: 10s
    labels:
      - deunhealth.restart.on.unhealthy=true
    volumes:
      - /volume1/docker/adguardhome/work:/opt/adguardhome/work
      - /volume1/docker/adguardhome/conf:/opt/adguardhome/conf
```

**Comment by otbutz** [comment]
Add the `NET_ADMIN` capability to your container and things should work, as quic-go is using `SO_RCVBUFFORCE` / `SO_SNDBUFFORCE` as of [v0.35.0](https://github.com/quic-go/quic-go/releases/tag/v0.35.0)

```yml
version: "2"
services:
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    hostname: adguardhome
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 784:784/udp
      - 853:853/tcp
      - 3000:3000/tcp
      - 80:80/tcp
      - 443:443/tcp
    network_mode: "host"
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    #healthcheck:
      #test: wget --no-verbose --tries=1 --spider http://localhost || exit 1
      #interval: 120s
      #retries: 5
      #start_period: 20s
      #timeout: 10s
    labels:
      - deunhealth.restart.on.unhealthy=true
    volumes:
      - /volume1/docker/adguardhome/work:/opt/adguardhome/work
      - /volume1/docker/adguardhome/conf:/opt/adguardhome/conf
```
