### ISSUE TITLE
Cannot start container with preconfigured config file

### ISSUE THREAD

**Issue by chrxmvtik** [AdguardTeam/AdGuardHome#5966]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux/AMD64 (aka x86_64)

### Installation

Docker

### Setup

On one machine

### AdGuard Home version

v0.107.33

### Action

```yaml
  spec:
        containers:
        - name: adguard-home
          image: adguard/adguardhome:latest
          ports:
          - containerPort: 53 #dns
            name: dns
            protocol: UDP
          - containerPort: 3000 #initial setup
            name: http-initial
          - containerPort: 80 #web gui
            name: http
            protocol: TCP
          volumeMounts:
          - name: adguard-config
            mountPath: /opt/adguardhome/conf/AdGuardHome.yaml
            subPath: AdGuardHome.yaml
          - name: adguard-data
            mountPath: /opt/adguardhome/work
          - name: adguard-certs
            mountPath: /etc/adguard/certs
            readOnly: true
```
I have configured volumeMounts on Kubernetes to point to certs and config location, certs are working fine, however when AGH is trying to start with premounted config file via ConfigMap, then it just drops an error:

`
[fatal] writing config file: rename /tmp/.AdGuardHome.yaml34246535 /opt/adguardhome/conf/AdGuardHome.yaml: device or resource busy
`

I tried to manually start AGH within the pod using proper flags, based on docker image:
```bash
CMD ["/opt/adguardhome/AdGuardHome" "--no-check-update" "-c" "/opt/adguardhome/conf/AdGuardHome.yaml" "-w" "/opt/adguardhome/work"]
```

Also tried to move config file to another locations and start AGH manually with specified location, still the same error remains.

I managed to workaround this issue by modifying command attached to deployment as of:

```yaml
        command:
          - "sh"
          - "-c"
          - >
            cp /etc/adguard/conf/AdGuardHome.yaml /opt/adguardhome/conf &&
            sleep 10 &&
            /opt/adguardhome/AdGuardHome --no-check-update --config /opt/adguardhome/conf/AdGuardHome.yaml
```

The key here is to wait some time before starting AGH with new config and avoid using work-dir - otherwise it is going to get stuck.

### Expected result

AdGuardHome reads properly config file from mounted volume

### Actual result

AdGuardHome doesn't read properly config file from mounted volume
