### ISSUE TITLE
Add CAP_NET_ADMIN to systemd unit

### ISSUE THREAD

**Issue by otbutz** [AdguardTeam/AdGuardHome#6000]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

The user has to manually edit `/etc/sysctl.conf` values to get rid of the quic-go warning and benefit from improved QUIC performance.

### Proposed solution

quic-go v0.35.0+ uses `SO_RCVBUFFORCE` and `SO_SNDBUFFORCE` which doesn't require tinkering with sysctl limits. The only downside is that the process must be executed with the `CAP_NET_ADMIN` capability to do this.

Adding the following line to the systemd unit should fix this:

```
AmbientCapabilities=CAP_NET_ADMIN
```

**Comment by otbutz** [comment]
For docker deployments this is mostly a documentation issue as point out in https://github.com/AdguardTeam/AdGuardHome/issues/5903#issuecomment-1632307183

Either via docker:

```
docker run --name adguardhome\
    --restart unless-stopped\
    --cap-add=NET_ADMIN\
    -v /my/own/workdir:/opt/adguardhome/work\
    -v /my/own/confdir:/opt/adguardhome/conf\
    -p 53:53/tcp -p 53:53/udp\
    -p 67:67/udp -p 68:68/udp\
    -p 80:80/tcp -p 443:443/tcp -p 443:443/udp -p 3000:3000/tcp\
    -p 853:853/tcp\
    -p 784:784/udp -p 853:853/udp -p 8853:8853/udp\
    -p 5443:5443/tcp -p 5443:5443/udp\
    -d adguard/adguardhome
```

or via docker compose:

```yml
services:
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    hostname: adguardhome
    network_mode: "host"
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
```
