### ISSUE TITLE
Extra set of triple backticks in a code block in Configuration wiki page

### ISSUE THREAD

**Issue by agrmohit** [AdguardTeam/AdGuardHome#6001]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

Line 776 on [Configuration](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#password-reset:~:text=...%0A%20%20%20%20password%3A-,%3CHASH%3E%60%60%60,-Save%20the%20file) contains extra triple backticks
Opening an issue since I can't create a PR on a wiki page.

```yaml
users:
  - name: ...
    password: <HASH>```
```

### Proposed solution

Change it to

```yaml
users:
  - name: ...
    password: <HASH>
```
