### ISSUE TITLE
Healthcheck error with the docker version

### ISSUE THREAD

**Issue by Erwan-loot** [AdguardTeam/AdGuardHome#6008]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux/AMD64 (aka x86_64)

### Installation

Docker

### Setup

On one machine

### AdGuard Home version

v0.107.34

### Action

Hi,

i'm running the container with update 107.34, 
this update removes the script healthcheck, but the healthcheck try to run the script anyway causing an unhealthy container

### Expected result

There is no error with the healthcheck.

### Actual result

```sh
 "/opt/adguardhome/scripts/healthcheck.sh": stat /opt/adguardhome/scripts/healthcheck.sh: no such file or directory: unknown
```

### Additional information and/or screenshots

My docker-compose
```yaml
version: "2.4"
services:
  adguard:
    image: adguard/adguardhome:latest
    container_name: adguard
    network_mode: host
    volumes:
      - "/docker/adguard/data:/opt/adguardhome/work/data:rw"
      - "/docker/adguard/config:/opt/adguardhome/conf:rw"
    restart: unless-stopped
    security_opt:
      - no-new-privileges=true
    mem_limit: 1024m
```
