### ISSUE TITLE
v0.93 - Redirect to https  does not work

### ISSUE THREAD

**Issue by zeus10000** [AdguardTeam/AdGuardHome#607]
With Redirect to HTTPS set to enabled, I do not see the http link getting redirected to https instead it shows as cannot connect to server.

```
bind_host: 0.0.0.0
bind_port: 3000
auth_name: ########
auth_pass: ########
language: ""
dns:
  bind_host: 0.0.0.0
  port: 53
  protection_enabled: true
  filtering_enabled: true
  blocked_response_ttl: 10
  querylog_enabled: true
  ratelimit: 20
  ratelimit_whitelist: []
  refuse_any: true
  bootstrap_dns: 8.8.8.8:53
  parental_sensitivity: 13
  parental_enabled: true
  safesearch_enabled: false
  safebrowsing_enabled: true
  upstream_dns:
  - tls://1.1.1.1
  - tls://1.0.0.1
tls:
  enabled: true
  server_name: ########
  force_https: true
  port_https: 443
  port_dns_over_tls: 853
  certificate_chain: |-
    -----BEGIN CERTIFICATE-----
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    -----END CERTIFICATE-----
  private_key: |-
    -----BEGIN PRIVATE KEY-----
    -----END PRIVATE KEY-----
```
