### ISSUE TITLE
Encryption (TLS) not working with cloudflare tunnels

### ISSUE THREAD

**Issue by xd003** [AdguardTeam/AdGuardHome#6111]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, ARM64

### Installation

Docker

### Setup

Deployed using docker compose on a vps -
```
adguardhome:
    image: adguard/adguardhome 
    container_name: adguardhome
    restart: unless-stopped
    ports:
      - "10.0.0.36:53:53/tcp"
      - "10.0.0.36:53:53/udp"
      - "80:80/tcp"
      - "443:443/tcp"
      - "443:443/udp"
      - "853:853/tcp"
      - "3000:3000/tcp"
    volumes:
      - /home/ubuntu/docker/adguard/data:/opt/adguardhome/work
      - /home/ubuntu/docker/adguard/config:/opt/adguardhome/conf
```

### AdGuard Home version

Version:  v0.107.36

### Action

1) Created a tunnel in cloudflare zero trust, deployed adguard home and cloudflared using docker-compose, adguard and tunnel status healthy, AG dashboard  accessible through IP:80 after initial setup

2) Now i created 2 public hostname in cloudflare tunnel. One for accessing the web interface, other for tls. Details mentioned below
```
• Dashboard
Subdomain1
Type - HTTP
URL - adguardhome:80

• TLS
subdomain2
Type - HTTP
URL - adguardhome:853
```
3) Adguard Dashboard is now accessible at https://subdomain1.domain.xyz

4) I generate a ssl certificate in cloudflare. Sites -> SSL/TLS -> Origin Server and save the certificate and key to a path in my server which adguard docker can access

5) i proceed ahead with encryption settings in AG home with Server Name as subdomain2.domain.xyz, added the path for certificate and key, it got detected fine so i clicked on save configuration

### Expected result

The internet should work fine when connecting through that domain through private dns settings 

### Actual result

When i enter subdomain2.domain.xyz in Private DNS settings in my Android device, it reports that there is no internet access
