### ISSUE TITLE
Feature Request: Optional Dark Theme

### ISSUE THREAD

**Issue by Ultrabenosaurus** [AdguardTeam/AdGuardHome#613]
Please can you add an optional dark theme of some sort? There are plenty of examples online to take inspiration from like community-made Atom themes hosted on Github. I have a browser extension that allows me to turn any website "dark" but it basically just inverts CSS colours, so the colour-coded bits in AdGuard Home and the logo in the top-left don't really work. 

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/1901532/53680286-17677b80-3cd1-11e9-9b00-26f3d5bfcafd.png)

</details>

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| Version of AdGuard Home server:| 0.93
| How did you setup DNS configuration:| Primary DNS for my Router
| If it's a router or IoT, please write device model:| Raspberry Pi 3 Model B 
| Operating system and version:| latest Raspbian (I updated last night)

### EDIT

For those interested I have published my latest dark theme CSS on userstyles.org for Stylus users: 

https://userstyles.org/styles/177418/adguard-home-dark 

I recommend using the "Customize Settings" button to set the IP address or local domain of your AdGuard Home interface before installing the theme, so that it works straight away. I've also added a setting so you can specify a main font; personally, I quite like [Lato](https://fonts.google.com/specimen/Lato) at the moment. Thanks to @carlbennett for the initial CSS and inspiration to tinker with this.

**Comment by ameshkov** [comment]
Well, the UI is not our top priority at the moment, but we'll take this feature request into account once we start working on the final design.

**Comment by Ultrabenosaurus** [comment]
That's fine, I thought that'd be the case for now :)

**Comment by frenck** [comment]
It would look amazing though...

![image](https://user-images.githubusercontent.com/195327/57011125-5c8c2900-6c00-11e9-83f7-9d31048383c9.png)

**Comment by carlbennett** [comment]
I'm making a userstyle theme for those interested. This is just a work in progress with what I have right now. But for me, this is so much nicer already.

Get the Stylus extension: https://add0n.com/stylus.html

Add this code:
```css
@-moz-document domain("192.168.1.22") {
body { background-color: #222; color: #eee; }
a { color: #aaffaa; }

.header { background-color: #336633; color: #eee; }
.mobile-menu { background-color: inherit; }

.footer { background-color: #113311; }
.footer a:not(.btn) { color: #aaffaa; }

.card { background-color: #333; }
.card-table tr td, .card-table tr th { border-color: #555; }

}
```

Change the IP address to where your AdGuard Home is located at.

:+1:

I'll update this with better code later as I manipulate my custom style code. Here's a preview.

![image](https://user-images.githubusercontent.com/592196/68642812-f0568000-04d4-11ea-9e1c-a599a453e96a.png)

**Comment by ArchiveBase** [comment]
You dont have to tired like that and its opensource as well.
https://chrome.google.com/webstore/detail/dark-reader/eimadpbcbfnmbkopoojfekhnkhdbieeh
https://addons.mozilla.org/en-US/firefox/addon/darkreader/

**Comment by carlbennett** [comment]
I don't want to have to keep flipping a switch. That extension doesn't work well on some pages. I like having finer control over specific pages. I do have that extension already installed and available to me, though.

**Comment by ArchiveBase** [comment]
![image](https://user-images.githubusercontent.com/46082456/68700861-42240680-05b8-11ea-8ccb-8cfdcf516606.png)

**Comment by Ultrabenosaurus** [comment]
@carlbennett I've added a few bits to improve the Query Log page:

```css
body { background-color: #222; color: #eee; }
a { color: #aaffaa; }
.header { background-color: #336633; color: #eee; }
.mobile-menu { background-color: inherit; }
.footer { background-color: #113311; }
.footer a:not(.btn) { color: #aaffaa; }
.card, .rt-tr { background-color: #333; }
.card-table tr td, .card-table tr th { border-color: #555; }
.rt-tr.red { background-color: #5f3333; }
.rt-tr.green { background-color: #335f33; }
.rt-tr.-even { filter: brightness(85%); }
```

I've set specific colours for the red and green rows, which your CSS left as mostly-white, and made the rows alternate with a slightly darker grey. The alternating bit also required specifying a default colour for `.rt-tr` which I tacked onto your `.card` declaration.

![image](https://user-images.githubusercontent.com/1901532/69089188-c9053300-0a3f-11ea-8e2c-1cf12717b334.png)
