### ISSUE TITLE
Statistical X-axis information error

### ISSUE THREAD

**Issue by bestpika** [AdguardTeam/AdGuardHome#6159]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Windows, AMD64 (aka x86_64)

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

v0.108.0-a.675+18d15be4

### Action

N/A

### Expected result

N/A

### Actual result

I noticed that the X-axis of the chart displays future dates.

### Additional information and/or screenshots

![image](https://github.com/AdguardTeam/AdGuardHome/assets/5698157/7a57c69d-35d8-415b-8318-d17124653a4e)
![image](https://github.com/AdguardTeam/AdGuardHome/assets/5698157/a8cee810-61be-4276-912e-f6cef99c69ac)

Configuration:
```yaml
querylog:
  ignored: []
  interval: 48h
  size_memory: 1000
  enabled: true
  file_enabled: true
statistics:
  ignored: []
  interval: 48h
  enabled: true
```
