### ISSUE TITLE
DoH with ClientID as Subdomain not being Recognized

### ISSUE THREAD

**Issue by clstrickland** [AdguardTeam/AdGuardHome#6371]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

FreeBSD, AMD64 (aka x86_64)

### Installation

Custom package (OpenWrt, HomeAssistant, etc; please mention in the description)

### Setup

On a router, DHCP is handled by the router

### AdGuard Home version

v0.108.0-b.47

### Action

```sh
./q @tls://test-device-7cn4d7-badclientid.adguard.myrealdomain.me google.com

./q @tls://test-device-7cn4d7.adguard.myrealdomain.me google.com
google.com. 4m20s A 142.250.189.238
google.com. 4m20s AAAA 2607:f8b0:4023:1000::71
[a whole bunch of records...]
google.com. 59m20s TXT "docusign=1b0a6754-49b1-4db5-8540-d2c12664b289"

./q @https://test-device-7cn4d7-badclientid.adguard.myrealdomain.me google.com

./q @https://test-device-7cn4d7.adguard.myrealdomain.me google.com
```

### Expected result

I don't really use "myrealdomain.me", I changed it in the report for privacy

AdGuard is configured with a client, which is whitelisted. When using DoT or DoH, we expect a request with a valid clientid as subdomain to return a response, and a request with an invalid clientid to not be responded to.

In this case, we expect the DoH and DoT requests using `test-device-7cn4d7.adguard.myrealdomain.me` to work, and those using `https://test-device-7cn4d7-badclientid.adguard.myrealdomain.me` to fail

### Actual result

For DoT, the results are as expected. However, with DoH, even with a valid clientid, there is no response.

### Additional information and/or screenshots

AdGuard Home is running on OPNSense. There is a reverse proxy, Traefik, which is handling https certificates.

I have configured a whoami container which is configured in Traefik in the same fashion as AdGuard Home, this effectively shows what the request looks like when AdGuard Home receives it.

These screenshots were taken while accessing the site from another location, so Traefik sees a public IP.

![image](https://github.com/AdguardTeam/AdGuardHome/assets/50763236/91da2bcb-fd32-4550-ab3b-47dd649a0eda)

![image](https://github.com/AdguardTeam/AdGuardHome/assets/50763236/44ed6cb4-6571-4f28-ab80-f168c5660773)

We can see that X-Real-IP, X-Forwarded-For, and Host are all provided, which is needed per https://github.com/AdguardTeam/AdGuardHome/wiki/Encryption#reverse-proxy

## Adguard Logs (from running `./q @https://test-device-7cn4d7.adguard.myrealdomain.me google.com`) 
<img width="1512" alt="image" src="https://github.com/AdguardTeam/AdGuardHome/assets/50763236/d07df11d-0f93-4109-86e5-66a4d839bbf3">

## AdGuard Home Config (AdGuardHome.yaml)
```yaml
dns:
  bind_hosts:
    - 0.0.0.0
  port: 53
  anonymize_client_ip: false
  ratelimit: 20
  ratelimit_whitelist: []
  refuse_any: true
  upstream_dns:
    - 127.0.0.1:53530
    - '[::1]:53530'
  upstream_dns_file: ""
  bootstrap_dns:
    - 9.9.9.10
    - 149.112.112.10
    - 2620:fe::10
    - 2620:fe::fe:10
  fallback_dns: []
  all_servers: false
  fastest_addr: false
  fastest_timeout: 1s
  allowed_clients:
    - 192.168.0.0/16
    - test-device-7cn4d7
    - 127.0.0.0/8
  disallowed_clients: []
  blocked_hosts:
    - version.bind
    - id.server
    - hostname.bind
  trusted_proxies:
    - 127.0.0.0/8
    - ::1/128
    - 192.168.1.5
  cache_size: 4194304
```
## Verifying host can access other DoH servers
```sh
./q --trace @https://test-device-7cn4d7.whoami.myrealdomain.me google.com
TRAC[0000] no cases matched for host test-device-7cn4d7.whoami.myrealdomain.me port
TRAC[0000] Setting port to 443
TRAC[0000] checking FQDN https://test-device-7cn4d7.whoami.myrealdomain.me
TRAC[0000] HTTPS scheme and no path, setting server to https://test-device-7cn4d7.whoami.myrealdomain.me:443/dns-query
DEBU[0000] Using HTTP(s) transport: https://test-device-7cn4d7.whoami.myrealdomain.me:443/dns-query
DEBU[0000] [http] sending GET request to https://test-device-7cn4d7.whoami.myrealdomain.me:443/dns-query?dns=q0EBAAABAAAAAAAABmdvb2dsZQNjb20AAAEAAQ
FATA[0000] unpacking DNS response from https://test-device-7cn4d7.whoami.myrealdomain.me:443/dns-query?dns=q0EBAAABAAAAAAAABmdvb2dsZQNjb20AAAEAAQ: dns: bad data




./q @https://dns.google google.com
google.com. 58m26s TXT "apple-domain-verification=30afIBcvSuDV2PLX"
google.com. 58m26s TXT "google-site-verification=wD8N7i1JTNTkezJ49swvWW48f8_9xveREV4oB-0Hf5o"
google.com. 58m26s TXT "v=spf1 include:_spf.google.com ~all"
[a whole bunch of records...]
```

**Comment by ainar-g** [comment]
Thank you for the very thorough report.  The configuration and the request information, assuming AGH receives the same, look good, so it's a rather weird issue.  We'll add some more debug logging to the DoH ClientID detection, but in the meantime:

1. Is the proxy configuration the same for AGH as the one for this whoami service?
2. Just to be sure, does the reverse proxy talk to AGH over plain HTTP?
3. Is `tls.strict_sni_check` set to `true`?  Does it show errors with DoT and DoH if you do enable it?

**Comment by clstrickland** [comment]
Enabling strict SNI checking results in this: `[error] Error in the BeforeRequestHandler: getting clientid: clientid check: client server name "" doesn't match host server name "adguard.realdomain.com"`. All requests, even requests from inside the network which are whitelisted by source IP, don't work with DoH. Turning Strict SNI checking back off undoes this issue.

I am making the request from the reverse proxy to AdGuard using HTTPS. Actually, in my testing, it looks like requests to `/dns-request` return 404 over HTTP no matter what, and such requests don't show in the log. This is still the case when doing something like `http://192.168.1.1:3000/dns-request` directly, not just with the reverse proxy.

Whoami and AdGuard are configured in the same way. Here is the (relevant) Traefik config if it helps:

```yaml
  routers:
    adguard-https:
      rule: "HostRegexp(`adguard.realdomain.com`,`{subdomain:[a-z0-9-]+}.adguard.realdomain.com`)"
      service: adguard-https
      tls:
        certresolver: letsEncrypt
        domains:
        - main: "adguard.realdomain.com"
          sans:
            - "*.adguard.realdomain.com"
      entryPoints:
        - websecure
    whoami-https:
      rule: "HostRegexp(`whoami.realdomain.com`,`{subdomain:[a-z0-9-]+}.whoami.realdomain.com`)"
      service: whoami-https
      tls:
        certresolver: letsEncrypt
        domains:
        - main: "whoami.realdomain.com"
          sans:
            - "*.whoami.realdomain.com"
      entryPoints:
        - websecure


  services:
    adguard-https:
      loadBalancer:
        servers:
          - url: "https://192.168.1.1:8443"
    whoami-https:
      loadBalancer:
        servers:
          - url: "http://simple-service:80"
```

The backend uses different protocols (since whoami doesn't seem to support https, if you want I can try to find another testing container like this which does) but that shouldn't be affecting the headers.
