### ISSUE TITLE
Docker Containers can connect to AdGuard GUI but Unable to Resolve via host IP

### ISSUE THREAD

**Issue by jschwalbe** [AdguardTeam/AdGuardHome#6442]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, AMD64 (aka x86_64)

### Installation

Docker

### Setup

On one machine

### AdGuard Home version

v0.107.41

### Action

Please bear with me on this. It's a confusing issue.

First of all, adguard docker-compose.yml:
```
version: "3.9"
services:
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 3000:3000/tcp
      - 3001:80/tcp
      - 3002:8902/tcp
    volumes:
      - ./conf:/opt/adguardhome/conf
      - ./data:/opt/adguardhome/work
    restart: always
    network_mode: bridge
```

Pretty vanilla setup. 

The host IP here is `192.168.25.81`.

```sh
user@192.168.25.81$ nslookup google.com 192.168.25.81
<success>

# now try to resolve from another docker container:
user@192.168.25.81:~/docker-configs/mosquitto$ docker compose exec mosquitto nslookup google.com 192.168.25.81
;; connection timed out; no servers could be reached

# however, the adguard container can still be reached on different ports.. why is that??
user@192.168.25.81:~/docker-configs/mosquitto$ docker compose exec mosquitto wget 192.168.25.81:3001 -O -
Connecting to 192.168.25.81:3001 (192.168.25.81:3001)
writing to stdout
<!doctype html><html lang="en"><head><meta charset="utf-8"><me.... (snip)

### Expected result

I should be able to use the host IP to resolve from other containers. Since it can connect to the GUI, why can't it connect to the DNS server on port 53?

### Actual result

See above. Thank you!

### Additional information and/or screenshots

_No response_

**Comment by jschwalbe** [comment]
I'll even add that from within the adguard container itself, the above is also true.. (just realized this)

```sh
$ docker compose exec adguardhome nslookup google.com 192.168.25.81
;; connection timed out; no servers could be reached

$ docker compose exec adguardhome wget 192.168.25.81:3001 -O- -
Connecting to 192.168.25.81:3001 (192.168.25.81:3001)
writing to stdout
<!doctype html><html lang="en"><head> ...
```

**Comment by ainar-g** [comment]
As far as I know there is an internal address for containers, usually within 172.17.0.0/16 subnet.  See <https://docs.docker.com/compose/networking/>.  Have you tried resolving `adguardhome.` from within the containers?

**Comment by jschwalbe** [comment]
Thanks - I believe your assumptions are correct,  but that doesn’t explain why the web server responds to the docker host address, but the DNS server does not. 

My limited knowledge thinks it’s a configuration error akin to the web server listening on _all_ interfaces/IPs, but the DNS server only to certain ones?

To answer you question about resolving adguardhone, I believe that works, but it’s not reasonable to have my router tell all the hosts on my network to try to use `adguardhome`, bc my laptop will not know what that is.

**Comment by MADx00** [comment]
I am facing a similar issue, as I am using AGH with WireGuard (specifically [wg-easy](https://github.com/wg-easy/wg-easy)) as a DNS resolver, what is weirder in my case, is that I can see from UI that the DNS requests are received by AGH, and the A record is translated, but from the VPN client side no response is received 

![image](https://github.com/AdguardTeam/AdGuardHome/assets/12590045/79cea331-f48a-4ea2-af1a-56f4faea8ea2)

*IP addreess "192.168.192.1" looks like the gateway of docker network

My setup is:
AGH is deployed as a docker container, and WG (VPN clients) are trying to communicate with AGH through the host IP that links port 54 to AGH port 53

my docker-compose is

```
version: '3.5'
services:
  adguardhome:
    container_name: adguardhome
    image: adguard/adguardhome:latest
    restart: unless-stopped
    volumes: 
      - ./config-adguardhome/work:/opt/adguardhome/work
      - ./config-adguardhome/conf:/opt/adguardhome/conf
    ports:
      - "54:53/tcp"
      - "54:53/udp"
      - "80:80/tcp"

  wg-easy:
      - WG_HOST=<host ip>
      - WG_DEFAULT_DNS=<host ip>:54
    image: ghcr.io/wg-easy/wg-easy
    container_name: wg-easy
    volumes:
      - ./config-wg-easy:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
```

**Comment by nathan815** [comment]
@MADx00  I had the same exact issue and same set up - running wg-easy and AdGuardHome in docker containers on the same host. DNS resolution to AdGuardHome over WG did not work, but the server was in fact reachable through WG. I think what is happening is WG is routing it correctly, but AdGuardHome is sending the response out the wrong interface for some reason.

Here is what solved it for me:

1. Put both containers in the same docker network. In docker-compose this looks like:
```
services:
  wireguard:
     #...
     networks:
       - dns_network

  adguardhome:
     #...
     networks:
       - dns_network

networks:
  dns_network:
    name: dns_network

```

2. Explicitly bind the ports of the AdGuardHome container to the host IP. Say the IP of your host machine running the containers is `192.168.0.50`, then in docker-compose:
```
  adguardhome:
    # ...
    ports:
      - 192.168.0.50:53:53/tcp
      - 192.168.0.50:53:53/udp
```
