### ISSUE TITLE
Log bootstrap/upstream timeouts on ERROR level, not DEBUG

### ISSUE THREAD

**Issue by adoyle-h** [AdguardTeam/AdGuardHome#6574]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, AMD64 (aka x86_64)

### Installation

Docker

### Setup

On one machine

### AdGuard Home version

v0.107.43 and v0.108.0-b.51

### Action

1. The docker compose.yaml

```yaml
version: "3.9"

services:
  adg:
    # image: adguard/adguardhome:v0.108.0-b.51
    image: adguard/adguardhome:v0.107.43
    restart: unless-stopped
    volumes:
      - ./work:/opt/adguardhome/work
      - ./conf:/opt/adguardhome/conf
      - ./.lego/certificates:/opt/adguardhome/cert
    mac_address: F8:7D:36:12:11:FB
    networks:
      macvlan:
        ipv4_address: 192.168.1.61

networks:
  macvlan:
    driver: macvlan
    driver_opts:
      parent: enp1s0

    ipam:
      config:
        - subnet: "192.168.1.0/24"
          ip_range: "192.168.1.61/30"
          gateway: "192.168.1.2"
```

2. The ./conf/AdGuardHome.yaml

```
http:
  pprof:
    port: 6060
    enabled: false
  address: 0.0.0.0:80
  session_ttl: 4h
auth_attempts: 5
block_auth_min: 15
http_proxy: ""
language: en
theme: auto
dns:
  bind_hosts:
    - 0.0.0.0
  port: 53
  anonymize_client_ip: false
  ratelimit: 20
  ratelimit_subnet_len_ipv4: 24
  ratelimit_subnet_len_ipv6: 56
  ratelimit_whitelist: []
  refuse_any: true
  upstream_dns:
    - https://dns10.quad9.net/dns-query
  upstream_dns_file: /opt/adguardhome/conf/dns.rules
  bootstrap_dns:
    - tls://223.5.5.5
  fallback_dns:
    - https://1.1.1.1/dns-query
  all_servers: true
  fastest_addr: false
  fastest_timeout: 1s
  allowed_clients: []
  disallowed_clients: []
  blocked_hosts:
    - version.bind
    - id.server
    - hostname.bind
  trusted_proxies:
    - 127.0.0.0/8
    - ::1/128
  cache_size: 67108864
  cache_ttl_min: 600
  cache_ttl_max: 800
  cache_optimistic: false
  bogus_nxdomain: []
  aaaa_disabled: false
  enable_dnssec: false
  edns_client_subnet:
    custom_ip: ""
    enabled: false
    use_custom: false
  max_goroutines: 300
  handle_ddr: true
  ipset: []
  ipset_file: ""
  bootstrap_prefer_ipv6: false
  upstream_timeout: 10s
  private_networks: []
  use_private_ptr_resolvers: true
  local_ptr_upstreams: []
  use_dns64: false
  dns64_prefixes: []
  serve_http3: false
  use_http3_upstreams: false
  serve_plain_dns: true
tls:
  enabled: false
querylog:
  ignored: []
  interval: 168h
  size_memory: 1000
  enabled: true
  file_enabled: true
statistics:
  ignored: []
  interval: 720h
  enabled: true
filters: []
whitelist_filters: []
user_rules:
  - '@@||s.deepl.com^$important'
  - ""
dhcp:
  enabled: false
filtering:
  blocking_ipv4: ""
  blocking_ipv6: ""
  blocked_services:
    schedule:
      time_zone: UTC
    ids: []
  protection_disabled_until: null
  safe_search:
    enabled: false
    bing: true
    duckduckgo: true
    google: true
    pixabay: true
    yandex: true
    youtube: true
  blocking_mode: default
  parental_block_host: family-block.dns.adguard.com
  safebrowsing_block_host: standard-block.dns.adguard.com
  rewrites: []
  safebrowsing_cache_size: 1048576
  safesearch_cache_size: 1048576
  parental_cache_size: 1048576
  cache_time: 30
  filters_update_interval: 24
  blocked_response_ttl: 10
  filtering_enabled: true
  parental_enabled: false
  safebrowsing_enabled: false
  protection_enabled: true
clients:
  runtime_sources:
    whois: true
    arp: true
    rdns: true
    dhcp: true
    hosts: true
  persistent: []
log:
  file: ""
  max_backups: 0
  max_size: 100
  max_age: 3
  compress: false
  local_time: false
  verbose: false
os:
  group: ""
  user: ""
  rlimit_nofile: 0
schema_version: 27
```

3. The ./conf/dns.rules

```
https://doh.dns.sb/dns-query
[/ipip.net/]tls://223.5.5.5
```

4. `docker compose up -d`

5. Send DNS request

```sh
nslookup -debug -type=a 'www.baidu.com'
```

### Expected result

The query log shows DNS server using `https://doh.dns.sb/dns-query`.

### Actual result

It seems the default upstream (https://doh.dns.sb/dns-query) is ignored in upstream_dns_file.
All DNS queries use the fallback_dns (https://1.1.1.1:443/dns-query).

![CleanShot 2023-12-22 at 21 00 48@2x](https://github.com/AdguardTeam/AdGuardHome/assets/1998490/63d9f1d2-8863-4754-ac50-06ebab3234d3)

The query log shows that adguard home using the DNS server `https://1.1.1.1:443/dns-query` which is my fallback_dns.

But when `nslookup www.ipip.net`, which domain defined in upstream_dns_file, the query log shows the DNS server using `tls://223.5.5.5:853`.

```sh
> nslookup www.ipip.net
Server:         192.168.1.61
Address:        192.168.1.61#53

Non-authoritative answer:
www.ipip.net    canonical name = 8d2070e4.ipip.net.cname.yunduns.com.
Name:   8d2070e4.ipip.net.cname.yunduns.com
Address: 220.185.183.49
Name:   8d2070e4.ipip.net.cname.yunduns.com
Address: 220.185.183.30
```

![CleanShot 2023-12-22 at 21 14 01@2x](https://github.com/AdguardTeam/AdGuardHome/assets/1998490/ef8948e1-aea0-4f02-8643-7b2f2eaa58ac)

### Additional information and/or screenshots

There is no `https://doh.dns.sb/dns-query` in top upstreams.

![CleanShot 2023-12-22 at 21 16 21@2x](https://github.com/AdguardTeam/AdGuardHome/assets/1998490/bd7c11f2-39ed-4c2e-b7cc-8286144dd1eb)
