### ISSUE TITLE
Custom Upstreams Cache Not Working

### ISSUE THREAD

**Issue by WildByDesign** [AdguardTeam/AdGuardHome#6596]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, ARMv7

### Installation

GitHub releases or script from README

### Setup

On a router, DHCP is handled by AdGuard Home

### AdGuard Home version

v0.107.43

### Action

Recently, AGH added the new feature for Custom Upstreams Cache (`upstreams_cache_enabled` and `upstreams_cache_size`).

After using that new setting for a few weeks, I realized that it was not caching requests.

### Expected result

Expected custom upstream requests to be cached.

### Actual result

![AGH-upstreams_cache_enabled](https://github.com/AdguardTeam/AdGuardHome/assets/26308319/06eecec9-c802-456b-9f59-4ae93bf1b0a0)

From the Dashboard screenshot above, the clients circled in blue and their corresponding upstreams appear to be caching correctly. These do no have custom upstream servers specified.

The clients circled in red and their corresponding upstreams do have custom upstream servers specified along with the new settings `upstreams_cache_enabled` and `upstreams_cache_size`. From the dashboard, it appears that the custom upstream servers are taking all of their requests and none are being cached.

I enabled the Query Log and monitored those clients for some period of time and observed no requests being served from cache.

### Additional information and/or screenshots

Persistent client info from adguardhome.yaml:

```
    - safe_search:
        enabled: true
        bing: true
        duckduckgo: true
        google: true
        pixabay: true
        yandex: true
        youtube: true
      blocked_services:
        schedule:
          time_zone: UTC
        ids:
          - roblox
      name: redacted
      ids:
        - redacted
        - redacted
        - redacted
      tags: []
      upstreams:
        - 208.67.222.123
        - 208.67.220.123
      upstreams_cache_size: 1048576
      upstreams_cache_enabled: true
      use_global_settings: false
      filtering_enabled: true
      parental_enabled: false
      safebrowsing_enabled: false
      use_global_blocked_services: true
      ignore_querylog: false
      ignore_statistics: false
    - safe_search:
        enabled: true
        bing: true
        duckduckgo: true
        google: true
        pixabay: true
        yandex: true
        youtube: false
      blocked_services:
        schedule:
          time_zone: UTC
        ids:
          - roblox
      name: redacted
      ids:
        - redacted
        - redacted
        - redacted
      tags: []
      upstreams:
        - 208.67.222.123
        - 208.67.220.123
      upstreams_cache_size: 1048576
      upstreams_cache_enabled: true
      use_global_settings: false
      filtering_enabled: true
      parental_enabled: false
      safebrowsing_enabled: false
      use_global_blocked_services: true
      ignore_querylog: false
      ignore_statistics: false
```
