### ISSUE TITLE
Settings page fail to load in v0.94 Ubuntu 

### ISSUE THREAD

**Issue by leon332157** [AdguardTeam/AdGuardHome#664]
### Steps to reproduce

1. Open a browser and load the server address 127.0.0.1:3000
2. Go to the settings tab

### Expected behavior

The settings page being loaded.

### Actual behavior

The page blanks out after loading for a short amount of time.

<details><summary>Screenshot:</summary>
 ![1](https://user-images.githubusercontent.com/30728609/54874716-371d2b80-4dc7-11e9-917f-25384007c121.png)
 ![2](https://user-images.githubusercontent.com/30728609/54874717-37b5c200-4dc7-11e9-8f8a-a82af55b455a.png)

</details>

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| Version of AdGuard Home server:| v 0.94
| How did you setup DNS configuration:| Home Sever with router dns configuration
| If it's a router or IoT, please write device model:| Lenovo X200
| Operating system and version:| Ubuntu 18.10 x64
## PS: This only seems to happen with a configuration Yaml file from older vesion: v0.92, renaming the old configuration and re-configuring fixed the issue.

**Comment by leon332157** [comment]
### Just in case the screenshots didn't work 
![1](https://user-images.githubusercontent.com/30728609/54874755-d9d5aa00-4dc7-11e9-8068-e31f77b7fb31.png)
![2](https://user-images.githubusercontent.com/30728609/54874756-dfcb8b00-4dc7-11e9-99cc-548d96cf33cc.png)

**Comment by ameshkov** [comment]
@leon332157 what exact browser version do you use?

**Comment by ameshkov** [comment]
> PS: This only seems to happen with a configuration Yaml file from older vesion: v0.92, renaming the old configuration and re-configuring fixed the issue.

So you were upgrading from v0.92 to v0.94 directly and something went wrong, right?

**Comment by leon332157** [comment]
The version is Mozilla Firefox 65.0.1 on Ubuntu X86_64

**Comment by szolin** [comment]
I couldn't reproduce the issue with the default yaml config created by v0.92-hotfix2 (linux, firefox 65).
Can you share your config file with us?

**Comment by leon332157** [comment]
```yaml
bind_host: 127.0.0.1
bind_port: 3000
auth_name: ****
auth_pass: ****
language: ""
dns:
  bind_host: 0.0.0.0
  port: 53
  protection_enabled: true
  filtering_enabled: true
  blocked_response_ttl: 10
  querylog_enabled: true
  ratelimit: 20
  ratelimit_whitelist: []
  refuse_any: true
  bootstrap_dns:
  - 8.8.8.8:53
  all_servers: false
  parental_sensitivity: 0
  parental_enabled: false
  safesearch_enabled: false
  safebrowsing_enabled: false
  upstream_dns:
  - tls://9.9.9.9
tls:
  enabled: false
  server_name: ""
  force_https: false
  port_https: 443
  port_dns_over_tls: 853
  certificate_chain: ""
  private_key: ""
filters:
- enabled: true
  url: https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt
  name: AdGuard Simplified Domain Names filter
  id: 1
- enabled: true
  url: https://adaway.org/hosts.txt
  name: AdAway
  id: 2
- enabled: false
  url: https://hosts-file.net/ad_servers.txt
  name: hpHosts - Ad and Tracking servers only
  id: 3
- enabled: false
  url: http://www.malwaredomainlist.com/hostslist/hosts.txt
  name: MalwareDomainList.com Hosts List
  id: 4
- enabled: true
  url: https://easylist.to/easylist/easylist.txt
  name: EasyList
  id: 1548646703
user_rules:
- **. ** . ** . ** proxy.belmont.k12.ma.us
- '@@||apple.com^'
- '@@||itunes.apple.com'
- '@@||brawalstars.com^'
- '||lsmdm.com^'
- '@@||supercell.com^'
- '||openresolvetest.net^'
- '@@||qq.com^'
- '||tracking.prd.mz.internal.unity3d.com^'
- '@@||appsflyer.com^'
- '@@||loggly.com^'
- '||iphantom.com^'
- '||iboss.com^'
- '@@||tweakboxapp.com^'
- '@@||downtutu.com^'
- '||xferrecords.com^'
dhcp:
  enabled: false
  interface_name: enp0s25
  gateway_ip: ""
  subnet_mask: ""
  range_start: ""
  range_end: ""
  lease_duration: 0
  icmp_timeout_msec: 0
log_file: ""
verbose: false
schema_version: 3
```
