### ISSUE TITLE
[Help Wanted] Unable to use AGH as DHCP Server

### ISSUE THREAD

**Issue by jslawler** [AdguardTeam/AdGuardHome#681]
Enabling DHCP server on AGH results in not being able to connect to internet or AGH, however router is still accessible.
This has worked in the past. After doing a wipe of my Raspberry Pi I have been unable to get the Pi(AGH) to act as a DHCP server.

### Steps to reproduce
1. Enable DHCP  post-setup on AGH
2. Disable router DHCP server

### Expected behavior
AdGuardHome to act as DHCP server.

### Actual behavior
Internet and AGH is inaccessible.
Couldn't listen to 192.168.178.60:68, cause: listen udp4 192.168.178.60:68: bind: address already in use

<details><summary>Screenshot:</summary>
<img width="1195" alt="Screen Shot 2019-03-29 at 05 11 32" src="https://user-images.githubusercontent.com/6005161/55185950-61873400-518d-11e9-8dd8-2cf5926c565d.png">
<img width="1177" alt="Screen Shot 2019-03-29 at 05 11 14" src="https://user-images.githubusercontent.com/6005161/55185954-64822480-518d-11e9-9a1b-dfb343914cb1.png">

</details>

### Your environment
```
AdGuard.yaml
bind_host: 0.0.0.0
bind_port: 80
auth_name: pi
auth_pass: 
language: ""
dns:
  bind_host: 0.0.0.0
  port: 53
  protection_enabled: true
  filtering_enabled: true
  blocked_response_ttl: 10
  querylog_enabled: true
  ratelimit: 20
  ratelimit_whitelist: []
  refuse_any: true
  bootstrap_dns:
  - 1.1.1.1:53
  all_servers: true
  parental_sensitivity: 13
  parental_enabled: false
  safesearch_enabled: false
  safebrowsing_enabled: true
  upstream_dns:
  - https://dns.adguard.com/dns-query
  - tls://dns.adguard.com
tls:
  enabled: false
  server_name: ""
  force_https: false
  port_https: 443
  port_dns_over_tls: 853
  certificate_chain: ""
  private_key: ""
filters:
- enabled: true
  url: https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt
  name: AdGuard Simplified Domain Names filter
  id: 1
- enabled: true
  url: https://adaway.org/hosts.txt
  name: ""
  id: 2
- enabled: true
  url: https://hosts-file.net/ad_servers.txt
  name: ""
  id: 3
- enabled: true
  url: https://www.malwaredomainlist.com/hostslist/hosts.txt
  name: ""
  id: 4
user_rules:
- ""
dhcp:
  enabled: true
  interface_name: eth0
  gateway_ip: 192.168.178.1
  subnet_mask: 255.255.255.0
  range_start: 192.168.178.20
  range_end: 192.168.178.200
  lease_duration: 864000
  icmp_timeout_msec: 0
log_file: ""
verbose: false
schema_version: 3
```

|   Description  |     Value    |
| -------------- | ------------ |
| Version of AdGuard Home server:| 0.94
| How did you setup DNS configuration:| Raspberry Pi 3 Model B+, Fritz Box 7290
| Operating system and version:| Raspbian GNU/Linux 9.8 (stretch)
