### ISSUE TITLE
AdGuard Home Default Filter Names

### ISSUE THREAD

**Issue by jslawler** [AdguardTeam/AdGuardHome#690]
As you can see from the AdGuardHome.yaml export below, only 1 of the 4 filters that come default with AdGuardHome have a name set.
I'd suggest adding a name for the remaining 3.
The list of names should be:

1. AdGuard Simplified Domain Names filter
2. AdAway default blocklist
3. hpHosts - Ad and Tracking servers only
4. MalwareDomainList.com Hosts List

```
filters:
- enabled: true
  url: https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt
  name: AdGuard Simplified Domain Names filter
  id: 1
- enabled: true
  url: https://adaway.org/hosts.txt
  name: ""
  id: 2
- enabled: true
  url: https://hosts-file.net/ad_servers.txt
  name: ""
  id: 3
- enabled: true
  url: https://www.malwaredomainlist.com/hostslist/hosts.txt
  name: ""
  id: 4
```
