### ISSUE TITLE
Seemingly randomly not responding to requests for a short period, then starts working again

### ISSUE THREAD

**Issue by Edgeburn** [AdguardTeam/AdGuardHome#7048]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, AMD64 (aka x86_64)

### Installation

Docker

### Setup

On a router, DHCP is handled by the router

### AdGuard Home version

v0.107.50

### Action

DNS queries over plain DNS, DoH and DoT

### Expected result

Consistent responses

### Actual result

Seemingly random drops that last anywhere from a few seconds to a few minutes

### Additional information and/or screenshots

I often see the following in the logs during the dropouts, with the first censored IP address being that of the server, and the second being that of the client. Note that it does _not_ only occur in DNS over TLS, this just happened to be the excerpt I picked out of similar log entries.

```
handling tcp: reading msg: connection timed out; original error: reading len: read tcp *.*.*.*:853->*.*.*.*:50751: i/o timeout
```

I have tried changing the upstream DNS servers and this made no difference. 

I also changed the network mode to `host` for the container in my docker compose (AdGuard Home section of which is below) and no longer putting it behind nginx-proxy-manager. 

```yaml
services:
    adguardhome:
        image: adguard/adguardhome
        container_name: adguardhome
        network_mode: host
        environment:
            TZ: America/Toronto
        volumes:
            - /home/edgeburnmedia/adguardhome/conf:/opt/adguardhome/conf
            - /home/edgeburnmedia/adguardhome/work:/opt/adguardhome/work
            - /home/edgeburnmedia/nginx-proxy-manager/letsencrypt:/etc/letsencrypt
        # ports:
            # # DNS
            # - 53:53
            # # DHCP server
            # # - 67:67/udp
            # # - 68:68/udp
            # # HTTPS/DNS-over-HTTPS
            # - 443:443/tcp
            # # DNS-over-TLS
            # - 853:853/tcp
            # # DNS-over-QUIC
            # - 853:853/udp
            # # DNSCrypt
            # - 5443:5443/tcp
            # - 5443:5443/udp
            # # WebUI
            # - 3000:3000/tcp
        restart: unless-stopped
```

Full logs are available at the following gist: https://gist.github.com/Edgeburn/e10e360a264240bc1cf5ac2717af1819
