### ISSUE TITLE
A record of many IP issues?

### ISSUE THREAD

**Issue by ohmypage** [AdguardTeam/AdGuardHome#7143]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Windows, AMD64 (aka x86_64)

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

v0.107.52

### Action

```sh
nslookup -debug -type=a rc10.oray.com 127.0.0.1
------------
Got answer:
    HEADER:
        opcode = QUERY, id = 1, rcode = NOERROR
        header flags:  response, want recursion, recursion avail.
        questions = 1,  answers = 1,  authority records = 0,  additional = 1

    QUESTIONS:
        1.0.0.127.in-addr.arpa, type = PTR, class = IN
    ANSWERS:
    ->  1.0.0.127.in-addr.arpa
        name = localhost
        ttl = 79617 (22 hours 6 mins 57 secs)
    ADDITIONAL RECORDS:
    ->  (root)
        ??? unknown type 41 ???
        ttl = 0 (0 secs)

------------
Server:  localhost
Address:  127.0.0.1

DNS request timed out.
    timeout was 2 seconds.
timeout (2 secs)
DNS request timed out.
    timeout was 2 seconds.
timeout (2 secs)
```

### Expected result

```sh
nslookup -debug -type=a rc10.oray.com 9.9.9.9
------------
Got answer:
    HEADER:
        opcode = QUERY, id = 1, rcode = NOERROR
        header flags:  response, want recursion, recursion avail.
        questions = 1,  answers = 1,  authority records = 0,  additional = 0

    QUESTIONS:
        9.9.9.9.in-addr.arpa, type = PTR, class = IN
    ANSWERS:
    ->  9.9.9.9.in-addr.arpa
        name = dns9.quad9.net
        ttl = 41248 (11 hours 27 mins 28 secs)

------------
Server:  dns9.quad9.net
Address:  9.9.9.9

------------
Got answer:
    HEADER:
        opcode = QUERY, id = 2, rcode = NOERROR
        header flags:  response, want recursion, recursion avail.
        questions = 1,  answers = 27,  authority records = 0,  additional = 0

    QUESTIONS:
        rc10.oray.com, type = A, class = IN
    ANSWERS:
    ->  rc10.oray.com
        internet address = 121.196.96.156
        ttl = 60 (1 min)
    ->  rc10.oray.com
        internet address = 121.196.43.191
        ttl = 60 (1 min)
    ->  rc10.oray.com
        internet address = 47.114.81.143
        ttl = 60 (1 min)
    ->  rc10.oray.com
        internet address = 121.196.106.244
        ttl = 60 (1 min)
    ->  rc10.oray.com
        internet address = 47.110.161.178
        ttl = 60 (1 min)
    ->  rc10.oray.com
        internet address = 47.111.154.78
        ttl = 60 (1 min)
    ->  rc10.oray.com
        internet address = 121.196.101.104
        ttl = 60 (1 min)
    ->  rc10.oray.com
        internet address = 121.196.107.102
        ttl = 60 (1 min)
    ->  rc10.oray.com
        internet address = 121.196.109.191
        ttl = 60 (1 min)
    ->  rc10.oray.com
        internet address = 121.196.41.207
        ttl = 60 (1 min)
    ->  rc10.oray.com
        internet address = 121.196.110.195
        ttl = 60 (1 min)
    ->  rc10.oray.com
        internet address = 121.196.105.75
        ttl = 60 (1 min)
    ->  rc10.oray.com
        internet address = 121.196.40.208
        ttl = 60 (1 min)
    ->  rc10.oray.com
        internet address = 47.114.105.242
        ttl = 60 (1 min)
    ->  rc10.oray.com
        internet address = 121.196.104.209
        ttl = 60 (1 min)
    ->  rc10.oray.com
        internet address = 121.196.111.17
        ttl = 60 (1 min)
    ->  rc10.oray.com
        internet address = 121.196.44.195
        ttl = 60 (1 min)
    ->  rc10.oray.com
        internet address = 47.114.116.61
        ttl = 60 (1 min)
    ->  rc10.oray.com
        internet address = 121.196.105.213
        ttl = 60 (1 min)
    ->  rc10.oray.com
        internet address = 121.196.111.176
        ttl = 60 (1 min)
    ->  rc10.oray.com
        internet address = 121.196.100.49
        ttl = 60 (1 min)
    ->  rc10.oray.com
        internet address = 121.196.44.127
        ttl = 60 (1 min)
    ->  rc10.oray.com
        internet address = 121.196.110.56
        ttl = 60 (1 min)
    ->  rc10.oray.com
        internet address = 121.196.102.112
        ttl = 60 (1 min)
    ->  rc10.oray.com
        internet address = 121.196.42.43
        ttl = 60 (1 min)
    ->  rc10.oray.com
        internet address = 121.196.106.171
        ttl = 60 (1 min)
    ->  rc10.oray.com
        internet address = 121.196.110.124
        ttl = 60 (1 min)

------------
Server:    rc10.oray.com
Addresses:  121.196.96.156
          121.196.43.191
          47.114.81.143
          121.196.106.244
          47.110.161.178
          47.111.154.78
          121.196.101.104
          121.196.107.102
          121.196.109.191
          121.196.41.207
          121.196.110.195
          121.196.105.75
          121.196.40.208
          47.114.105.242
          121.196.104.209
          121.196.111.17
          121.196.44.195
          47.114.116.61
          121.196.105.213
          121.196.111.176
          121.196.100.49
          121.196.44.127
          121.196.110.56
          121.196.102.112
          121.196.42.43
          121.196.106.171
          121.196.110.124
```

### Actual result

ADGuard Home Server no respond.

### Additional information and/or screenshots

config:
```yaml
http:
  pprof:
    port: 6060
    enabled: false
  address: 127.0.0.1:8053
  session_ttl: 720h
users:
  - name: admin
    password: mask
auth_attempts: 5
block_auth_min: 15
http_proxy: ""
language: en
theme: auto
dns:
  bind_hosts:
    - 0.0.0.0
  port: 53
  anonymize_client_ip: false
  ratelimit: 50
  ratelimit_subnet_len_ipv4: 24
  ratelimit_subnet_len_ipv6: 56
  ratelimit_whitelist: []
  refuse_any: true
  upstream_dns:
    - https://120.53.53.53/dns-query
    - https://223.5.5.5/dns-query
  upstream_dns_file: ""
  bootstrap_dns:
    - 119.29.29.29
    - 223.5.5.5
    - 114.114.114.114
  fallback_dns: []
  upstream_mode: load_balance
  fastest_timeout: 1s
  allowed_clients: []
  disallowed_clients: []
  blocked_hosts:
    - version.bind
    - id.server
    - hostname.bind
  trusted_proxies:
    - 127.0.0.0/8
    - ::1/128
  cache_size: 4194304
  cache_ttl_min: 0
  cache_ttl_max: 0
  cache_optimistic: true
  bogus_nxdomain: []
  aaaa_disabled: true
  enable_dnssec: false
  edns_client_subnet:
    custom_ip: 202.96.128.88
    enabled: true
    use_custom: true
  max_goroutines: 300
  handle_ddr: true
  ipset: []
  ipset_file: ""
  bootstrap_prefer_ipv6: false
  upstream_timeout: 10s
  private_networks: []
  use_private_ptr_resolvers: true
  local_ptr_upstreams:
    - 172.20.20.20
  use_dns64: false
  dns64_prefixes: []
  serve_http3: false
  use_http3_upstreams: false
  serve_plain_dns: true
  hostsfile_enabled: true
tls:
  enabled: false
  server_name: ""
  force_https: false
  port_https: 443
  port_dns_over_tls: 853
  port_dns_over_quic: 853
  port_dnscrypt: 0
  dnscrypt_config_file: ""
  allow_unencrypted_doh: false
  certificate_chain: ""
  private_key: ""
  certificate_path: ""
  private_key_path: ""
  strict_sni_check: false
querylog:
  dir_path: ""
  ignored: []
  interval: 2160h
  size_memory: 1000
  enabled: true
  file_enabled: true
statistics:
  dir_path: ""
  ignored: []
  interval: 2160h
  enabled: true
filters:
  - enabled: false
    url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_1.txt
    name: AdGuard DNS filter
    id: 1
  - enabled: false
    url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_2.txt
    name: AdAway Default Blocklist
    id: 2
whitelist_filters: []
user_rules:
  - ""
dhcp:
  enabled: false
  interface_name: ""
  local_domain_name: lan
  dhcpv4:
    gateway_ip: ""
    subnet_mask: ""
    range_start: ""
    range_end: ""
    lease_duration: 86400
    icmp_timeout_msec: 1000
    options: []
  dhcpv6:
    range_start: ""
    lease_duration: 86400
    ra_slaac_only: false
    ra_allow_slaac: false
filtering:
  blocking_ipv4: ""
  blocking_ipv6: ""
  blocked_services:
    schedule:
      time_zone: Local
    ids: []
  protection_disabled_until: null
  safe_search:
    enabled: false
    bing: true
    duckduckgo: true
    google: true
    pixabay: true
    yandex: true
    youtube: true
  blocking_mode: default
  parental_block_host: family-block.dns.adguard.com
  safebrowsing_block_host: standard-block.dns.adguard.com
  rewrites:
    - domain: cauth.example.com
      answer: 172.16.15.178
  safebrowsing_cache_size: 1048576
  safesearch_cache_size: 1048576
  parental_cache_size: 1048576
  cache_time: 30
  filters_update_interval: 24
  blocked_response_ttl: 10
  filtering_enabled: true
  parental_enabled: false
  safebrowsing_enabled: false
  protection_enabled: true
clients:
  runtime_sources:
    whois: true
    arp: true
    rdns: true
    dhcp: true
    hosts: true
  persistent: []
log:
  enabled: true
  file: ""
  max_backups: 0
  max_size: 100
  max_age: 3
  compress: false
  local_time: false
  verbose: false
os:
  group: ""
  user: ""
  rlimit_nofile: 0
schema_version: 28
```
