### ISSUE TITLE
DNS rewrite by CIDR

### ISSUE THREAD

**Issue by rhoriguchi** [AdguardTeam/AdGuardHome#7189]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

It would be cool to have an option to have DNS rewrite rules for certain IP ranges. I have multiple VLANs with transition rules so certain VLANs can't reach certain IPs. So it would be nice that I can disable rewrites for certain ranges. Currently that causes certain domains do not return anything since they are blocked by the firewall.

Host: 192.168.1.15
```
> nslookup test.com
Server:         192.168.1.1
Address:        192.168.1.1#53

Non-authoritative answer:
Name:   test.com
Address: 192.168.2.2
```

Host: 192.168.10.15 (here I don't want a rewrite rule so it should return a public IP)
```
> nslookup test.com
Server:         192.168.1.1
Address:        192.168.1.1#53

Non-authoritative answer:
Name:   test.com
Address: 3.18.255.247
Name:   test.com
Address: 34.224.149.186
```

### Proposed solution

Some way to configure what IP ranges which has a DNS rewrite rule, default would be `*` so any IP.

```yaml
filtering:
  rewrites:
    - domain: test.com
      answer: 192.168.2.2
      cidr:
        - 192.168.1.0/24
        - 192.168.2.0/24
    - domain: some-other-domain.com
      answer: 192.168.1.1
      cidr: * # this does not have to be set, so fully backward compatible
 ```
