### ISSUE TITLE
DNS rewrites responding twice and causing errors in clients

### ISSUE THREAD

**Issue by fskaeh** [AdguardTeam/AdGuardHome#7255]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, ARM64

### Installation

Docker

### Setup

On one machine

### AdGuard Home version

v0.107.52

### Action

Since this morning, DNS rewrites seems to be misbehaving on my AGH server. My setup is as follows:
# AGH installed as one Docker container

``` yml
name: adguard
services:
  adguard:
    container_name: adguard
    dns:
      - 172.88.88.1
    image: adguard/adguardhome:latest
    networks:
      - global
    platform: linux/arm64/v8
    ports:
      - 53:53
      - 53:53/udp
    restart: unless-stopped
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
networks:
  global:
    external: true
```

# Application XYZ installed as another Docker container (Bazarr in this example but other containers have the same issue)
``` yml
name: bazarr
services:
  bazarr:
    container_name: bazarr
    dns:
      - 172.88.88.1
    image: linuxserver/bazarr:latest
    networks:
      - global
    platform: linux/arm64/v8
    restart: unless-stopped
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
networks:
  global:
    external: true
```

# Both containers are inside the same bridge network
``` yml
name: global
services:
  global:
    container_name: global
    dns:
      - 172.88.88.1
    image: hello-world
    networks:
      - global
    platform: linux/arm64/v8
networks:
  global:
    enable_ipv6: true
    driver: bridge
    name: global
    ipam:
      driver: default
      config:
        - subnet: 172.88.88.0/24
          gateway: 172.88.88.1
        - subnet: fd00:dead:beef::/80
          gateway: fd00:dead:beef::1
```

# Docker config file
``` json
{
  "iptables" : true,
  "features" : {
    "buildkit" : true
  },
  "ip6tables" : true,
  "experimental" : true,
  "builder" : {
    "gc" : {
      "defaultKeepStorage" : "20GB",
      "enabled" : true
    }
  },
  "userland-proxy" : false
}
```

This setup has worked fine for the past several months, and allows all my containers to use AGH as a DNS to benefit from my DNS rewrites to reach other containers via their full URLs without having to set public DNS records on Cloudflare for all my services.

Since this morning, this has stopped working. What happens is as follows:
- Container A will perform a DNS query for `container-b.mydomain.xyz`
- The request shows in the query list in AGH, but twice. One of the responses actually returns the proper IP for container B, the other apparently gets forwarded to AGH's upstream (Quad9) and returns NXDOMAIN (which makes sense since there's not public DNS record for container B)
- The client (container A) apparently gets the NXDOMAIN response rather than the IP, and therefore fails to reach container B.

I haven't made any change to my setup or config in at least 6 months.

### Expected result

DNS rewrites should continue to return only the IP I set in the config instead of forwarding queries to upstream servers.

### Actual result

DNS rewrites are answered twice: once with NXDOMAIN and once with the proper IP, leading to errors in clients.

### Additional information and/or screenshots

# DNS query being performed from a client (Docker container)
<img width="406" alt="Screenshot 2024-09-09 at 11 25 22" src="https://github.com/user-attachments/assets/896d42c4-00ec-47dc-ace4-8f6d0489aae6">

# The query showing up twice in the query list in AGH
<img width="1174" alt="Screenshot 2024-09-09 at 11 24 43" src="https://github.com/user-attachments/assets/48bc7a12-54a0-4e83-8491-150dab71fd9f">

# One correct response
<img width="1174" alt="365594732-aaa107c0-64da-4f80-929b-d87548430db0" src="https://github.com/user-attachments/assets/1790f87c-ebb0-4909-acc7-bb1a170aedd0">

# One NXDOMAIN response due to the query being inexplicably forwarded to Quad9
<img width="1174" alt="365594735-b0b0a50b-e543-427e-abf5-34d61ce30bf9" src="https://github.com/user-attachments/assets/dd308424-8635-4f68-a43a-5c8e31ff2c30">
