### ISSUE TITLE
LetsEncrypt certificate chain invalid 

### ISSUE THREAD

**Issue by fonix232** [AdguardTeam/AdGuardHome#758]
I'm trying to configure Adguard Home on my cloud server which uses Docker to separate concerns, and the [linuxserver.io Let's Encrypt image](https://github.com/linuxserver/docker-letsencrypt) for proxying subdomains. 

I've added the generated wildcard certificate and private key through the Settings page (I know, linking to the keys folder of the exposed volume of the letsencrypt container would be a better solution and I will start using that once everything is set up). However it throws an error for the certificate:

Status:
- Certificate chain is invalid
- Subject: CN=*.fonix232.me
- Issuer: CN=Let's Encrypt Authority X3,O=Let's Encrypt,C=US
- Expires: 2019-08-13 01:10:42
- Hostnames: *.fonix232.mefonix232.me

This certificate has worked for me for all the subdomains, yet AdguardHome says it's invalid.

### Steps to reproduce
1. Set up linuxserver/letsencrypt with wildcard domain
2. Set up AdguardHome
3. Add keys generated by the letsencrypt container to AGH
4. Watch the error appear

### Expected behavior
One would expect the key to be accepted since it's a valid Let's Encrypt certificate

### Actual behavior
Let's Encrypt key is claimed invalid.

</details>

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| Version of AdGuard Home server:| v0.95-hotfix
| How did you setup DNS configuration:| System
| If it's a router or IoT, please write device model:| Various Android phones on Android Pie
| Operating system and version:| Varies with manufacturer

**Comment by fonix232** [comment]
![image](https://user-images.githubusercontent.com/371847/57834863-254b7980-77b5-11e9-99ab-d3375e5acec2.png)

**Comment by ameshkov** [comment]
Hi! It just means that the root certificate is missing on your Linux machine.

AGH looks for it in these locations:
https://golang.org/src/crypto/x509/root_linux.go

**Comment by fonix232** [comment]
That's interesting, since the Docker image is supposed to have built-in SSL cert requests from Let's Encrypt - so basically that wouldn't work either?

**Comment by ameshkov** [comment]
Well, yeah:)

There is another possible cause: have you copy/pasted the full chain or the leaf certificate only? If the intermediate certificate is missing, AGH won't be able to validate the chain (it won't be able to connect root to leaf).

**Comment by Omoeba** [comment]
where is the location of the built-in ssl certificates from the docker image?

**Comment by ameshkov** [comment]
I am not an expert, but since it's Linux, it should be in one of the places listed here: https://golang.org/src/crypto/x509/root_linux.go

**Comment by fabh2o** [comment]
The solution is adding the root certificate manually.
In my case I have a Cloudflare certificate, so I need to add the Cloudflare Origin CA root certificate (the .pem can be found [here](https://support.cloudflare.com/hc/en-us/articles/115000479507-Managing-Cloudflare-Origin-CA-certificates))
The AGH docker image is built on top of Alpine Linux, so the default certificate path is `/etc/ssl/cert.pem`. In the container it's a link to `/etc/ssl/certs/ca-certificates.crt`, so we can append our root certificate like so `cat downloadedRootCert.pem >> /etc/ssl/certs/ca-certificates.crt`.
Note that this isn't a permanent solution, all changes are lost once the container is restarted/recreated

**Comment by jpeizer** [comment]
After a lot of digging I have found what should be a decent long term solution for this issue.

Create a config map holding the root-ca.pem similar to:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflare-root-ca.crt
data:
  origin_ca_rsa_root.pem: |-
    -----BEGIN CERTIFICATE-----
    MIIEADCCAuigAwIBAgIID+...
```

Then create a new mount for the deployment:
```yaml
spec:
  containers:
  - image: adguard/adguardhome:latest
     volumeMounts:
     - mountPath: /etc/ssl/certs/origin_ca_rsa_root.pem
       name: cloudflare-root-ca
       subPath: origin_ca_rsa_root.pem
  - configMap:
          defaultMode: 256
          name: cloudflare-root-ca.crt
          optional: false
        name: cloudflare-root-ca
```

Now you have the root ca inside the container on every deployment, after this was make a delayed command to the deployed container.
```yaml
ports:
  - containerPort: 3000
lifecycle:
  postStart:
    exec:
      command: ["/bin/sh", "-c", "cd /etc/ssl/certs && cat origin_ca_rsa_root.pem >> ca-certificates.crt"]
```

Now every time the container restarts or recreated the root is added and appended to the bottom of ca-certificates.crt

I have not done a lot of testing on this but initial setup appears to work perfectly fine.

**Comment by kiwilad-nz** [comment]
I have just migrated this from my docker install over to FreeBSD (pfSense).
I have the same issue. How do I go about it on FreeBSD?
Apparently the certs pulled via the Acme package aren't stored locally but only in config but was trying to copy paste the cert/private key and ran into the same problem.

**Comment by marcodantonio** [comment]
> Then create a new mount for the deployment:

Can you help me to do that?

**Comment by jeromelarras** [comment]
Bonjour
J’utilise votre solution sur un NAS Synology DS720PLUS
Dans la partie chiffrement que j’ai activé, j’ai renseigné le nom DDNS de mon NAS, les ports que j’ai configurés pour l’interface et les protocoles dns tls et quic éventuellement.
Comme vous pouvez le constater, j’ai indiqué les chemins par défaut de mon certificat et de sa clé privée dans la partie chiffrement.
 
Cependant la chaine de certificat semble ne pas plaire intégralement. 
J’ai lu qu’il faudrait avoir le certificat et le root ensemble.
J’ai testé avec un copié collé, j’obtiens toujours « chaine de certificat non valide », avec une date en 2035.
Pouvez vous m’indiquer ce que je dois changer ? Ainsi, je pourrai demander au support Synology, de voir ce qu’il serait possible de faire pour ce fameux « root », si c’est ça l’origine du problème.
Dans cette attente, merci pour votre aide.

Jérôme L
![message d'erreur](https://user-images.githubusercontent.com/107620682/213481742-ff086ba3-f5d7-492c-af03-7b3326142866.png)

**Comment by ouncool** [comment]
@fabh2o  Thanks，I tested a scenario where restarting the container does not affect the certificate chain.

**my environment** 
- Host my domain with Cloudflare.
- https://hub.docker.com/r/adguard/adguardhome

```shell
wget https://developers.cloudflare.com/ssl/static/origin_ca_rsa_root.pem /my/own/confdir
docker exec -it <AdGuard Home ID> /bin/sh 
# Inside the docker container
cat /opt/adguardhome/conf/origin_ca_rsa_root.pem >> /etc/ssl/certs/ca-certificates.crt
ps -ef  # the pid of adguardhome is 1 by default
kill 1  # container auto restart and exit
# now，encryption_chain_valid
docker stop  adguardhome 
docker start  adguardhome 
docker restart  adguardhome 
# encryption_chain_valid，it's work.
```

**Comment by zullkas** [comment]
> The solution is adding the root certificate manually. In my case I have a Cloudflare certificate, so I need to add the Cloudflare Origin CA root certificate (the .pem can be found [here](https://support.cloudflare.com/hc/en-us/articles/115000479507-Managing-Cloudflare-Origin-CA-certificates)) The AGH docker image is built on top of Alpine Linux, so the default certificate path is `/etc/ssl/cert.pem`. In the container it's a link to `/etc/ssl/certs/ca-certificates.crt`, so we can append our root certificate like so `cat downloadedRootCert.pem >> /etc/ssl/certs/ca-certificates.crt`. Note that this isn't a permanent solution, all changes are lost once the container is restarted/recreated

This helped, thanks. 
When using a standalone install, you need to restart the AdGuard service:
`/opt/AdGuardHome/AdGuardHome -s restart`

**Comment by ugmac** [comment]
Just to add a tip:

To prevent the root certs reset when pulling a new image, make a copy of the updated ca-certificates.crt and bind it in docker-compose.yaml in the 'volumes' block.

`      - type: bind
        source: <path-on-persistent-storage>/ca-certificates.crt
        target: /etc/ssl/certs/ca-certificates.crt
`

**Comment by sigma2017** [comment]
I am using LetsEncrypt and i can't see any ca-certificates.crt. Where from can I get it?
Having the same issue btw...
Thanks in advance

**Comment by xlionjuan** [comment]
```yaml
services:
  app:
    container_name: adguard
    image: adguard/adguardhome:latest
    volumes:
      - ./conf:/opt/adguardhome/conf
      - ./work:/opt/adguardhome/work
      - /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt:ro
```
