### ISSUE TITLE
no querylog output in openwrt

### ISSUE THREAD

**Issue by james-li** [AdguardTeam/AdGuardHome#7639]
### Prerequisites

- [x] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [x] I have searched other issues and found no duplicates

- [x] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [x] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, ARMv7

### Installation

GitHub releases or script from README

### Setup

On a router, DHCP is handled by the router

### AdGuard Home version

AdGuard Home, version v0.107.56

### Action

Replace the following command with the one you're calling or a
description of the failing action:

```sh
nslookup -debug -type=a 'www.x.com'  192.168.10.1
```

### Expected result

In `/opt/AdGuardHome/data/`, there should be a record in `querylog.json`

### Actual result

no record in `querylog.json`

### Additional information and/or screenshots

openwrt version: `openwrt/releases/22.03.7/packages/aarch64_cortex-a53`

/etc/Adg.yaml:
```
http:
  pprof:
    port: 6060
    enabled: false
  address: 0.0.0.0:3000
  session_ttl: 720h
users:
  - name: admin
    password: 
auth_attempts: 5
block_auth_min: 15
http_proxy: ""
language: ""
theme: auto
dns:
  bind_hosts:
    - 0.0.0.0
  port: 53
  anonymize_client_ip: false
  ratelimit: 20
  ratelimit_subnet_len_ipv4: 24
  ratelimit_subnet_len_ipv6: 56
  ratelimit_whitelist: []
  refuse_any: true
  upstream_dns:
    - 127.0.0.1:7874
  upstream_dns_file: ""
  bootstrap_dns:
    - 9.9.9.10
    - 149.112.112.10
    - 2620:fe::10
    - 2620:fe::fe:10
  fallback_dns: []
  upstream_mode: load_balance
  fastest_timeout: 1s
  allowed_clients: []
  disallowed_clients: []
  blocked_hosts:
    - version.bind
    - id.server
    - hostname.bind
  trusted_proxies:
    - 127.0.0.0/8
    - ::1/128
  cache_size: 0
  cache_ttl_min: 0
  cache_ttl_max: 0
  cache_optimistic: false
  bogus_nxdomain: []
  aaaa_disabled: false
  enable_dnssec: false
  edns_client_subnet:
    custom_ip: ""
    enabled: false
    use_custom: false
  max_goroutines: 300
  handle_ddr: true
  ipset: []
  ipset_file: ""
  bootstrap_prefer_ipv6: false
  upstream_timeout: 10s
  private_networks: []
  use_private_ptr_resolvers: false
  local_ptr_upstreams: []
  use_dns64: false
  dns64_prefixes: []
  serve_http3: false
  use_http3_upstreams: false
  serve_plain_dns: true
  hostsfile_enabled: true
tls:
  enabled: false
  server_name: ""
  force_https: false
  port_https: 443
  port_dns_over_tls: 853
  port_dns_over_quic: 853
  port_dnscrypt: 0
  dnscrypt_config_file: ""
  allow_unencrypted_doh: false
  certificate_chain: ""
  private_key: ""
  certificate_path: ""
  private_key_path: ""
  strict_sni_check: false
querylog:
  dir_path: ""
  ignored: []
  interval: 2160h
  size_memory: 10000
  enabled: true
  file_enabled: true
statistics:
  dir_path: ""
  ignored: []
  interval: 24h
  enabled: true
filters:
  - enabled: true
    url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_1.txt
    name: AdGuard DNS filter
    id: 1
  - enabled: true
    url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_2.txt
    name: AdAway Default Blocklist
    id: 2
whitelist_filters: []
user_rules: []
dhcp:
  enabled: false
  interface_name: ""
  local_domain_name: lan
  dhcpv4:
    gateway_ip: ""
    subnet_mask: ""
    range_start: ""
    range_end: ""
    lease_duration: 86400
    icmp_timeout_msec: 1000
    options: []
  dhcpv6:
    range_start: ""
    lease_duration: 86400
    ra_slaac_only: false
    ra_allow_slaac: false
filtering:
  blocking_ipv4: ""
  blocking_ipv6: ""
  blocked_services:
    schedule:
      time_zone: UTC
    ids: []
  protection_disabled_until: null
  safe_search:
    enabled: false
    bing: true
    duckduckgo: true
    ecosia: true
    google: true
    pixabay: true
    yandex: true
    youtube: true
  blocking_mode: default
  parental_block_host: family-block.dns.adguard.com
  safebrowsing_block_host: standard-block.dns.adguard.com
  rewrites: []
  safe_fs_patterns:
    - /usr/bin/AdGuardHome/userfilters/*
  safebrowsing_cache_size: 1048576
  safesearch_cache_size: 1048576
  parental_cache_size: 1048576
  cache_time: 30
  filters_update_interval: 24
  blocked_response_ttl: 10
  filtering_enabled: true
  parental_enabled: false
  safebrowsing_enabled: false
  protection_enabled: true
clients:
  runtime_sources:
    whois: true
    arp: true
    rdns: true
    dhcp: true
    hosts: true
  persistent:
    - safe_search:
        enabled: false
        bing: true
        duckduckgo: true
        ecosia: true
        google: true
        pixabay: true
        yandex: true
        youtube: true
      blocked_services:
        schedule:
          time_zone: UTC
        ids: []
      name: 客户端 192.168.10.15
      ids:
        - 192.168.10.15
      tags:
        - device_nas
      upstreams: []
      uid: 019482e9-8141-72d9-b5cd-e1cfddc200c0
      upstreams_cache_size: 0
      upstreams_cache_enabled: false
      use_global_settings: true
      filtering_enabled: false
      parental_enabled: false
      safebrowsing_enabled: false
      use_global_blocked_services: true
      ignore_querylog: false
      ignore_statistics: false
log:
  enabled: true
  file: ""
  max_backups: 0
  max_size: 100
  max_age: 3
  compress: false
  local_time: false
  verbose: true
os:
  group: ""
  user: ""
  rlimit_nofile: 0
schema_version: 29

```

```
# uci show|grep -i adg
AdGuardHome.AdGuardHome=AdGuardHome
AdGuardHome.AdGuardHome.httpport='3000'
AdGuardHome.AdGuardHome.configpath='/etc/AdGuardHome.yaml'
AdGuardHome.AdGuardHome.logfile='/tmp/AdGuardHome.log'
AdGuardHome.AdGuardHome.binpath='/usr/bin/AdGuardHome'
AdGuardHome.AdGuardHome.workdir='/opt/AdGuardHome'
AdGuardHome.AdGuardHome.keepdb='0'
AdGuardHome.AdGuardHome.waitonboot='1'
AdGuardHome.AdGuardHome.enabled='1'
AdGuardHome.AdGuardHome.ucitracktest='0'
AdGuardHome.AdGuardHome.lastworkdir='/opt/AdGuardHome'
AdGuardHome.AdGuardHome.lastlogfile='/tmp/AdGuardHome.log'
AdGuardHome.AdGuardHome.hostsmd5='5504bb04bd01cb0e340aee9e2ae065b2'
AdGuardHome.AdGuardHome.redirect='exchange'
AdGuardHome.AdGuardHome.version='v0.107.56'
AdGuardHome.AdGuardHome.binmtime='1737640919'
AdGuardHome.AdGuardHome.verbose='1'
AdGuardHome.AdGuardHome.backupwdpath='/opt/AdGuardHome'
AdGuardHome.AdGuardHome.old_redirect='exchange'
AdGuardHome.AdGuardHome.old_port='5300'
AdGuardHome.AdGuardHome.old_enabled='1'
```
