### ISSUE TITLE
Domain Rewrite failed

### ISSUE THREAD

**Issue by binLep** [AdguardTeam/AdGuardHome#7672]
### Prerequisites

- [x] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [x] I have searched other issues and found no duplicates

- [x] I want to request a feature or enhancement and not ask a question

### The problem

- version:  v0.107.57

normalizing legacy rewrite: ParseAddr("download-cdn.jetbrains.com.cn"): unexpected character (at "download-cdn.jetbrains.com.cn")

```yaml
  rewrites:
    - domain: redirector.jetbrains.com.cn
      answer: download-cdn.jetbrains.com.cn
```

### Proposed solution

add support
