### ISSUE TITLE
IPv6 DNS upstream won't work.

### ISSUE THREAD

**Issue by 80kk** [AdguardTeam/AdGuardHome#7727]
### Prerequisites

- [x] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [x] I have searched other issues and found no duplicates

- [x] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [x] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, AMD64 (aka x86_64)

### Installation

Docker

### Setup

On one machine

### AdGuard Home version

0.107.57

### Action

I am trying to configure two upstream DNS servers, one for IPv4 and one for IPv6, both are configured on another VM running Bind DNS. However no matter in what format I supply IPv6 upstream DNS it always failing `Test Upstream` feature saying:
```Server "[2a00:1234:567:b01::7]:53": could not be used, please check that you've written it correctly```
How this section should look like?
```
dns:
  bind_hosts:
    - 0.0.0.0
  port: 53
  anonymize_client_ip: false
  ratelimit: 2000
  ratelimit_subnet_len_ipv4: 24
  ratelimit_subnet_len_ipv6: 64
  ratelimit_whitelist: []
  refuse_any: true
  upstream_dns:
    - 192.168.20.7
    - 2a00:1234:567:b01::7
  upstream_dns_file: ""
```
I've tried in [] in '', in "". https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuring-upstreams isn't helpful.

### Expected result

Pass the upstream test.

### Actual result

Failing
