### ISSUE TITLE
Retry failed private rDNS before cache expiry

### ISSUE THREAD

**Issue by pduchnovsky** [AdguardTeam/AdGuardHome#7743]
### Prerequisites

- [x] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [x] I have searched other issues and found no duplicates

- [x] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [x] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, AMD64 (aka x86_64)

### Installation

Docker

### Setup

On one machine

### AdGuard Home version

v0.107.59

### Action

1. Set up coredns docker container address as Private reverse DNS server
![Image](https://github.com/user-attachments/assets/4ddabb9e-e118-45f2-8745-f0296153ad41)
2. Start both adguard and coredns at the same time (using docker-compose)

### Expected result

I would expect adguard home to re-try using Private reverse DNS server after failure, rather than trying once and then disregarding it forever until restart.

### Actual result

Adguard home probably tries to contact Private reverse DNS server after start, it fails because coredns instance is still not ready to serve, then it continues to ignore it completely, unless adguard home is restarted, or Private reverse DNS server entry is re-done and saved again.

### Additional information and/or screenshots

docker-compose

```
version: '4'

x-defaults: &defaults
  restart: always
  mem_swappiness: "1"
  security_opt:
    - no-new-privileges:true

services:
  adguard:
    <<: *defaults
    image: adguard/adguardhome
    container_name: adguard
    network_mode: host
    environment:
      - TZ=Europe/Amsterdam
    labels:
      - traefik.enable=true
      - traefik.http.services.adguard.loadbalancer.server.port=3000
      - traefik.http.routers.adguard.rule=Host(`adguard.${TRAEFIK_DOMAIN}`)
      - traefik.http.routers.adguard.entrypoints=websecure
      - traefik.http.routers.adguard.middlewares=internal@file
    volumes:
      - /volume1/docker/adguard/conf:/opt/adguardhome/conf
      - /volume1/docker/adguard/work:/opt/adguardhome/work
    mem_limit: 700m
    memswap_limit: 700m

  coredns:
    <<: *defaults
    image: ghcr.io/dougbw/coredns_omada@sha256:f95d7d342bdd82c2625a4c9313ae83d0a79db917501ba878e15b50b82b1f9b09
    container_name: coredns
    ports:
      - 127.0.0.1:5053:53/udp
    environment:
      - TZ=Europe/Amsterdam
      - OMADA_URL=https://${SERVER_LAN_IP}:8043
      - OMADA_SITE=Default
      - OMADA_USERNAME=${OMADA_USERNAME}
      - OMADA_PASSWORD=${OMADA_PASSWORD}
      - OMADA_DISABLE_HTTPS_VERIFICATION=true
    volumes:
      - /volume1/docker/coredns/Corefile:/Corefile
    mem_limit: 100m
    memswap_limit: 100m
```
