### ISSUE TITLE
Upgrade to v0.108.0-b.67 failed

### ISSUE THREAD

**Issue by rphillips** [AdguardTeam/AdGuardHome#7773]
### Prerequisites

- [x] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [x] I have searched other issues and found no duplicates

- [x] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [x] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, AMD64 (aka x86_64)

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

v0.108.0-b.67

### Action

I upgraded to v0.108.0-b.67 using the automated button within the website. Usually this works fine, but with this release the AdguardHome binary is failing to start.

```
root@adguard:/opt/AdGuardHome# ./AdGuardHome
2025/04/17 19:19:48.692167 [info] AdGuard Home, version v0.108.0-b.67
2025/04/17 19:19:48.695718 [info] tls_manager: using default ciphers
2025/04/17 19:19:48.700403 [info] Initializing auth module: /opt/AdGuardHome/data/sessions.db
2025/04/17 19:19:48.700538 [info] auth: initialized.  users:1  sessions:3
2025/04/17 19:19:48.700749 [info] webapi: initializing
2025/04/17 19:19:48.722541 [error] closing query log: flushing log buffer: nothing to write to a file
2025/04/17 19:19:48.722613 [fatal] newServerConfig: constructing tls config: parsing tls key pair: tls: failed to find any PEM data in certificate input
```

```
root@adguard:/opt/AdGuardHome# ./AdGuardHome --version
AdGuard Home, version v0.108.0-b.67
```

Partial Config:

```
tls:
  enabled: true
  server_name: <redacted>
  force_https: false
  port_https: 55355
  port_dns_over_tls: 785
  port_dns_over_quic: 784
  port_dnscrypt: 0
  dnscrypt_config_file: ""
  allow_unencrypted_doh: true
  certificate_chain: ""
  private_key: ""
  certificate_path: ""
  private_key_path: ""
  strict_sni_check: false
```

### Expected result

Upgrades should be backwards compatible.

### Actual result

AdguardHome binary is erroring out upon start.

**Comment by rphillips** [comment]
Downgrading to v0.108.0-b.66 does work. The AdguardHome binary successfully starts up.

**Comment by ainar-g** [comment]
@rphillips, just to be clear, do you actually have neither certificate data nor certificate path in the TLS config?  Are you using that `enabled: true` for `allow_unencrypted_doh: true`?

**Comment by ainar-g** [comment]
@schzhn, please investigate.  It might be that the new validation is too strict and doesn't allow users to enable unencrypted DoH without adding certificates, which is a common configuration for AGH instances behind proxies.

**Comment by rphillips** [comment]
@ainar-g Yes, correct. I have a reverse proxy proxying to the Adguard backend for DOH. There are not any Adguard certificates or keys setup.

**Comment by EugeneOne1** [comment]
@rphillips, hello.  We've just released the [beta release](https://github.com/AdguardTeam/AdGuardHome/releases/tag/v0.108.0-b.68) that should handle the certificates absence correctly.  Could you please confirm if this fixes the issue?

**Comment by chris-1243** [comment]
Sorry to jump in, I have a similar error on latest release v0.107.62 using Docker.


I use `DNSCrypt` and have to set the tls to `true` according to documentation

```
newServerConfig: constructing
tls config: parsing tls key
pair: tls: failed to find any
PEM data in certificate input
```

```
tls:
  enabled: true
  server_name: ""
  force_https: false
  port_https: 443
  port_dns_over_tls: 853
  port_dns_over_quic: 853
  port_dnscrypt: some_value
  dnscrypt_config_file: /opt/adguardhome/conf/dnscrypt.yaml
  allow_unencrypted_doh: false
  certificate_chain: ""
  private_key: ""
  certificate_path: ""
  private_key_path: ""
  strict_sni_check: false
```

V0.107.61 is perfectly working with the `tls` configuration above.

The only way to have v0.107.62 working with my setup is to have

```
allow_unencrypted_doh: true
```

but I do not use DoH only DNSCrypt.

**Comment by rphillips** [comment]
This bug is back with 0.107.74. 

Logs:

```
May 07 22:28:37  systemd[1]: Started AdGuard Home: Network-level blocker.
May 07 22:28:37  AdGuardHome[2177]: 2026/05/07 22:28:37.163147 [info] starting adguard home version="AdGuard Home, version 0.107.74"
May 07 22:28:37  AdGuardHome[2177]: 2026/05/07 22:28:37.165874 [info] dhcpd: warning: creating dhcpv4 server err="dhcpv4: invalid IP is not an IPv4 address"
May 07 22:28:37  AdGuardHome[2177]: 2026/05/07 22:28:37.166281 [info] tls_manager: using default ciphers
May 07 22:28:37  AdGuardHome[2177]: 2026/05/07 22:28:37.170949 [info] webapi: initializing
May 07 22:28:37  AdGuardHome[2177]: 2026/05/07 22:28:37.172019 [info] filtering: warning: filter has no id idx=0 new_id=1778192918
May 07 22:28:37  AdGuardHome[2177]: 2026/05/07 22:28:37.174344 [fatal] creating dns server: newServerConfig: constructing tls config: parsing tls key pair: tls: failed to find any PEM data in certificate input
```

**Comment by herdir** [comment]
Hitting this too, on stable **v0.107.73**, so somewhere between the 0.107.62 report and the 0.107.74 "it's back" comment above. Same exact fatal:

```
2026/08/14 07:21:52.970929 [fatal] newServerConfig: constructing tls config: parsing tls key pair: tls: failed to find any PEM data in certificate input
```

My config had `tls.enabled: true` but all four cert fields blank:
```yaml
tls:
  enabled: true
  certificate_chain: ""
  private_key: ""
  certificate_path: ""
  private_key_path: ""
```

This one's on a GL.iNet GL-MT6000, and it turned into a bigger mess than just "AGH won't start." The router's DNS setup redirects all LAN traffic on port 53 straight to AGH regardless of whether it's actually running, so the crash loop took down internet for every device on the network, silently, until I tracked it down. Given it's shown up on 0.107.62, 0.107.73, and 0.107.74, this really doesn't seem like a one-off. Happy to attach full logs/config if it'd help pin it down.
