### ISSUE TITLE
V0.107.62 update failed

### ISSUE THREAD

**Issue by chris-1243** [AdguardTeam/AdGuardHome#7856]
### Prerequisites

- [x] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [x] I have searched other issues and found no duplicates

- [x] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [x] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, AMD64 (aka x86_64)

### Installation

Docker

### Setup

On one machine

### AdGuard Home version

V0.107.62

### Action

I updated from V0.107.61 to V0.107.62 via docker pull command. Usually, it works perfectly fine but not this time

```
adguardhome  | 2025/05/31 23:02:55.989284 [info] AdGuard Home, version v0.107.62
adguardhome  | 2025/05/31 23:02:56.009015 [info] tls_manager: using default ciphers
adguardhome  | 2025/05/31 23:02:56.023864 [info] Initializing auth module: /opt/adguardhome/work/data/sessions.db
adguardhome  | 2025/05/31 23:02:56.024232 [info] auth: initialized.  users:1  sessions:0
adguardhome  | 2025/05/31 23:02:56.024337 [info] webapi: initializing
adguardhome  | 2025/05/31 23:02:56.194808 [error] closing query log: flushing log buffer: nothing to write to a file
adguardhome  | 2025/05/31 23:02:56.194847 [fatal] newServerConfig: constructing tls config: parsing tls key pair: tls: failed to find any PEM data in certificate input
adguardhome exited with code 0
```

Below, my `tls` section

```
tls:
  enabled: true
  server_name: ""
  force_https: false
  port_https: 443
  port_dns_over_tls: 853
  port_dns_over_quic: 853
  port_dnscrypt: some_value
  dnscrypt_config_file: /opt/adguardhome/conf/dnscrypt.yaml
  allow_unencrypted_doh: false
  certificate_chain: ""
  private_key: ""
  certificate_path: ""
  private_key_path: ""
  strict_sni_check: false
```

I do not use DoH, only DNSCrypt. According to the documentation, there is nothing more to add.
https://github.com/AdguardTeam/Adguardhome/wiki/DNSCrypt

### Expected result

V0.107.62 to work like previous working version

### Actual result

No errors at start-up

### Additional information and/or screenshots

This issue looks very similar to https://github.com/AdguardTeam/AdGuardHome/issues/7773

As a work around, I have set 

`allow_unencrypted_doh: true`

V0.107.62 is now starting correctly. What bother me, I do not use DoH and this setting was not used previously.

**Comment by tjharman** [comment]
Thanks I agree that's a duplicate of https://github.com/AdguardTeam/AdGuardHome/issues/7773

**Comment by tjharman** [comment]
Apologies, I see that issue is closed and you've been asked to open a new ticket.

**Comment by kairusds** [comment]
I've been wondering why my reverse proxy setup is failing and I guess this is the issue. I'm using Traefik, I reverse proxied the DoT/DoQ ports and the only results I get are either the logs giving me a `bad certificate` error if I set the same cerfiicates as Traefik or the ports not starting at all if I left the certificate fields empty on the config.

**Comment by oncetap** [comment]
This might be the reason why my reverse proxy setup DoT/DoQ with ADGH is failing, as the docs never stated these changes anywhere. If I use the same certificates on my reverse proxy as ADGH, I get a bad certificate error, and if I set it to empty, DoT/DoQ doesn't work at all.

**Comment by NikhilMunda** [comment]
Yesterday, on 23 Jun I also faced the same issue on V0.107.62. After I updated the version from V0.107.61 Its worked fine for 2-3 days. Suddenly it stopped working showing "Update checked failed, Please check your internet connection" Only WhatsApp is working for sending messages. I checked My internet is working fine. It is installed on raspberry pi 3B+, internet is working fine on raspberry pi as i was able ping and update, only the issue is with adguard. If there is an easy fix I would really like to know.

**Comment by mix3d** [comment]
This happened to me after updating my Proxmox LXC adguard container, which has been working fine for almost 7 months. I got the same error message after updating to .72, and switching that flag to true is working again. 

I've never touched the config manually before, only editing settings through the UI. 

My config, after manually turning `allow_unencrypted_doh` to true, no other changes:

```
tls:
  enabled: true
  server_name: adguard.<mydomain>
  force_https: false
  port_https: 443
  port_dns_over_tls: 853
  port_dns_over_quic: 853
  port_dnscrypt: 0
  dnscrypt_config_file: ""
  allow_unencrypted_doh: true
  certificate_chain: ""
  private_key: ""
  certificate_path: ""
  private_key_path: ""
  strict_sni_check: false
```
