### ISSUE TITLE
Allow multiple IPs/CIDRs and MACs per client

### ISSUE THREAD

**Issue by Bluscream** [AdguardTeam/AdGuardHome#809]
Something like

```yaml
clients:
- name: My PC
  ips:
  - 192.168.2.55 # LAN IPv4
  - 2003:e3:9f10:7100:8145:9eff:d6d4:12b9 # LAN IPv6
  - 192.168.2.56 # WiFi IPv4
  - 2003:e3:9f10:7100:8145:9eff:d6d4:12b9 # WiFi IPv6
  macs:
  - 1C-1B-0D-76-8B-F1 # LAN
  - 1C-1B-0D-76-8B-F2 # WiFi
  use_global_settings: true
  filtering_enabled: false
  parental_enabled: false
  safebrowsing_enabled: false
  safesearch_enabled: false
```

So they can share the same settings and name in the statistics

- [ ] Allow IPv6 entries https://github.com/AdguardTeam/AdGuardHome/issues/727#issuecomment-493659533
- [ ] Change the config parser and migration of old configs
- [ ] Use UI multiline textbox for multiple MAC/IP entries
- [ ] Show MACs/IPs textbox at the same time
