### ISSUE TITLE
Add an option to block access to specific Services

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardHome#819]
One more NextDNS feature I find quite cool:
https://uploads.adguard.com/up04_d2jvi_Services_-_My_First_Configuration_-_nextdns.png

However, it makes sense only if we allow blocking these on a per-client basis.

**Comment by ameshkov** [comment]
The current implementation lacks global "services" settings:

Add "Blocked services" setting to General settings.

**Comment by bzy39** [comment]
While on this, why not create a form to add custom blocked services? like DNS rewrite.
and the configuration like
```
services:
  - id: tiktok
    name: TikTok
	rules:
	- '||snssdk.com^'
	- '||amemv.com^'
	- '||toutiao.com^'
	- '||ixigua.com^'
	- '||pstatp.com^'
	- '||ixiguavideo.com^'
	- '||toutiaocloud.com^'
	- '||toutiaocloud.net^'
	- '||bdurl.com^'
	- '||bytecdn.cn^'
	- '||byteimg.com^'
	- '||ixigua.com^'
  - id: twitter
	name: Twitter 
	rules:
	- '||twitter.com^'
	- '||t.co^'
	- '||twimg.com^'
```
