### ISSUE TITLE
Android Phone failed to obtain ip address

### ISSUE THREAD

**Issue by rt400** [AdguardTeam/AdGuardHome#883]
HI,
i just install yesterday the Adguard on Docker.
i use with DHCP server and only my phone cannot obtain ip address from server (phone is samsung s5 android 6) , in my work i have the same server and i install Adguard in docker also and the phone is get ip quickly ( so its not phone problem) , i also try to delete leases DB and still the problem. so now i set in my phone a static IP .
i wonder what the can be the problem ( i come from Pi-Hole and there idont have this problem)
this is my config :
```
bind_host: 0.0.0.0
bind_port: 88
auth_name: ""
auth_pass: ""
language: ""
rlimit_nofile: 0
dns:
  bind_host: 0.0.0.0
  port: 53
  protection_enabled: true
  filtering_enabled: true
  blocking_mode: nxdomain
  blocked_response_ttl: 10
  querylog_enabled: true
  ratelimit: 20
  ratelimit_whitelist: []
  refuse_any: true
  bootstrap_dns:
  - 1.1.1.1:53
  all_servers: true
  allowed_clients: []
  disallowed_clients: []
  blocked_hosts: []
  parental_sensitivity: 0
  parental_enabled: false
  safesearch_enabled: false
  safebrowsing_enabled: false
  resolveraddress: ""
  upstream_dns:
  - https://dns.cloudflare.com/dns-query
tls:
  enabled: false
  server_name: ""
  force_https: false
  port_https: 443
  port_dns_over_tls: 853
  certificate_chain: ""
  private_key: ""
filters:
- enabled: true
  url: https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt
  name: AdGuard Simplified Domain Names filter
  id: 1
- enabled: true
  url: https://adaway.org/hosts.txt
  name: AdAway
  id: 2
- enabled: true
  url: https://hosts-file.net/ad_servers.txt
  name: hpHosts - Ad and Tracking servers only
  id: 3
- enabled: true
  url: https://www.malwaredomainlist.com/hostslist/hosts.txt
  name: MalwareDomainList.com Hosts List
  id: 4
user_rules: []
dhcp:
  enabled: true
  interface_name: eno1
  gateway_ip: 192.168.1.253
  subnet_mask: 255.255.253.0
  range_start: 192.168.0.10
  range_end: 192.168.1.200
  lease_duration: 86400
  icmp_timeout_msec: 1000
clients: []
log_file: ""
verbose: false
schema_version: 3 
```
