### ISSUE TITLE
Add TikTok to Blocked services

### ISSUE THREAD

**Issue by lifansama** [AdguardTeam/AdGuardHome#950]
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

Here are some rules may help you
```
||snssdk.com^
||amemv.com^
||toutiao.com^
||ixigua.com^
||pstatp.com^
||ixiguavideo.com^
||toutiaocloud.com^
||toutiaocloud.net^
||bdurl.com^
||bytecdn.cn^
||byteimg.com^
||ixigua.com^

**Comment by ArchiveBase** [comment]
TikTok listed on nextdns.io https://github.com/AdguardTeam/AdGuardHome/issues/819 maybe @ameshkov lazy to add it ;)
Anyway @lifansama you can add above rules to Filters > Custom filtering rules. Just some're higher visitor ranked websites

**Comment by bzy39** [comment]
While on this, why not create a form to add custom blocked services? like DNS rewrite.

**Comment by bzy39** [comment]
While on this, why not create a form to add custom blocked services? like DNS rewrite.
and the configuration like
```
services:
  - id: tiktok
    name: TikTok
	rules:
	- '||snssdk.com^'
	- '||amemv.com^'
	- '||toutiao.com^'
	- '||ixigua.com^'
	- '||pstatp.com^'
	- '||ixiguavideo.com^'
	- '||toutiaocloud.com^'
	- '||toutiaocloud.net^'
	- '||bdurl.com^'
	- '||bytecdn.cn^'
	- '||byteimg.com^'
	- '||ixigua.com^'
  - id: twitter
	name: Twitter 
	rules:
	- '||twitter.com^'
	- '||t.co^'
	- '||twimg.com^'
```
